import csv
import re


def looks_like_header_cell(value: str) -> bool:
    if value is None:
        return False

    value = str(value).strip()

    if not value:
        return False

    if len(value) > 40:
        return False

    if value.lower().startswith("generated by"):
        return False

    return bool(re.search(r"[A-Za-z]", value))


def detect_csv_schema(file_path: str, max_rows: int = 10):
    best_row = None
    best_score = -1

    with open(file_path, "r", encoding="utf-8-sig", newline="") as csvfile:
        reader = csv.reader(csvfile)

        for index, row in enumerate(reader):
            if index >= max_rows:
                break

            clean_row = [cell.strip() for cell in row if cell.strip()]

            if not clean_row:
                continue

            score = sum(1 for cell in clean_row if looks_like_header_cell(cell))

            if len(clean_row) >= 2 and score > best_score:
                best_score = score
                best_row = clean_row

    if not best_row:
        return ""

    columns = []

    for col in best_row:
        clean = (
            col.lower()
            .replace(" ", "_")
            .replace("%", "percent")
            .replace("-", "_")
        )
        columns.append(clean)

    return f"uploaded_data({', '.join(columns)})"