import csv
import sqlite3
import re


def clean_column_name(name: str) -> str:
    name = name.strip().lower()
    name = name.replace("%", "percent")
    name = re.sub(r"[^a-zA-Z0-9_]+", "_", name)
    name = name.strip("_")

    if not name:
        name = "column"

    return name


def load_csv_to_sqlite(csv_path: str, db_path: str = "app_data.db", table_name: str = "uploaded_data"):
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    with open(csv_path, "r", encoding="utf-8-sig", newline="") as file:
        rows = list(csv.reader(file))

    if not rows:
        conn.close()
        return {"success": False, "message": "CSV file is empty"}

    header_index = None
    headers = None

    for i, row in enumerate(rows[:10]):
        clean_row = [cell.strip() for cell in row if cell.strip()]

        if len(clean_row) >= 2 and not clean_row[0].lower().startswith("generated by"):
            header_index = i
            headers = clean_row
            break

    if header_index is None or headers is None:
        conn.close()
        return {"success": False, "message": "Could not detect CSV header"}

    columns = [clean_column_name(col) for col in headers]

    cursor.execute(f"DROP TABLE IF EXISTS {table_name}")

    column_defs = ", ".join([f'"{col}" TEXT' for col in columns])

    cursor.execute(f"""
        CREATE TABLE {table_name} (
            {column_defs}
        )
    """)

    placeholders = ", ".join(["?"] * len(columns))
    quoted_columns = ", ".join([f'"{col}"' for col in columns])

    for row in rows[header_index + 1:]:
        values = row[:len(columns)]

        if len(values) < len(columns):
            values += [""] * (len(columns) - len(values))

        cursor.execute(
            f"""
            INSERT INTO {table_name} ({quoted_columns})
            VALUES ({placeholders})
            """,
            values,
        )

    conn.commit()
    conn.close()

    return {
        "success": True,
        "table": table_name,
        "columns": columns,
        "rows_inserted": len(rows) - header_index - 1,
    }