import csv
import sqlite3
import re


def infer_sqlite_type(values):
    non_empty_values = []

    for value in values:
        value = str(value).strip()

        if value == "":
            continue

        non_empty_values.append(value)

    if not non_empty_values:
        return "TEXT"

    has_decimal = False

    for value in non_empty_values:
        cleaned_value = value.replace(",", "")

        if cleaned_value.endswith("%"):
            cleaned_value = cleaned_value[:-1]
            has_decimal = True

        try:
            number = float(cleaned_value)

            if not number.is_integer():
                has_decimal = True

        except ValueError:
            return "TEXT"

    if has_decimal:
        return "REAL"

    return "INTEGER"


def clean_column_name(name: str) -> str:
    name = name.strip().lower()
    name = name.replace("%", "percent")
    name = re.sub(r"[^a-zA-Z0-9_]+", "_", name)
    name = name.strip("_")

    if not name:
        name = "column"

    return name


def load_csv_to_sqlite(csv_path: str, db_path: str = "app_data.db", table_name: str = "uploaded_data"):
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    with open(csv_path, "r", encoding="utf-8-sig", newline="") as file:
        rows = list(csv.reader(file))

    if not rows:
        conn.close()
        return {"success": False, "message": "CSV file is empty"}

    header_index = None
    headers = None

    for i, row in enumerate(rows[:10]):
        clean_row = [cell.strip() for cell in row if cell.strip()]

        if len(clean_row) >= 2 and not clean_row[0].lower().startswith("generated by"):
            header_index = i
            headers = clean_row
            break

    if header_index is None or headers is None:
        conn.close()
        return {"success": False, "message": "Could not detect CSV header"}

    columns = [clean_column_name(col) for col in headers]

    cursor.execute(f"DROP TABLE IF EXISTS {table_name}")

    column_type = {}

    for index, col in enumerate(columns):
        values = []

        for row in rows[header_index + 1:]:
            if index < len(row):
                values.append(row[index])

        column_type[col] = infer_sqlite_type(values)
    
    print("COLUMN TYPES:", column_type, flush=True)

    column_defs = ", ".join([
        f'"{col}" {column_type[col]}'
        for col in columns
    ])

    cursor.execute(f"""
        CREATE TABLE {table_name} (
            {column_defs}
        )
    """)

    placeholders = ", ".join(["?"] * len(columns))
    quoted_columns = ", ".join([f'"{col}"' for col in columns])

    for row in rows[header_index + 1:]:
        values = []

        for index, col in enumerate(columns):
            raw_value = row[index] if index < len(row) else ""
            raw_value = str(raw_value).strip().replace(",", "")

            if raw_value.endswith("%"):
                raw_value = raw_value[:-1]

            if raw_value == "":
                values.append(None)
            elif column_type[col] == "INTEGER":
                values.append(int(float(raw_value)))
            elif column_type[col] == "REAL":
                values.append(float(raw_value))
            else:
                values.append(raw_value)


        if len(values) < len(columns):
            values += [""] * (len(columns) - len(values))

        cursor.execute(
            f"""
            INSERT INTO {table_name} ({quoted_columns})
            VALUES ({placeholders})
            """,
            values,
        )

    conn.commit()
    conn.close()

    return {
        "success": True,
        "table": table_name,
        "columns": columns,
        "rows_inserted": len(rows) - header_index - 1,
    }