"""
Doctor database 500-query SpiderSQL execution test.

This file contains 500 fixed, normal natural-language queries for the
ten-table doctor database (database ID 56):

- departments
- doctors
- insurance_policies
- patients
- appointments
- diagnoses
- prescriptions
- lab_tests
- procedures
- billing_claims

The queries follow only the finalized relationships between those tables.

Organization:
- 10 SQL/query categories
- 50 queries per category
- 15 easy, 20 moderate, and 15 hard queries per category

The file contains no expected/reference SQL. At runtime it sends each
natural-language query to SpiderSQL, prints PASS or FAIL, and writes the
generated SQL and query details to one TXT file.

Example:
    python doctor_db56_500_test_run.py

Optional:
    python doctor_db56_500_test_run.py --database-id 56 \
        --base-url http://127.0.0.1:8000 \
        --output doctor_db56_500_query_sql_results.txt \
        --timeout 180
"""

from __future__ import annotations

import argparse
import json
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any


TEST_CASES = [{'id': 1, 'category': 'aggregation', 'difficulty': 'easy', 'query': 'How many departments are currently open?'},
 {'id': 2,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the total annual budget across all departments?'},
 {'id': 3, 'category': 'aggregation', 'difficulty': 'easy', 'query': 'What is the average department quality rating?'},
 {'id': 4, 'category': 'aggregation', 'difficulty': 'easy', 'query': 'How many doctors are currently active?'},
 {'id': 5, 'category': 'aggregation', 'difficulty': 'easy', 'query': 'What is the average salary of all doctors?'},
 {'id': 6,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the highest number of years of experience among doctors?'},
 {'id': 7,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'How many insurance policies are currently active?'},
 {'id': 8,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the average deductible amount across insurance policies?'},
 {'id': 9, 'category': 'aggregation', 'difficulty': 'easy', 'query': 'How many patients have a chronic condition?'},
 {'id': 10, 'category': 'aggregation', 'difficulty': 'easy', 'query': 'What is the average patient weight?'},
 {'id': 11, 'category': 'aggregation', 'difficulty': 'easy', 'query': 'How many appointments have been completed?'},
 {'id': 12,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the average wait time for appointments?'},
 {'id': 13, 'category': 'aggregation', 'difficulty': 'easy', 'query': 'How many diagnoses are currently active?'},
 {'id': 14,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the average estimated cost of prescriptions?'},
 {'id': 15,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the total billed amount across all billing claims?'},
 {'id': 16,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'How many active doctors are accepting new patients?'},
 {'id': 17,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average salary of board-certified doctors?'},
 {'id': 18,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the total bed capacity of accredited departments?'},
 {'id': 19,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average occupancy of departments that offer emergency services?'},
 {'id': 20,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'How many active insurance policies include prescription coverage?'},
 {'id': 21,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average out-of-pocket maximum for PPO plans?'},
 {'id': 22,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'How many patients prefer a language other than English?'},
 {'id': 23,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average weight of patients who currently smoke?'},
 {'id': 24,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'How many appointments were completed in 2025?'},
 {'id': 25,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average wait time for urgent appointments?'},
 {'id': 26,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'How many telehealth appointments required an interpreter?'},
 {'id': 27,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average follow-up interval for confirmed diagnoses?'},
 {'id': 28,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'How many active prescriptions require prior authorization?'},
 {'id': 29,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the total estimated cost of controlled-substance prescriptions?'},
 {'id': 30,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'How many completed lab tests had an abnormal result?'},
 {'id': 31,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average result value for critical lab tests?'},
 {'id': 32,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'How many completed procedures required general anesthesia?'},
 {'id': 33,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average recovery time after successful procedures?'},
 {'id': 34,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the total patient responsibility on paid claims?'},
 {'id': 35,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average number of days to payment for approved claims?'},
 {'id': 36,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'How many active patients have a primary doctor who is accepting new patients?'},
 {'id': 37,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the average salary of doctors working in accredited departments with emergency services?'},
 {'id': 38,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the total billed amount for completed appointments in 2025?'},
 {'id': 39,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the average patient responsibility for claims tied to urgent appointments?'},
 {'id': 40,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'How many patients with chronic conditions received a confirmed diagnosis?'},
 {'id': 41,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the total estimated prescription cost for patients covered by active PPO policies?'},
 {'id': 42,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'How many appointments for patients with high deductibles were completed?'},
 {'id': 43,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the average wait time for appointments handled by board-certified doctors?'},
 {'id': 44,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the total allowed amount for claims submitted for procedures requiring anesthesia?'},
 {'id': 45,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'How many abnormal lab tests belong to patients with chronic conditions?'},
 {'id': 46,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the average procedure cost in departments with a quality rating above 4?'},
 {'id': 47,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'How many patients received both a diagnosis and a prescription during the same appointment?'},
 {'id': 48,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the total insurance-paid amount for claims associated with completed appointments?'},
 {'id': 49,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the average number of days to payment for claims on active insurance policies?'},
 {'id': 50,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'How many active doctors performed procedures with no complications?'},
 {'id': 51,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each department with the number of unused beds based on bed capacity minus current occupancy.'},
 {'id': 52,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each department with annual budget per doctor.'},
 {'id': 53,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each department with current occupancy as a percentage of bed capacity.'},
 {'id': 54,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each doctor with salary per year of experience.'},
 {'id': 55,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each doctor with the number of years remaining until license expiration.'},
 {'id': 56,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each insurance policy with remaining out-of-pocket exposure after subtracting the deductible.'},
 {'id': 57,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each insurance policy with specialist copay minus primary-care copay.'},
 {'id': 58,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each patient with body mass index using weight and height.'},
 {'id': 59,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each appointment with the difference between planned duration and actual time between check-in and '
           'check-out.'},
 {'id': 60,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each appointment with copay per minute of appointment duration.'},
 {'id': 61,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each diagnosis with the number of days between onset and diagnosis.'},
 {'id': 62,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each prescription with estimated cost per prescribed unit.'},
 {'id': 63,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each lab test with the position of its result within the reference range.'},
 {'id': 64,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each procedure with estimated cost per minute of procedure time.'},
 {'id': 65,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each billing claim with the unpaid amount after insurance payment.'},
 {'id': 66,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the bed occupancy percentage for each department.'},
 {'id': 67,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average salary per year of experience for each medical specialty.'},
 {'id': 68,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the percentage of active doctors for each department.'},
 {'id': 69,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the percentage of doctors accepting new patients for each specialty.'},
 {'id': 70,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average deductible as a percentage of the out-of-pocket maximum for each plan type.'},
 {'id': 71,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the percentage of policies with prescription coverage for each provider.'},
 {'id': 72,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the percentage of patients with chronic conditions for each primary doctor.'},
 {'id': 73,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average body mass index for each patient gender.'},
 {'id': 74,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the completed-appointment rate for each appointment type.'},
 {'id': 75,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average wait time per appointment minute for each priority level.'},
 {'id': 76,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the percentage of confirmed diagnoses for each diagnosis category.'},
 {'id': 77,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average follow-up interval for each diagnosis severity.'},
 {'id': 78,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average prescription cost per unit for each drug class.'},
 {'id': 79,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the percentage of active prescriptions for each medication form.'},
 {'id': 80,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the abnormal-result rate for each lab-test category.'},
 {'id': 81,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the critical-result rate for each laboratory.'},
 {'id': 82,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the complication rate for each procedure category.'},
 {'id': 83,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average procedure cost per recovery minute for each anesthesia type.'},
 {'id': 84,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the insurance payment rate for each claim status using insurance-paid amount divided by billed '
           'amount.'},
 {'id': 85,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average patient-responsibility percentage for each insurance provider.'},
 {'id': 86,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each department, calculate total doctor payroll as a percentage of the department annual budget.'},
 {'id': 87,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each doctor, calculate completed appointments per year of experience.'},
 {'id': 88,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each doctor, calculate confirmed diagnoses per completed appointment.'},
 {'id': 89,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each patient, calculate total billed amount per completed appointment.'},
 {'id': 90,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each patient, calculate insurance-paid amount as a percentage of total billed amount.'},
 {'id': 91,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each insurance provider, calculate total insurance payments per active policy.'},
 {'id': 92,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each appointment type, calculate prescription cost per completed appointment.'},
 {'id': 93,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each diagnosis category, calculate total treatment cost using prescription and procedure costs.'},
 {'id': 94,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each doctor specialty, calculate average patient wait time per completed appointment.'},
 {'id': 95,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each department, calculate successful procedures as a percentage of completed procedures.'},
 {'id': 96,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each patient, calculate abnormal lab tests as a percentage of completed lab tests.'},
 {'id': 97,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each medication class, calculate adverse-reaction rate among prescriptions.'},
 {'id': 98,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each procedure category, calculate complication cost per completed procedure.'},
 {'id': 99,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each insurance plan type, calculate patient responsibility as a percentage of allowed claim amount.'},
 {'id': 100,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each department, calculate claim revenue per occupied bed.'},
 {'id': 101,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different department operating statuses are represented?'},
 {'id': 102,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many distinct specialty categories do departments have?'},
 {'id': 103,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different doctor specialties are represented?'},
 {'id': 104,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many distinct doctor employment types are used?'},
 {'id': 105,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different insurance providers appear?'},
 {'id': 106,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many distinct insurance plan types are available?'},
 {'id': 107,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different patient blood types are represented?'},
 {'id': 108,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many distinct patient languages are recorded?'},
 {'id': 109,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different appointment types occur?'},
 {'id': 110,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many distinct appointment statuses appear?'},
 {'id': 111,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different diagnosis categories are represented?'},
 {'id': 112,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many distinct medication classes are prescribed?'},
 {'id': 113,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different laboratory test categories appear?'},
 {'id': 114,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many distinct procedure categories are recorded?'},
 {'id': 115, 'category': 'distinct_count', 'difficulty': 'easy', 'query': 'How many different claim statuses appear?'},
 {'id': 116,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct doctors completed at least one appointment?'},
 {'id': 117,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct patients had at least one completed appointment?'},
 {'id': 118,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct departments handled urgent appointments?'},
 {'id': 119,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct insurance providers have active policies?'},
 {'id': 120,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct patients received a confirmed diagnosis?'},
 {'id': 121,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct doctors recorded a severe diagnosis?'},
 {'id': 122,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct patients received an active prescription?'},
 {'id': 123,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct doctors prescribed a controlled substance?'},
 {'id': 124,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct patients had an abnormal lab result?'},
 {'id': 125,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct laboratories produced a critical result?'},
 {'id': 126,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct doctors performed a completed procedure?'},
 {'id': 127,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct departments performed procedures requiring general anesthesia?'},
 {'id': 128,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct patients have a paid billing claim?'},
 {'id': 129,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct insurance policies were used on approved claims?'},
 {'id': 130,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct doctors treated patients with chronic conditions?'},
 {'id': 131,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct patients required an interpreter during an appointment?'},
 {'id': 132,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct doctors had a telehealth appointment?'},
 {'id': 133,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct patients had both a diagnosis and a prescription?'},
 {'id': 134,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct appointment types produced a lab test?'},
 {'id': 135,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct procedure types resulted in a complication?'},
 {'id': 136,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct patients had completed appointments in both 2024 and 2025?'},
 {'id': 137,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct doctors both recorded a diagnosis and prescribed medication?'},
 {'id': 138,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct departments had both completed procedures and abnormal lab tests?'},
 {'id': 139,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct patients had both an abnormal lab result and a paid claim?'},
 {'id': 140,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct doctors treated patients covered by more than one insurance provider?'},
 {'id': 141,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct patients received prescriptions from at least three different doctors?'},
 {'id': 142,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct insurance providers paid claims for both procedures and prescriptions?'},
 {'id': 143,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct patients had appointments in more than one department?'},
 {'id': 144,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct doctors both performed procedures and reviewed lab tests?'},
 {'id': 145,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct patients had both severe and mild diagnoses?'},
 {'id': 146,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct departments handled both urgent and routine appointments?'},
 {'id': 147,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct doctors treated both chronic-condition and non-chronic-condition patients?'},
 {'id': 148,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct patients underwent procedures with more than one anesthesia type?'},
 {'id': 149,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct insurance policies were associated with both paid and denied claims?'},
 {'id': 150,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct doctors had patients with both active and resolved diagnoses?'},
 {'id': 151, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count departments by operating status.'},
 {'id': 152,
  'category': 'group_by',
  'difficulty': 'easy',
  'query': 'Show average department quality rating by specialty category.'},
 {'id': 153, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count doctors by specialty.'},
 {'id': 154, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Show average doctor salary by employment type.'},
 {'id': 155, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count insurance policies by plan type.'},
 {'id': 156, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Show average deductible by insurance provider.'},
 {'id': 157, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count patients by blood type.'},
 {'id': 158, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Show average patient weight by gender.'},
 {'id': 159, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count appointments by appointment status.'},
 {'id': 160, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Show average wait time by appointment type.'},
 {'id': 161, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count diagnoses by severity.'},
 {'id': 162, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Show average prescription cost by drug class.'},
 {'id': 163, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count lab tests by test status.'},
 {'id': 164,
  'category': 'group_by',
  'difficulty': 'easy',
  'query': 'Show average procedure cost by procedure category.'},
 {'id': 165, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count billing claims by claim status.'},
 {'id': 166, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Count active doctors by department.'},
 {'id': 167, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Show average doctor salary by department.'},
 {'id': 168, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Count patients by primary doctor.'},
 {'id': 169, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Show patient count by insurance provider.'},
 {'id': 170, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Count completed appointments by doctor.'},
 {'id': 171, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Show average wait time by department.'},
 {'id': 172,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Count appointments by priority level and appointment type.'},
 {'id': 173,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show confirmed diagnosis count by diagnosis category.'},
 {'id': 174, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Show active diagnosis count by doctor.'},
 {'id': 175,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show prescription count by medication and prescription status.'},
 {'id': 176, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Show total prescription cost by doctor.'},
 {'id': 177, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Count abnormal lab tests by laboratory.'},
 {'id': 178, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Show average lab result value by test name.'},
 {'id': 179, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Count completed procedures by department.'},
 {'id': 180, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Show average procedure cost by doctor.'},
 {'id': 181,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show complication count by procedure category.'},
 {'id': 182,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show total billed amount by insurance provider.'},
 {'id': 183,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show total patient responsibility by payment status.'},
 {'id': 184, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Count claims by doctor and claim status.'},
 {'id': 185,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show average days to payment by insurance plan type.'},
 {'id': 186,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show completed appointment count by department and doctor specialty.'},
 {'id': 187,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show average wait time by insurance provider and appointment priority.'},
 {'id': 188,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show confirmed diagnosis count by department and severity.'},
 {'id': 189,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show prescription cost by department and drug class.'},
 {'id': 190,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show abnormal lab-test count by doctor specialty and test category.'},
 {'id': 191,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show completed procedure count by department and anesthesia type.'},
 {'id': 192,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show total billed amount by department and insurance provider.'},
 {'id': 193,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show insurance-paid amount by appointment type and claim status.'},
 {'id': 194,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show patient count, appointment count, and billed amount by primary doctor.'},
 {'id': 195,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show average patient responsibility by diagnosis category and insurance plan type.'},
 {'id': 196,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show completed appointment count by patient language and appointment type.'},
 {'id': 197,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show diagnosis count and prescription cost by patient blood type.'},
 {'id': 198,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show procedure count and average recovery time by doctor and department.'},
 {'id': 199,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show lab-test count and abnormal-result rate by department and laboratory.'},
 {'id': 200,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show claim count, billed amount, and days to payment by provider and payment status.'},
 {'id': 201,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List department statuses represented by more than five departments.'},
 {'id': 202,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List specialty categories with an average department quality rating above 4.'},
 {'id': 203,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List doctor specialties represented by more than five doctors.'},
 {'id': 204,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List employment types with an average doctor salary above 200000 dollars.'},
 {'id': 205,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List insurance plan types with more than five policies.'},
 {'id': 206,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List providers with an average deductible above 2000 dollars.'},
 {'id': 207,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List blood types represented by more than five patients.'},
 {'id': 208, 'category': 'having', 'difficulty': 'easy', 'query': 'List languages spoken by more than five patients.'},
 {'id': 209,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List appointment statuses represented by more than ten appointments.'},
 {'id': 210,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List appointment types with an average wait time above 60 minutes.'},
 {'id': 211,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List diagnosis severities represented by more than ten diagnoses.'},
 {'id': 212,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List drug classes with an average prescription cost above 100 dollars.'},
 {'id': 213,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List laboratories with more than five completed tests.'},
 {'id': 214,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List procedure categories with an average cost above 5000 dollars.'},
 {'id': 215,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List claim statuses with total billed amount above 50000 dollars.'},
 {'id': 216,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List departments with more than three active doctors.'},
 {'id': 217,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List doctors who completed more than two appointments.'},
 {'id': 218,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List doctors with more than two active patients.'},
 {'id': 219,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List insurance providers with more than five active policies.'},
 {'id': 220,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List patients with more than two completed appointments.'},
 {'id': 221,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List doctors who recorded more than two confirmed diagnoses.'},
 {'id': 222,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List patients with more than two prescriptions.'},
 {'id': 223,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List medications prescribed more than five times.'},
 {'id': 224,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List laboratories with more than two abnormal results.'},
 {'id': 225,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List doctors who ordered more than three lab tests.'},
 {'id': 226,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List departments that completed more than two procedures.'},
 {'id': 227,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List doctors who performed more than two procedures.'},
 {'id': 228,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List patients whose total billed amount exceeds 10000 dollars.'},
 {'id': 229,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List providers whose total insurance payments exceed 50000 dollars.'},
 {'id': 230,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List appointment types with more than five follow-up-required visits.'},
 {'id': 231,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List diagnosis categories with an average follow-up interval above 60 days.'},
 {'id': 232,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List drug classes with more than two adverse-reaction prescriptions.'},
 {'id': 233,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List procedure categories with more than two complications.'},
 {'id': 234,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List doctors whose patients have an average wait time above 60 minutes.'},
 {'id': 235,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List departments whose total billed amount exceeds 100000 dollars.'},
 {'id': 236,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List departments whose average doctor salary is above the hospital-wide average doctor salary.'},
 {'id': 237,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List doctors whose completed appointment count is above the average doctor appointment count.'},
 {'id': 238,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List patients whose total billed amount is above the average patient billed amount.'},
 {'id': 239,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List insurance providers whose payment rate is above 70 percent.'},
 {'id': 240,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List doctors whose confirmed diagnosis rate is above 60 percent.'},
 {'id': 241,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List departments whose abnormal lab-result rate is above the hospital average.'},
 {'id': 242,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List patients who received prescriptions from at least three different drug classes.'},
 {'id': 243,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List doctors who treated patients from at least three insurance providers.'},
 {'id': 244,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List departments whose procedure complication rate is below 5 percent.'},
 {'id': 245,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List appointment types whose average wait time is above the overall appointment average.'},
 {'id': 246,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List diagnosis categories whose average treatment cost exceeds the overall diagnosis-category average.'},
 {'id': 247,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List doctors whose procedure revenue is above the average doctor procedure revenue.'},
 {'id': 248,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List insurance plan types whose average patient responsibility is below the overall plan average.'},
 {'id': 249,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List patients with claims from at least three different appointment types.'},
 {'id': 250,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List departments whose insurance-paid amount exceeds their total patient responsibility.'},
 {'id': 251, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each doctor with their department name.'},
 {'id': 252, 'category': 'join', 'difficulty': 'easy', 'query': "Show each patient with their primary doctor's name."},
 {'id': 253, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each patient with their insurance provider.'},
 {'id': 254, 'category': 'join', 'difficulty': 'easy', 'query': "Show each appointment with the patient's name."},
 {'id': 255, 'category': 'join', 'difficulty': 'easy', 'query': "Show each appointment with the doctor's name."},
 {'id': 256, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each appointment with the department name.'},
 {'id': 257, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each diagnosis with the appointment number.'},
 {'id': 258, 'category': 'join', 'difficulty': 'easy', 'query': "Show each diagnosis with the patient's name."},
 {'id': 259, 'category': 'join', 'difficulty': 'easy', 'query': "Show each diagnosis with the doctor's name."},
 {'id': 260, 'category': 'join', 'difficulty': 'easy', 'query': "Show each prescription with the patient's name."},
 {'id': 261, 'category': 'join', 'difficulty': 'easy', 'query': "Show each prescription with the doctor's name."},
 {'id': 262, 'category': 'join', 'difficulty': 'easy', 'query': "Show each lab test with the patient's name."},
 {'id': 263, 'category': 'join', 'difficulty': 'easy', 'query': "Show each procedure with the doctor's name."},
 {'id': 264,
  'category': 'join',
  'difficulty': 'easy',
  'query': "Show each procedure with the assisting doctor's name."},
 {'id': 265, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each billing claim with its insurance provider.'},
 {'id': 266,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List active doctors with their department names and salaries.'},
 {'id': 267,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List patients with their primary doctors and policy plan names.'},
 {'id': 268,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List completed appointments with patient names and doctor names.'},
 {'id': 269,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List urgent appointments with department names and wait times.'},
 {'id': 270,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List confirmed diagnoses with patient names and severity.'},
 {'id': 271,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List active prescriptions with patient names and medication costs.'},
 {'id': 272,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List abnormal lab tests with patient names and laboratory names.'},
 {'id': 273,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List completed procedures with patient names and procedure costs.'},
 {'id': 274,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List paid claims with patient names and insurance-paid amounts.'},
 {'id': 275,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List patients covered by PPO plans with provider names.'},
 {'id': 276,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List doctors accepting new patients with department quality ratings.'},
 {'id': 277,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List appointments requiring interpreters with patient languages.'},
 {'id': 278,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List severe diagnoses with doctor names and treatment plans.'},
 {'id': 279,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List controlled-substance prescriptions with prescribing doctor names.'},
 {'id': 280,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List critical lab tests with reviewing doctor names.'},
 {'id': 281,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List procedures with complications and the performing doctor.'},
 {'id': 282,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List denied claims with patient names and denial reasons.'},
 {'id': 283, 'category': 'join', 'difficulty': 'moderate', 'query': 'List patients whose primary doctor is on call.'},
 {'id': 284,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List appointments handled by board-certified doctors.'},
 {'id': 285,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List billing claims associated with active insurance policies.'},
 {'id': 286,
  'category': 'join',
  'difficulty': 'hard',
  'query': "List appointments where the appointment department differs from the doctor's department."},
 {'id': 287,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List diagnoses where the diagnosis doctor differs from the appointment doctor.'},
 {'id': 288,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List prescriptions where the prescribing doctor differs from the appointment doctor.'},
 {'id': 289,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List lab tests where the ordering doctor differs from the appointment doctor.'},
 {'id': 290,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List procedures where the performing doctor differs from the appointment doctor.'},
 {'id': 291,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List billing claims where the claim doctor differs from the appointment doctor.'},
 {'id': 292,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List patients whose primary doctor works in a different department from their most recent appointment.'},
 {'id': 293,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List procedures where the assisting doctor belongs to a different department from the performing doctor.'},
 {'id': 294,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List patients whose policy was inactive on the service date of a claim.'},
 {'id': 295,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List completed appointments that have no completed procedure.'},
 {'id': 296,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List diagnoses whose patient does not match the patient on the appointment.'},
 {'id': 297,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List prescriptions whose patient does not match the patient on the appointment.'},
 {'id': 298,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List lab tests whose patient does not match the patient on the appointment.'},
 {'id': 299,
  'category': 'join',
  'difficulty': 'hard',
  'query': "List claims whose policy does not match the patient's recorded policy."},
 {'id': 300,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List procedures whose department differs from the appointment department.'},
 {'id': 301,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each appointment with patient name, doctor name, and department name.'},
 {'id': 302,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each patient with primary doctor, department, and insurance provider.'},
 {'id': 303,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each diagnosis with patient name, doctor name, and appointment number.'},
 {'id': 304,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each prescription with patient name, doctor name, and appointment number.'},
 {'id': 305,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each lab test with patient name, doctor name, and appointment number.'},
 {'id': 306,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each procedure with patient name, performing doctor, and department.'},
 {'id': 307,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each billing claim with patient name, doctor name, and provider.'},
 {'id': 308,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each completed appointment with patient name and policy plan.'},
 {'id': 309,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each patient with primary doctor specialty and department name.'},
 {'id': 310,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each procedure with performing doctor and assisting doctor.'},
 {'id': 311,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each prescription with patient policy and insurance provider.'},
 {'id': 312,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each lab test with patient blood type and doctor specialty.'},
 {'id': 313,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each diagnosis with department name and patient language.'},
 {'id': 314,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each claim with appointment type and patient name.'},
 {'id': 315,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each appointment with patient policy plan and insurance provider.'},
 {'id': 316,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List completed appointments with patient, doctor, department, and insurance provider.'},
 {'id': 317,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List chronic-condition patients with confirmed diagnoses and their primary doctors.'},
 {'id': 318,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List active prescriptions for patients covered by PPO policies, with doctor and provider.'},
 {'id': 319,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List abnormal lab tests with patient, ordering doctor, and appointment type.'},
 {'id': 320,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List completed procedures with patient, doctor, department, and anesthesia type.'},
 {'id': 321,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List paid claims with patient, doctor, provider, and appointment status.'},
 {'id': 322,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List urgent appointments for chronic-condition patients with primary-doctor details.'},
 {'id': 323,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List severe diagnoses that resulted in active prescriptions, with patient and doctor.'},
 {'id': 324,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List procedures with complications and the related claim amount.'},
 {'id': 325,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List patients with completed appointments and denied claims, including provider.'},
 {'id': 326,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List board-certified doctors who treated patients covered by active insurance policies.'},
 {'id': 327,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List interpreter-required appointments with patient language and doctor specialty.'},
 {'id': 328,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List critical lab results from completed appointments, with patient and department.'},
 {'id': 329,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List prescriptions requiring authorization with patient policy and provider.'},
 {'id': 330,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List procedures requiring general anesthesia with performing and assisting doctors.'},
 {'id': 331,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List patients who had diagnoses and lab tests during the same appointment.'},
 {'id': 332,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List appointments that produced both prescriptions and billing claims.'},
 {'id': 333,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List doctors who recorded diagnoses and performed procedures for the same patient.'},
 {'id': 334,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List departments with completed appointments, procedures, and billing claims.'},
 {'id': 335,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List insurance providers with patients, appointments, and paid claims.'},
 {'id': 336,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List patients who had a confirmed diagnosis, an active prescription, and an abnormal lab result during the '
           'same appointment.'},
 {'id': 337,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List doctors who treated chronic-condition patients and produced both procedures and paid claims.'},
 {'id': 338,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List departments where completed appointments led to procedures with no complications and fully paid '
           'claims.'},
 {'id': 339,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List patients with urgent appointments whose claims were denied despite active insurance coverage.'},
 {'id': 340,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List doctors whose patients had both severe diagnoses and critical lab results.'},
 {'id': 341,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List insurance providers that covered procedures performed by doctors outside the appointment department.'},
 {'id': 342,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List patients who received prescriptions and procedures from different doctors during the same '
           'appointment.'},
 {'id': 343,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List appointments where diagnosis, prescription, lab-test, and procedure doctors are not all the same.'},
 {'id': 344,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List patients whose primary doctor did not participate in any of their completed appointments.'},
 {'id': 345,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List doctors who both prescribed medication and performed a procedure for the same appointment.'},
 {'id': 346,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List departments with abnormal lab tests, procedure complications, and denied claims.'},
 {'id': 347,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List patients whose total procedure cost exceeded insurance payment on related claims.'},
 {'id': 348,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List providers whose covered patients had both telehealth and in-person completed appointments.'},
 {'id': 349,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List doctors who treated patients with active policies from at least three providers and generated paid '
           'claims.'},
 {'id': 350,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List appointments that generated a confirmed diagnosis, active prescription, completed lab test, completed '
           'procedure, and paid claim.'},
 {'id': 351,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 5 departments with the largest annual budgets.'},
 {'id': 352,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 5 departments with the highest bed occupancy.'},
 {'id': 353,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 doctors with the highest salaries.'},
 {'id': 354,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 doctors with the most years of experience.'},
 {'id': 355,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 insurance policies with the highest deductibles.'},
 {'id': 356,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 policies with the largest out-of-pocket maximums.'},
 {'id': 357,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 patients with the highest body weight.'},
 {'id': 358,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 appointments with the longest wait times.'},
 {'id': 359,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 appointments with the highest copays.'},
 {'id': 360,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 diagnoses with the longest follow-up intervals.'},
 {'id': 361,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 prescriptions with the highest estimated costs.'},
 {'id': 362,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 lab tests with the highest result values.'},
 {'id': 363,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 procedures with the highest estimated costs.'},
 {'id': 364,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 billing claims with the largest billed amounts.'},
 {'id': 365,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 claims with the longest time to payment.'},
 {'id': 366,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 departments by number of active doctors.'},
 {'id': 367,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 doctors by number of completed appointments.'},
 {'id': 368,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 primary doctors by number of patients.'},
 {'id': 369,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 5 insurance providers by number of active policies.'},
 {'id': 370,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 patients by number of completed appointments.'},
 {'id': 371,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 doctors by number of confirmed diagnoses.'},
 {'id': 372,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 patients by total prescription cost.'},
 {'id': 373,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 medications by number of prescriptions.'},
 {'id': 374,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 laboratories by number of abnormal results.'},
 {'id': 375,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 doctors by number of lab tests ordered.'},
 {'id': 376,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 departments by completed procedure count.'},
 {'id': 377,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 doctors by total procedure cost.'},
 {'id': 378,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 patients by total billed amount.'},
 {'id': 379,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 5 providers by total insurance payments.'},
 {'id': 380,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 appointment types by average wait time.'},
 {'id': 381,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 diagnosis categories by average follow-up interval.'},
 {'id': 382,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 drug classes by total prescription cost.'},
 {'id': 383,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 procedure categories by complication count.'},
 {'id': 384,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 doctors by total billed claim amount.'},
 {'id': 385,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 5 departments by total insurance-paid amount.'},
 {'id': 386,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 doctors by completed appointments within each department.'},
 {'id': 387,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the highest-paid doctor in each specialty.'},
 {'id': 388,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 patients by total billed amount within each insurance provider.'},
 {'id': 389,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 departments by average patient wait time among departments with at least five completed '
           'appointments.'},
 {'id': 390,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 doctors by confirmed diagnosis rate within each specialty.'},
 {'id': 391,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 5 patients by prescription cost among patients with at least three prescriptions.'},
 {'id': 392,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 laboratories by abnormal-result rate among laboratories with at least five completed '
           'tests.'},
 {'id': 393,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 doctors by procedure revenue within each department.'},
 {'id': 394,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 providers by insurance payment rate among providers with at least five claims.'},
 {'id': 395,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 5 patients by abnormal lab-test count within each blood type.'},
 {'id': 396,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 departments by successful-procedure rate.'},
 {'id': 397,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 5 doctors by average patient-responsibility amount.'},
 {'id': 398,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 appointment types by paid-claim amount.'},
 {'id': 399,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 diagnosis categories by combined prescription and procedure cost.'},
 {'id': 400,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 5 insurance plans by lowest average days to payment among plans with at least five claims.'},
 {'id': 401,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List doctor identifiers that appear either as primary doctors or appointment doctors.'},
 {'id': 402,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List doctor identifiers that appear either in diagnoses or prescriptions.'},
 {'id': 403,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List patient identifiers that appear either in appointments or billing claims.'},
 {'id': 404,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List appointment identifiers that appear either in diagnoses or lab tests.'},
 {'id': 405,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List appointment identifiers that appear either in prescriptions or procedures.'},
 {'id': 406,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List policy identifiers that appear either in patient records or billing claims.'},
 {'id': 407,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List department identifiers that appear either in doctors or appointments.'},
 {'id': 408,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List patients who either have a chronic condition or currently smoke.'},
 {'id': 409,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List doctors who are either board certified or accepting new patients.'},
 {'id': 410,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List policies that include either dental or vision coverage.'},
 {'id': 411,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List appointments that are either urgent or emergency priority.'},
 {'id': 412,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List diagnoses that are either severe or moderate.'},
 {'id': 413,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List prescriptions that are either active or completed.'},
 {'id': 414,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List lab tests that are either abnormal or critical.'},
 {'id': 415,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List claims that are either paid or approved.'},
 {'id': 416,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List patients who have both a completed appointment and a confirmed diagnosis.'},
 {'id': 417,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List doctors who both recorded a diagnosis and prescribed medication.'},
 {'id': 418,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List appointments that have both a lab test and a procedure.'},
 {'id': 419,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List patients who have both a prescription and a billing claim.'},
 {'id': 420,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List departments that have both active doctors and completed procedures.'},
 {'id': 421,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List patients with completed appointments but no billing claims.'},
 {'id': 422,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List appointments with diagnoses but no prescriptions.'},
 {'id': 423,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List patients with prescriptions but no completed procedures.'},
 {'id': 424,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List doctors who ordered lab tests but performed no procedures.'},
 {'id': 425,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List policies used by patients but never used on a billing claim.'},
 {'id': 426,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List departments with completed appointments but no completed procedures.'},
 {'id': 427,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List patients with abnormal lab tests but no confirmed diagnosis.'},
 {'id': 428,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List doctors with completed appointments but no recorded diagnoses.'},
 {'id': 429,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List providers with active policies but no paid claims.'},
 {'id': 430,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List appointments with procedures but no billing claim.'},
 {'id': 431,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List patients with paid claims but no active prescription.'},
 {'id': 432,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List doctors who prescribed medication but never reviewed a lab test.'},
 {'id': 433,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List appointment types associated with both diagnoses and prescriptions.'},
 {'id': 434,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List patients who had both telehealth and non-telehealth appointments.'},
 {'id': 435,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List departments that handled both urgent and routine appointments.'},
 {'id': 436,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List patients who had both confirmed diagnoses and active prescriptions but no completed procedure.'},
 {'id': 437,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List doctors who both prescribed medication and performed procedures but never reviewed a lab test.'},
 {'id': 438,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List departments with both abnormal lab tests and completed procedures but no denied claims.'},
 {'id': 439,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List insurance providers with both paid and approved claims but no denied claims.'},
 {'id': 440,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List patients who had both urgent and routine appointments but no telehealth appointment.'},
 {'id': 441,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List doctors who treated both chronic-condition and non-chronic-condition patients but no smoking '
           'patients.'},
 {'id': 442,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List appointments that produced both diagnoses and lab tests but no prescriptions.'},
 {'id': 443,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List patients with claims from both PPO and HMO plans but no EPO plan.'},
 {'id': 444,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List departments with both general-anesthesia and local-anesthesia procedures but no complications.'},
 {'id': 445,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List doctors who recorded both severe and mild diagnoses but no moderate diagnoses.'},
 {'id': 446,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List patients who received both controlled and non-controlled prescriptions but no adverse reaction.'},
 {'id': 447,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List laboratories that produced both high and low abnormal results but no critical results.'},
 {'id': 448,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List procedure categories performed in both emergency and routine appointments but not urgent '
           'appointments.'},
 {'id': 449,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List providers that paid claims for both procedures and diagnoses but no denied claims.'},
 {'id': 450,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List patients who had appointments in both medical and surgical departments but no diagnostic department.'},
 {'id': 451,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List departments with annual budgets above the average department budget.'},
 {'id': 452,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List departments with quality ratings above the average department quality rating.'},
 {'id': 453,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List doctors earning more than the average doctor salary.'},
 {'id': 454,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List doctors with more experience than the average doctor.'},
 {'id': 455,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List policies with deductibles above the average policy deductible.'},
 {'id': 456,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List patients whose weight is above the average patient weight.'},
 {'id': 457,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List appointments with wait times above the average appointment wait time.'},
 {'id': 458,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List diagnoses with follow-up intervals above the average diagnosis follow-up interval.'},
 {'id': 459,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List prescriptions costing more than the average prescription cost.'},
 {'id': 460,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List lab tests with result values above the average result value.'},
 {'id': 461,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List procedures costing more than the average procedure cost.'},
 {'id': 462,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List claims with billed amounts above the average claim amount.'},
 {'id': 463,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List patients who have never had an appointment.'},
 {'id': 464,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List doctors who have never completed an appointment.'},
 {'id': 465,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List insurance policies that have never appeared on a billing claim.'},
 {'id': 466,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List doctors earning more than the average salary in their department.'},
 {'id': 467,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List departments with active doctor counts above the average department active-doctor count.'},
 {'id': 468,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List patients with more completed appointments than the average patient with an appointment.'},
 {'id': 469,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List doctors with more confirmed diagnoses than the average diagnosing doctor.'},
 {'id': 470,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List providers with more active policies than the average provider.'},
 {'id': 471,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List patients whose total prescription cost is above the average patient prescription cost.'},
 {'id': 472,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List laboratories whose abnormal-result count is above the average laboratory count.'},
 {'id': 473,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List doctors whose completed procedure count is above the average performing doctor.'},
 {'id': 474,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List patients whose combined claim charges exceed the average combined claim charges per patient.'},
 {'id': 475,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List providers whose total insurance payment is above the average provider payment.'},
 {'id': 476,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List appointments with wait times above the average for their appointment type.'},
 {'id': 477,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List diagnoses with follow-up intervals above the average for their diagnosis category.'},
 {'id': 478,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List prescriptions costing more than the average for their drug class.'},
 {'id': 479,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List procedures costing more than the average for their procedure category.'},
 {'id': 480,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List claims taking longer to pay than the average claim for the same provider.'},
 {'id': 481,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List patients whose most recent appointment was completed.'},
 {'id': 482,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List doctors whose latest appointment was urgent.'},
 {'id': 483,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List departments where every active doctor is board certified.'},
 {'id': 484,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List providers where every active policy includes prescription coverage.'},
 {'id': 485,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List patients for whom every completed appointment produced a billing claim.'},
 {'id': 486,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List the highest-paid doctor in each department.'},
 {'id': 487,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List the patient with the largest billed amount for each insurance provider.'},
 {'id': 488,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List the most expensive procedure in each procedure category.'},
 {'id': 489,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List doctors whose completed-appointment count is above the average for their specialty.'},
 {'id': 490,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List patients whose billed amount is above the average for patients with the same primary doctor.'},
 {'id': 491,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List departments whose procedure revenue is above the average for departments in the same specialty '
           'category.'},
 {'id': 492,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List providers whose insurance payment rate is above the average provider payment rate.'},
 {'id': 493,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List doctors whose confirmed-diagnosis rate is above the average rate in their department.'},
 {'id': 494,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List patients who received every drug class prescribed during any of their appointments.'},
 {'id': 495,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List doctors for whom every completed appointment has at least one diagnosis.'},
 {'id': 496,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List departments where every completed procedure had signed consent.'},
 {'id': 497,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List providers where every paid claim was paid within 90 days.'},
 {'id': 498,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List patients whose three most recent appointments had decreasing wait times.'},
 {'id': 499,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List doctors whose 2025 completed appointment count exceeded their 2024 count.'},
 {'id': 500,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List departments whose abnormal-lab rate is above the overall department average and whose complication '
           'rate is below the overall department average.'}]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run 500 fixed doctor-database natural-language queries against SpiderSQL."
    )
    parser.add_argument(
        "--database-id",
        type=int,
        default=56,
        help="SpiderSQL database ID. Defaults to the uploaded doctor database ID 56.",
    )
    parser.add_argument(
        "--base-url",
        default="http://127.0.0.1:8000",
        help="SpiderSQL backend base URL.",
    )
    parser.add_argument(
        "--output",
        default="doctor_db56_500_query_sql_results.txt",
        help="Single TXT output file containing each query and its generated SQL.",
    )
    parser.add_argument(
        "--timeout",
        type=int,
        default=180,
        help="Per-query HTTP timeout in seconds.",
    )
    parser.add_argument(
        "--start-index",
        type=int,
        default=1,
        help="Start at this 1-based test number. Useful after an interrupted run.",
    )
    parser.add_argument(
        "--end-index",
        type=int,
        default=len(TEST_CASES),
        help="Stop at this 1-based test number.",
    )
    return parser.parse_args()


def _trace_headers(trace_meta: dict[str, str] | None) -> dict[str, str]:
    """Emit the optional X-SpiderSQL-* diagnostic headers so full-trace runs
    capture per-test metadata (test id / category / difficulty / trace run).
    No-op ({}) when trace_meta is None. Only sent when values are present."""
    if not trace_meta:
        return {}
    name = {"test_id": "X-SpiderSQL-Test-ID", "category": "X-SpiderSQL-Category",
            "difficulty": "X-SpiderSQL-Difficulty", "trace_run": "X-SpiderSQL-Trace-Run"}
    return {name[k]: str(v) for k, v in trace_meta.items() if k in name and v}


def post_query(base_url: str, database_id: int, question: str, timeout: int, trace_meta: dict[str, str] | None = None) -> tuple[int, dict[str, Any]]:
    url = f"{base_url.rstrip('/')}/database/{database_id}/execute_sql"
    request_body = json.dumps({"question": question}).encode("utf-8")
    request = urllib.request.Request(
        url,
        data=request_body,
        headers={"Content-Type": "application/json", "Accept": "application/json",
                 **_trace_headers(trace_meta)},
        method="POST",
    )

    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            status_code = response.getcode()
            raw = response.read().decode("utf-8", errors="replace")
    except urllib.error.HTTPError as exc:
        status_code = exc.code
        raw = exc.read().decode("utf-8", errors="replace")
    except Exception as exc:
        return 0, {"success": False, "_client_error": str(exc)}

    try:
        payload = json.loads(raw) if raw.strip() else {}
    except json.JSONDecodeError:
        payload = {"success": False, "_raw_response": raw}

    if not isinstance(payload, dict):
        payload = {"success": False, "_raw_response": payload}

    return status_code, payload


def extract_sql(payload: dict[str, Any]) -> str:
    generated = payload.get("generated_sql")

    if isinstance(generated, dict):
        for key in ("sql", "query", "generated_sql"):
            value = generated.get(key)
            if isinstance(value, str) and value.strip():
                return value.strip()

    if isinstance(generated, str) and generated.strip():
        return generated.strip()

    for key in ("sql", "query_sql", "final_sql"):
        value = payload.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()

    execution = payload.get("execution")
    if isinstance(execution, dict):
        for key in ("sql", "executed_sql"):
            value = execution.get(key)
            if isinstance(value, str) and value.strip():
                return value.strip()

    return ""


def execution_succeeded(http_status: int, payload: dict[str, Any]) -> bool:
    if http_status < 200 or http_status >= 300:
        return False

    top_level = payload.get("success")
    execution = payload.get("execution")

    if top_level is False:
        return False

    if isinstance(execution, dict) and execution.get("success") is False:
        return False

    if top_level is True:
        return True

    if isinstance(execution, dict) and execution.get("success") is True:
        return True

    return False


def format_record(case: dict[str, Any], status: str, sql: str) -> str:
    displayed_sql = sql if sql else "<NO SQL GENERATED>"
    separator = "=" * 100
    return (
        f"{separator}\n"
        f"TEST {case['id']:03d}\n"
        f"CATEGORY: {case['category']}\n"
        f"DIFFICULTY: {case['difficulty']}\n"
        f"STATUS: {status}\n"
        f"QUERY:\n{case['query']}\n"
        f"SQL:\n{displayed_sql}\n"
    )


def main() -> int:
    args = parse_args()

    if args.start_index < 1 or args.end_index > len(TEST_CASES) or args.start_index > args.end_index:
        print(
            f"Invalid range. Use 1 <= start-index <= end-index <= {len(TEST_CASES)}.",
            file=sys.stderr,
        )
        return 2

    selected_cases = [
        case for case in TEST_CASES
        if args.start_index <= case["id"] <= args.end_index
    ]

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    file_mode = "w" if args.start_index == 1 else "a"

    pass_count = 0
    fail_count = 0
    run_started = time.time()

    with output_path.open(file_mode, encoding="utf-8") as output:
        for position, case in enumerate(selected_cases, start=1):
            http_status, payload = post_query(
                base_url=args.base_url,
                database_id=args.database_id,
                question=case["query"],
                timeout=args.timeout,
                trace_meta={
                    "test_id": str(case.get("id", position)),
                    "category": case.get("category"),
                    "difficulty": case.get("difficulty"),
                    "trace_run": getattr(args, "trace_run", None),
                },
            )

            sql = extract_sql(payload)
            passed = execution_succeeded(http_status, payload)
            status = "PASS" if passed else "FAIL"

            if passed:
                pass_count += 1
            else:
                fail_count += 1

            print(
                f"[{position:03d}/{len(selected_cases):03d}] "
                f"{status} | TEST {case['id']:03d} | "
                f"{case['category']} | {case['difficulty']}",
                flush=True,
            )

            output.write(format_record(case, status, sql))
            output.flush()

    elapsed = time.time() - run_started
    print("-" * 100)
    print(f"Completed: {len(selected_cases)}")
    print(f"PASS: {pass_count}")
    print(f"FAIL: {fail_count}")
    print(f"Elapsed seconds: {elapsed:.1f}")
    print(f"TXT output: {output_path.resolve()}")

    return 0 if fail_count == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
