"""
Northstar Commerce 500-query SpiderSQL execution test.

This file contains 500 fixed natural-language queries:
- 10 categories
- 50 queries per category
- 15 easy, 20 moderate, and 15 hard queries per category

It does not contain expected/reference SQL.
At runtime it sends each fixed query to SpiderSQL, prints PASS or FAIL,
and writes only the generated SQL and query details to one TXT file.

Example:
    python northstar_500_test_run.py --database-id 51

Optional:
    python northstar_500_test_run.py --database-id 51 \
        --base-url http://127.0.0.1:8000 \
        --output northstar_500_query_sql_results.txt \
        --timeout 180
"""

from __future__ import annotations

import argparse
import json
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any


TEST_CASES = [{'id': 1, 'category': 'aggregation', 'difficulty': 'easy', 'query': 'How many customers are currently active?'},
 {'id': 2,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the total current balance across all customers?'},
 {'id': 3,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the average credit limit for enterprise customers?'},
 {'id': 4, 'category': 'aggregation', 'difficulty': 'easy', 'query': 'How many suppliers have a rating of 1?'},
 {'id': 5,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the average sale price of Electronics products?'},
 {'id': 6,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the highest list price among Apparel products?'},
 {'id': 7,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the lowest standard cost among Office Supplies products?'},
 {'id': 8, 'category': 'aggregation', 'difficulty': 'easy', 'query': 'How many warehouses are currently open?'},
 {'id': 9,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the total quantity available across all inventory records?'},
 {'id': 10,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the average salary of active employees?'},
 {'id': 11, 'category': 'aggregation', 'difficulty': 'easy', 'query': 'How many sales orders have been delivered?'},
 {'id': 12,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the total grand total of all sales orders?'},
 {'id': 13,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the average payment amount for settled payments?'},
 {'id': 14, 'category': 'aggregation', 'difficulty': 'easy', 'query': 'How many shipments used overnight service?'},
 {'id': 15,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the total shipping cost of delivered shipments?'},
 {'id': 16,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the total revenue from delivered orders placed in 2025?'},
 {'id': 17,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average order value for online sales orders?'},
 {'id': 18,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the total amount refunded across all payments?'},
 {'id': 19,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the total inventory value stored in Spokane warehouses?'},
 {'id': 20,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average utilization percentage of temperature-controlled warehouses?'},
 {'id': 21,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the combined annual budget of departments in the Corporate division?'},
 {'id': 22,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average salary of employees in the Information Technology department?'},
 {'id': 23,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the total quantity ordered for products in the Electronics category?'},
 {'id': 24,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the total line revenue for Apparel products?'},
 {'id': 25,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the total amount collected through credit-card payments that settled successfully?'},
 {'id': 26,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average shipping cost for shipments sent by FedEx?'},
 {'id': 27,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'How much revenue came from sales orders marked as high priority?'},
 {'id': 28,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the total quantity damaged for inventory held in Phoenix warehouses?'},
 {'id': 29,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average fraud score for failed payments?'},
 {'id': 30,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the total value of orders placed by Gold loyalty customers?'},
 {'id': 31,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average sale price of products supplied by manufacturers?'},
 {'id': 32,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the total payroll for employees working in Washington state?'},
 {'id': 33,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the total amount of discounts given on delivered sales orders?'},
 {'id': 34,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average package count for freight shipments?'},
 {'id': 35,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the total inventory value of discontinued products?'},
 {'id': 36,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What was the total revenue from delivered online orders placed by Platinum customers in 2025?'},
 {'id': 37,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the average line total for Electronics products shipped from Northwest-region warehouses?'},
 {'id': 38,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the total quantity ordered for products supplied by rating-1 suppliers?'},
 {'id': 39,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the combined net payment amount for enterprise customers whose payments settled in 2026?'},
 {'id': 40,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the total shipping cost for delivered orders sent to residential addresses in Washington?'},
 {'id': 41,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the average order value for customers whose account status is active and whose loyalty tier is '
           'Gold?'},
 {'id': 42,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the total inventory value of low-stock products supplied by high-risk suppliers?'},
 {'id': 43,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the average salary of active full-time employees whose departments have a high compliance level?'},
 {'id': 44,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the total line revenue from products sold on partner-channel orders during 2025?'},
 {'id': 45,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the total refunded amount for orders that were eventually delivered?'},
 {'id': 46,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the average shipment weight for orders containing at least one Outdoors product?'},
 {'id': 47,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the total order revenue handled by sales representatives in the Sales department?'},
 {'id': 48,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the total quantity shipped for products stored in temperature-controlled warehouses?'},
 {'id': 49,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the average delivery time in days for shipments that were delivered and required a signature?'},
 {'id': 50,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the total profit amount from delivered order items, calculated as quantity shipped times unit '
           'price minus unit cost?'},
 {'id': 51,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each product name with the difference between its list price and standard cost.'},
 {'id': 52,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each product name with its discount amount from list price to sale price.'},
 {'id': 53,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each inventory record with the percentage of on-hand quantity that is available.'},
 {'id': 54,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each warehouse with the number of unused capacity units.'},
 {'id': 55,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each employee with the dollar amount of their target bonus.'},
 {'id': 56,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each payment with the difference between the payment amount and net amount.'},
 {'id': 57,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each sales order with its discount as a percentage of subtotal.'},
 {'id': 58,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each sales order with tax as a percentage of subtotal.'},
 {'id': 59,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each order item with its gross profit per unit.'},
 {'id': 60,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each order item with its total gross profit based on quantity ordered.'},
 {'id': 61,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each shipment with shipping cost per kilogram.'},
 {'id': 62,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each department with the difference between budgeted and current headcount.'},
 {'id': 63,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each customer with the percentage of their credit limit currently used.'},
 {'id': 64,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each supplier with payment terms expressed in weeks.'},
 {'id': 65,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each product with its markup percentage from standard cost to list price.'},
 {'id': 66,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average order value for each sales channel.'},
 {'id': 67,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the percentage of sales orders that were delivered for each priority level.'},
 {'id': 68,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the refund rate for each payment method using refunded amount divided by payment amount.'},
 {'id': 69,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average gross margin percentage for each product category.'},
 {'id': 70,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the inventory availability rate for each warehouse.'},
 {'id': 71,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average shipping cost per package for each carrier.'},
 {'id': 72,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average payment processing fee percentage for each payment provider.'},
 {'id': 73,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the employee salary cost per current department headcount for each department.'},
 {'id': 74,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average order discount percentage for each customer segment.'},
 {'id': 75,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the percentage of customers who opted into marketing for each loyalty tier.'},
 {'id': 76,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the percentage of active suppliers for each supplier type.'},
 {'id': 77,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the stock damage rate for each warehouse using damaged quantity divided by on-hand quantity.'},
 {'id': 78,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average revenue per order for each order status.'},
 {'id': 79,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average units ordered per order for each sales channel.'},
 {'id': 80,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average profit per order item for each product category.'},
 {'id': 81,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the percentage of shipments delivered on or before their estimated delivery date for each '
           'carrier.'},
 {'id': 82,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average number of days from order date to ship date for each sales channel.'},
 {'id': 83,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the percentage of fulfilled order items for each warehouse.'},
 {'id': 84,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average refunded percentage for each customer segment.'},
 {'id': 85,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the revenue share of each product category as a percentage of total order-item revenue.'},
 {'id': 86,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each customer, calculate lifetime delivered-order revenue divided by the number of delivered orders.'},
 {'id': 87,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each supplier, calculate total order-item revenue minus total order-item cost for the products it '
           'supplies.'},
 {'id': 88,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each warehouse, calculate inventory value per unit of capacity.'},
 {'id': 89,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': "For each department, calculate total employee salary as a percentage of the department's annual budget."},
 {'id': 90,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each loyalty tier, calculate delivered-order revenue as a percentage of all order revenue for that '
           'tier.'},
 {'id': 91,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each product category, calculate total gross profit divided by total line revenue.'},
 {'id': 92,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each sales representative, calculate delivered-order revenue per customer served.'},
 {'id': 93,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each carrier, calculate average shipping cost per delivered kilogram, excluding shipments with zero '
           'weight.'},
 {'id': 94,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each customer segment, calculate net settled payments as a percentage of gross settled payment '
           'amount.'},
 {'id': 95,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each warehouse region, calculate shipped units divided by available inventory units.'},
 {'id': 96,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each product, calculate total quantity shipped divided by total quantity ordered.'},
 {'id': 97,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each supplier risk level, calculate the percentage of supplied products that are discontinued.'},
 {'id': 98,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each department, calculate average employee performance rating per ten thousand dollars of average '
           'salary.'},
 {'id': 99,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each month of 2025, calculate delivered-order revenue growth compared with the previous month.'},
 {'id': 100,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each product category, calculate its share of total inventory value and its share of total sales '
           'revenue.'},
 {'id': 101,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different customer segments are represented in the customer table?'},
 {'id': 102,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many distinct loyalty tiers do customers have?'},
 {'id': 103,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different cities appear in customer addresses?'},
 {'id': 104,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many distinct job titles are used by employees?'},
 {'id': 105,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different supplier types are there?'},
 {'id': 106,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many distinct product categories are in the catalog?'},
 {'id': 107,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different product brands are available?'},
 {'id': 108,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many distinct warehouse regions are represented?'},
 {'id': 109,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different order statuses occur in sales orders?'},
 {'id': 110, 'category': 'distinct_count', 'difficulty': 'easy', 'query': 'How many distinct sales channels are used?'},
 {'id': 111,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different payment methods appear in payments?'},
 {'id': 112,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many distinct carriers appear in shipments?'},
 {'id': 113,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different shipment service levels are used?'},
 {'id': 114,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many distinct states appear in supplier addresses?'},
 {'id': 115,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different department divisions are represented?'},
 {'id': 116,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct customers placed at least one order in 2025?'},
 {'id': 117,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct products were ordered on delivered sales orders?'},
 {'id': 118,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct suppliers provide Electronics products?'},
 {'id': 119,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct customers have made a settled payment?'},
 {'id': 120,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct warehouses fulfilled order items for Apparel products?'},
 {'id': 121,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct employees handled high-priority sales orders?'},
 {'id': 122,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct products are currently low in stock?'},
 {'id': 123,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct customers used a shipping address in Spokane?'},
 {'id': 124,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct departments have active full-time employees?'},
 {'id': 125,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct carriers delivered shipments to Washington?'},
 {'id': 126,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct customers placed online orders that were delivered?'},
 {'id': 127,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct product categories appear on partner-channel orders?'},
 {'id': 128,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct suppliers have products with a sale price above 500?'},
 {'id': 129,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct warehouses currently store discontinued products?'},
 {'id': 130,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct customers have received a refunded or partially refunded order?'},
 {'id': 131,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct cities contain an open warehouse?'},
 {'id': 132,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct customers ordered products in the Outdoors category?'},
 {'id': 133,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct sales representatives handled orders from enterprise customers?'},
 {'id': 134,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct products had at least one backordered unit?'},
 {'id': 135,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct payment providers processed credit-card payments?'},
 {'id': 136,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct customers placed delivered orders in both 2024 and 2025?'},
 {'id': 137,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct products were sold through both online and store channels?'},
 {'id': 138,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct suppliers provided products sold on delivered orders during 2025?'},
 {'id': 139,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct customers both placed a high-priority order and made a settled payment?'},
 {'id': 140,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct warehouses fulfilled orders for Gold customers in 2025?'},
 {'id': 141,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct employees managed either a warehouse or at least one sales order?'},
 {'id': 142,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct products are both low in stock and supplied by a high-risk supplier?'},
 {'id': 143,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct customers had orders shipped from more than one warehouse?'},
 {'id': 144,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct carriers delivered orders containing Electronics products?'},
 {'id': 145,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct product categories were purchased by Platinum customers through the online channel?'},
 {'id': 146,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct suppliers had products stored in at least three different warehouses?'},
 {'id': 147,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct customers used different addresses for billing and shipping on the same order?'},
 {'id': 148,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct employees handled delivered orders worth more than 1,000 dollars?'},
 {'id': 149,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct products were ordered in 2025 but have no available inventory now?'},
 {'id': 150,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct customer cities generated delivered-order revenue above 10,000 dollars?'},
 {'id': 151, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count customers by account status.'},
 {'id': 152, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count customers by loyalty tier.'},
 {'id': 153, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count addresses by state.'},
 {'id': 154, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count employees by department.'},
 {'id': 155, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count suppliers by rating.'},
 {'id': 156, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count products by category.'},
 {'id': 157, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count warehouses by region.'},
 {'id': 158, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Show total available inventory by warehouse.'},
 {'id': 159, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count sales orders by order status.'},
 {'id': 160, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Show total sales-order revenue by sales channel.'},
 {'id': 161, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count payments by payment method.'},
 {'id': 162, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count shipments by carrier.'},
 {'id': 163, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Show average salary by employment type.'},
 {'id': 164, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Show average product sale price by category.'},
 {'id': 165, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Show total annual budget by division.'},
 {'id': 166,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show delivered-order revenue by customer loyalty tier.'},
 {'id': 167,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show total quantity ordered by product category.'},
 {'id': 168, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Show inventory value by warehouse city.'},
 {'id': 169,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show average supplier rating by supplier type.'},
 {'id': 170,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show the number of active employees by department and employment type.'},
 {'id': 171,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show total refunded amount by payment method.'},
 {'id': 172,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show average shipment cost by carrier and service level.'},
 {'id': 173,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show order count and average order value by priority.'},
 {'id': 174,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show total damaged inventory quantity by warehouse.'},
 {'id': 175,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show customer count by segment and preferred language.'},
 {'id': 176,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show product count and average list price by brand.'},
 {'id': 177,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show total order-item revenue by fulfillment status.'},
 {'id': 178,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show total settled payment amount by payment provider.'},
 {'id': 179,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show delivered shipment count by destination state.'},
 {'id': 180,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show average warehouse utilization by region.'},
 {'id': 181, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Show total customer balance by loyalty tier.'},
 {'id': 182,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show average employee performance rating by department.'},
 {'id': 183, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Show order count by year and sales channel.'},
 {'id': 184,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show total quantity backordered by product category.'},
 {'id': 185,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show average shipping cost by shipment status.'},
 {'id': 186,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show delivered-order revenue by customer segment and product category.'},
 {'id': 187,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show total gross profit by supplier and product category.'},
 {'id': 188,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show shipped quantity by warehouse region and sales channel.'},
 {'id': 189,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show average order value by customer loyalty tier and order year.'},
 {'id': 190,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show settled payment amount by customer segment and payment method.'},
 {'id': 191,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show delivered shipment count and average delivery time by carrier and destination state.'},
 {'id': 192,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show inventory value by supplier risk level and warehouse region.'},
 {'id': 193,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show total quantity ordered by sales representative and product category.'},
 {'id': 194,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show average line discount percentage by customer segment and product brand.'},
 {'id': 195,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show delivered-order revenue by billing state and shipping state.'},
 {'id': 196,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show active employee payroll by department division and remote-work status.'},
 {'id': 197, 'category': 'group_by', 'difficulty': 'hard', 'query': 'Show total order revenue by month for 2025.'},
 {'id': 198,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show product sales revenue by supplier rating and product category.'},
 {'id': 199,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show average fulfillment rate by warehouse and product category.'},
 {'id': 200,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show customer count, order count, and total revenue by customer city.'},
 {'id': 201, 'category': 'having', 'difficulty': 'easy', 'query': 'List loyalty tiers with more than 50 customers.'},
 {'id': 202, 'category': 'having', 'difficulty': 'easy', 'query': 'List states with more than 20 customer addresses.'},
 {'id': 203, 'category': 'having', 'difficulty': 'easy', 'query': 'List departments with more than 8 employees.'},
 {'id': 204,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List supplier ratings shared by more than 10 suppliers.'},
 {'id': 205,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List product categories containing more than 50 products.'},
 {'id': 206,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List warehouse regions containing more than one warehouse.'},
 {'id': 207,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List order statuses with more than 25 sales orders.'},
 {'id': 208,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List payment methods used for more than 50 payments.'},
 {'id': 209,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List carriers that handled more than 100 shipments.'},
 {'id': 210,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List employment types with an average salary above 70,000 dollars.'},
 {'id': 211,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List product categories with an average sale price above 200 dollars.'},
 {'id': 212,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List divisions with a total annual budget above 3 million dollars.'},
 {'id': 213,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List warehouses with more than 10,000 available units.'},
 {'id': 214,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List customer segments with a total current balance above 100,000 dollars.'},
 {'id': 215,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List shipment service levels with an average shipping cost above 20 dollars.'},
 {'id': 216,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List customers whose total sales-order value exceeds 5,000 dollars.'},
 {'id': 217,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List products with more than 20 total units ordered.'},
 {'id': 218,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List suppliers whose products have generated more than 10,000 dollars in line revenue.'},
 {'id': 219,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List warehouses holding inventory worth more than 500,000 dollars.'},
 {'id': 220,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List employees who have handled more than 10 sales orders.'},
 {'id': 221,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List departments whose active employee payroll exceeds 500,000 dollars.'},
 {'id': 222,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List customer cities with more than 10 delivered orders.'},
 {'id': 223,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List product brands with an average sale price above 300 dollars.'},
 {'id': 224,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List carriers with more than 50 delivered shipments.'},
 {'id': 225,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List payment providers that settled more than 50,000 dollars.'},
 {'id': 226,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List customers who have placed at least 3 delivered orders.'},
 {'id': 227,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List product categories with more than 100 backordered units.'},
 {'id': 228,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List supplier types with an average rating above 3.'},
 {'id': 229,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List warehouse cities with total damaged quantity above 100 units.'},
 {'id': 230,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List loyalty tiers whose delivered-order revenue exceeds 50,000 dollars.'},
 {'id': 231,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List sales channels with an average order value above 1,000 dollars.'},
 {'id': 232,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List employees whose average handled order value exceeds 1,500 dollars.'},
 {'id': 233,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List products stored in more than 3 warehouses.'},
 {'id': 234,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List destination states with more than 30 delivered shipments.'},
 {'id': 235,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List customers whose total refunded amount exceeds 100 dollars.'},
 {'id': 236,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List suppliers whose products generated more than 20,000 dollars in delivered-order revenue during 2025.'},
 {'id': 237,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List customers whose delivered-order total is greater than their credit limit.'},
 {'id': 238,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List warehouses whose shipped quantity exceeds their current available inventory quantity.'},
 {'id': 239,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List departments whose average employee salary is above the company-wide average salary.'},
 {'id': 240,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List product categories whose gross margin percentage is above 40 percent.'},
 {'id': 241,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List sales representatives who handled more than 20 delivered orders and more than 25,000 dollars in '
           'revenue.'},
 {'id': 242,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List customer segments whose refund rate is above 5 percent.'},
 {'id': 243,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List carriers whose on-time delivery rate is below 90 percent.'},
 {'id': 244,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List products whose total ordered quantity is more than twice their current available inventory.'},
 {'id': 245,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List suppliers whose average product sale price is above the overall average product sale price.'},
 {'id': 246,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List customers who ordered from at least 3 different product categories.'},
 {'id': 247,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List warehouses that fulfilled orders for more than 25 distinct customers.'},
 {'id': 248,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List product categories sold through all four sales channels.'},
 {'id': 249,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List departments whose current headcount exceeds their headcount budget.'},
 {'id': 250,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List customer cities whose delivered-order revenue exceeds the average delivered revenue across all '
           'customer cities.'},
 {'id': 251,
  'category': 'join',
  'difficulty': 'easy',
  'query': 'Show each customer name with their address city and state.'},
 {'id': 252, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each employee name with their department name.'},
 {'id': 253, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each product name with its supplier name.'},
 {'id': 254, 'category': 'join', 'difficulty': 'easy', 'query': "Show each warehouse name with its manager's name."},
 {'id': 255,
  'category': 'join',
  'difficulty': 'easy',
  'query': 'Show each inventory record with the product name and warehouse name.'},
 {'id': 256, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each sales order number with the customer name.'},
 {'id': 257,
  'category': 'join',
  'difficulty': 'easy',
  'query': 'Show each sales order number with the assigned sales representative.'},
 {'id': 258,
  'category': 'join',
  'difficulty': 'easy',
  'query': 'Show each order item with the order number and product name.'},
 {'id': 259,
  'category': 'join',
  'difficulty': 'easy',
  'query': 'Show each payment number with its sales order number.'},
 {'id': 260,
  'category': 'join',
  'difficulty': 'easy',
  'query': 'Show each shipment number with its sales order number.'},
 {'id': 261, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each shipment number with the destination city.'},
 {'id': 262, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each product name with its department name.'},
 {'id': 263, 'category': 'join', 'difficulty': 'easy', 'query': "Show each employee name with their manager's name."},
 {'id': 264, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each sales order with its billing city.'},
 {'id': 265, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each sales order with its shipping city.'},
 {'id': 266,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List delivered order numbers with customer names and grand totals.'},
 {'id': 267,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List Electronics products with their supplier names and sale prices.'},
 {'id': 268,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List active employees with their department names and salaries.'},
 {'id': 269,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List low-stock inventory records with product names and warehouse names.'},
 {'id': 270,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List settled payments with customer names and payment amounts.'},
 {'id': 271,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List delivered shipments with customer names and actual delivery dates.'},
 {'id': 272,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List high-priority orders with sales representative names.'},
 {'id': 273,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List products from rating-1 suppliers with product names and prices.'},
 {'id': 274,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List shipments sent from temperature-controlled warehouses.'},
 {'id': 275,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List customers and their primary address details.'},
 {'id': 276,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List order items that have backordered units with product names.'},
 {'id': 277,
  'category': 'join',
  'difficulty': 'moderate',
  'query': "List warehouses with their manager's department name."},
 {'id': 278,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List sales orders where billing and shipping addresses are in different states.'},
 {'id': 279,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List products and their available inventory in Spokane warehouses.'},
 {'id': 280,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List suppliers and the products they provide that cost more than 100 dollars.'},
 {'id': 281,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List employees and the department that manages their work location.'},
 {'id': 282,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List refunded orders with customer names and refunded amounts.'},
 {'id': 283,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List shipments with their origin warehouse city and destination city.'},
 {'id': 284,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List customer names with every payment method they have used.'},
 {'id': 285,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List products with the warehouses where they are currently out of stock.'},
 {'id': 286,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List customers whose primary address city matches the city of an open warehouse.'},
 {'id': 287,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List employees who manage another employee and show both employee names.'},
 {'id': 288,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List sales orders with customer name, billing city, shipping city, and sales representative name.'},
 {'id': 289,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List products whose supplier state matches the state of a warehouse storing that product.'},
 {'id': 290,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List delivered shipments where the destination state differs from the origin warehouse state.'},
 {'id': 291,
  'category': 'join',
  'difficulty': 'hard',
  'query': "List order items where the unit price is lower than the product's current sale price."},
 {'id': 292,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List customers whose current balance is greater than the grand total of one of their orders.'},
 {'id': 293,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List products supplied by inactive suppliers but still present in inventory.'},
 {'id': 294,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List departments and warehouses managed by employees from those departments.'},
 {'id': 295,
  'category': 'join',
  'difficulty': 'hard',
  'query': "List payments whose billing postal code matches the order's billing address postal code."},
 {'id': 296,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List shipments whose recipient name differs from the customer name on the order.'},
 {'id': 297,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List employees whose manager works in a different state.'},
 {'id': 298,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List sales orders whose shipping address belongs to a different customer than the order customer.'},
 {'id': 299,
  'category': 'join',
  'difficulty': 'hard',
  'query': "List products whose warehouse-specific reorder point is higher than the product's default reorder point."},
 {'id': 300,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List customers who used the same address for billing and shipping on an order.'},
 {'id': 301,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each order number with customer name and product name.'},
 {'id': 302,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each delivered order with customer name and shipment carrier.'},
 {'id': 303,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each payment with customer name and order number.'},
 {'id': 304,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each order item with product name and supplier name.'},
 {'id': 305,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each inventory record with product name, supplier name, and warehouse name.'},
 {'id': 306,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each shipment with order number, customer name, and destination city.'},
 {'id': 307,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each sales order with customer name, sales representative name, and department name.'},
 {'id': 308,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each product with supplier name and owning department.'},
 {'id': 309,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each order item with order number, product name, and warehouse name.'},
 {'id': 310,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each warehouse with manager name and manager department.'},
 {'id': 311,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each delivered order with customer name and settled payment amount.'},
 {'id': 312,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each shipment with customer name and origin warehouse name.'},
 {'id': 313,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each product with supplier rating and available inventory quantity.'},
 {'id': 314,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each customer with order number and shipping city.'},
 {'id': 315,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each employee with manager name and department name.'},
 {'id': 316,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List delivered orders with customer name, product name, quantity ordered, and line total.'},
 {'id': 317,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List Gold customers with their delivered order numbers and payment amounts.'},
 {'id': 318,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List Electronics products sold on online orders with customer names.'},
 {'id': 319,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List backordered items with order number, product name, supplier name, and warehouse name.'},
 {'id': 320,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List shipments delivered to Washington with customer name and origin warehouse city.'},
 {'id': 321,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List settled credit-card payments with customer name, order total, and card brand.'},
 {'id': 322,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List high-priority orders with customer name, sales representative, and shipment status.'},
 {'id': 323,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List products from high-risk suppliers with warehouse name and available quantity.'},
 {'id': 324,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List active employees who manage warehouses with department and warehouse region.'},
 {'id': 325,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List customer names, order numbers, payment statuses, and shipment statuses for 2025 orders.'},
 {'id': 326,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List refunded payments with customer segment and order sales channel.'},
 {'id': 327,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List Apparel order items with supplier name, customer name, and quantity shipped.'},
 {'id': 328,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List delivered shipments containing Outdoors products with carrier and destination city.'},
 {'id': 329,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List supplier names with product names and total inventory value by warehouse.'},
 {'id': 330,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List enterprise customers with their order numbers, billing state, and shipping state.'},
 {'id': 331,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List order items fulfilled by limited-status warehouses with product and customer names.'},
 {'id': 332,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List products that were ordered but are currently low in stock, with supplier and warehouse.'},
 {'id': 333,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List sales representatives with the customers and products on the orders they handled.'},
 {'id': 334,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List shipments requiring signatures with customer name, order total, and carrier.'},
 {'id': 335,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List active suppliers with products sold through the partner channel and total line amounts.'},
 {'id': 336,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List customers who placed delivered online orders for Electronics products, with order number, product, '
           'payment amount, and carrier.'},
 {'id': 337,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List high-risk suppliers whose products were sold on refunded orders, with customer and refund amount.'},
 {'id': 338,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List warehouses that shipped products to customers in the same state as the warehouse, with customer, '
           'product, and order.'},
 {'id': 339,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': "List sales representatives who handled Platinum customers' delivered orders, with product category and "
           'order revenue.'},
 {'id': 340,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List products that are low in stock but were ordered more than 20 times, with supplier and warehouse.'},
 {'id': 341,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List customer orders where billing state, shipping state, supplier state, and warehouse state are all '
           'different.'},
 {'id': 342,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List delivered shipments that arrived late, with customer, order number, carrier, warehouse, and '
           'destination state.'},
 {'id': 343,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List products supplied by rating-1 suppliers that generated delivered-order revenue in 2025, with revenue '
           'by warehouse.'},
 {'id': 344,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List employees who manage a warehouse and also handled a sales order, with department, warehouse, and '
           'order.'},
 {'id': 345,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List customers whose settled payments came from more than one payment method and whose orders used more '
           'than one carrier.'},
 {'id': 346,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List orders containing products from at least two suppliers, with customer and shipment details.'},
 {'id': 347,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List discontinued products that were sold in 2025 and still have available inventory, with supplier and '
           'warehouse.'},
 {'id': 348,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List customers who bought products from high-risk suppliers and later received a refund, with order and '
           'shipment status.'},
 {'id': 349,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List warehouses with available inventory for products sold to Gold customers through online orders.'},
 {'id': 350,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List departments whose employees handled orders containing products owned by a different department.'},
 {'id': 351,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 5 customers with the highest current balance.'},
 {'id': 352,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 most expensive products by list price.'},
 {'id': 353,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 5 least expensive products by sale price.'},
 {'id': 354, 'category': 'order_limit_topk', 'difficulty': 'easy', 'query': 'Show the 5 highest-rated suppliers.'},
 {'id': 355,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 5 warehouses with the highest utilization percentage.'},
 {'id': 356,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 employees with the highest salaries.'},
 {'id': 357,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 largest sales orders by grand total.'},
 {'id': 358, 'category': 'order_limit_topk', 'difficulty': 'easy', 'query': 'Show the 10 largest payments by amount.'},
 {'id': 359, 'category': 'order_limit_topk', 'difficulty': 'easy', 'query': 'Show the 10 heaviest shipments.'},
 {'id': 360,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 5 departments with the largest annual budgets.'},
 {'id': 361,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 inventory records with the most available units.'},
 {'id': 362,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 products with the largest markup from cost to list price.'},
 {'id': 363,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 5 customers with the most loyalty points.'},
 {'id': 364,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 shipments with the highest shipping cost.'},
 {'id': 365,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 5 suppliers with the longest payment terms.'},
 {'id': 366,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 customers by total sales-order value.'},
 {'id': 367,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 products by total quantity ordered.'},
 {'id': 368,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 5 suppliers by total line revenue from their products.'},
 {'id': 369,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 5 warehouses by total inventory value.'},
 {'id': 370,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 sales representatives by total order revenue handled.'},
 {'id': 371,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 5 product categories by delivered-order revenue.'},
 {'id': 372,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 5 carriers by number of delivered shipments.'},
 {'id': 373,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the bottom 5 warehouses by total available inventory.'},
 {'id': 374,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 customers by total refunded amount.'},
 {'id': 375,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 products by gross profit.'},
 {'id': 376,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the 5 departments with the highest average salary.'},
 {'id': 377,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 cities by number of customer addresses.'},
 {'id': 378,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 5 payment providers by settled payment amount.'},
 {'id': 379,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 products by number of warehouses stocking them.'},
 {'id': 380,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 5 customer segments by average order value.'},
 {'id': 381,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the 10 orders with the largest total discount amount.'},
 {'id': 382,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 5 brands by total quantity sold.'},
 {'id': 383,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 customers by number of delivered orders.'},
 {'id': 384,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 5 destination states by delivered shipment count.'},
 {'id': 385,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the 10 suppliers with the highest average product sale price.'},
 {'id': 386,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 products by delivered-order revenue within each product category.'},
 {'id': 387,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 5 customers by delivered-order revenue within each loyalty tier.'},
 {'id': 388,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the highest-revenue sales representative in each department.'},
 {'id': 389,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 warehouses by shipped quantity within each region.'},
 {'id': 390,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 5 suppliers by gross profit from delivered orders in 2025.'},
 {'id': 391,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the 10 products with the greatest gap between ordered quantity and available inventory.'},
 {'id': 392,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 5 customer cities by average delivered-order value, considering only cities with at least 5 '
           'delivered orders.'},
 {'id': 393,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 carriers by on-time delivery rate, considering only carriers with at least 20 delivered '
           'shipments.'},
 {'id': 394,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the 5 employees with the highest revenue per order handled.'},
 {'id': 395,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 product categories by gross margin percentage.'},
 {'id': 396,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the 5 customers with the greatest refund rate among customers with at least 3 payments.'},
 {'id': 397,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 warehouses by inventory value per capacity unit.'},
 {'id': 398,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the 10 products with the highest sales revenue but no available inventory.'},
 {'id': 399,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 5 suppliers by number of distinct customers who bought their products.'},
 {'id': 400,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 months of 2025 by delivered-order revenue.'},
 {'id': 401,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List cities that appear either in customer addresses or in warehouse locations.'},
 {'id': 402,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List state codes that appear either in customer addresses or supplier addresses.'},
 {'id': 403,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List people names that appear either as customers or employees.'},
 {'id': 404,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List product IDs that are either discontinued or currently out of stock.'},
 {'id': 405,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List customer IDs that have either a sales order or a payment.'},
 {'id': 406,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List order IDs that have either a payment or a shipment.'},
 {'id': 407,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List warehouse IDs that appear either in inventory or in shipments.'},
 {'id': 408,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List product IDs that appear either in inventory or in sales order items.'},
 {'id': 409,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List employee IDs that are either warehouse managers or sales representatives on orders.'},
 {'id': 410,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List address IDs used either for billing or shipping on sales orders.'},
 {'id': 411,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List customers who have placed an online order or a store order.'},
 {'id': 412,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List products that belong to either Electronics or Apparel.'},
 {'id': 413,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List suppliers located in either Washington or Idaho.'},
 {'id': 414,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List shipments sent by either UPS or FedEx.'},
 {'id': 415,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List employees who are either full-time or part-time.'},
 {'id': 416,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List customers who placed orders in both 2024 and 2025.'},
 {'id': 417,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List products that were sold through both online and store channels.'},
 {'id': 418,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List customers who have both a delivered order and a settled payment.'},
 {'id': 419,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List warehouses that both hold inventory and have originated a shipment.'},
 {'id': 420,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List products that are both low in stock and have been ordered.'},
 {'id': 421,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List employees who are both warehouse managers and sales representatives on orders.'},
 {'id': 422,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List customer cities that are also warehouse cities.'},
 {'id': 423,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List suppliers whose products are both in inventory and present on sales orders.'},
 {'id': 424,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List orders that have a payment but no shipment.'},
 {'id': 425,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List products that are in inventory but have never been ordered.'},
 {'id': 426,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List customers who made payments but have no delivered orders.'},
 {'id': 427,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List warehouses that originated shipments but currently have no low-stock inventory.'},
 {'id': 428,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List products sold online but never sold through the store channel.'},
 {'id': 429,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List customers who ordered Electronics but never ordered Apparel.'},
 {'id': 430,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List suppliers with active products but no products appearing on an order.'},
 {'id': 431,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List addresses used for shipping but never used for billing.'},
 {'id': 432,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List employees who handle orders but do not manage a warehouse.'},
 {'id': 433,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List carriers used for delivered shipments but not for shipment exceptions.'},
 {'id': 434,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List product categories sold in 2025 but not sold in 2024.'},
 {'id': 435,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List customers who received shipments but never had a failed payment.'},
 {'id': 436,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List customers who bought products from both Electronics and Outdoors but never bought Apparel.'},
 {'id': 437,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List products sold to both Gold and Platinum customers but not to Bronze customers.'},
 {'id': 438,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List suppliers whose products were sold through both online and partner channels but never through store '
           'orders.'},
 {'id': 439,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List warehouses that shipped products to both Washington and Idaho but not to California.'},
 {'id': 440,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List employees who handled both delivered and cancelled orders but never handled an urgent order.'},
 {'id': 441,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List customers who used both credit-card and ACH payments but never used PayPal.'},
 {'id': 442,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List products that are stocked in both Spokane and Phoenix warehouses but not in Moscow warehouses.'},
 {'id': 443,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List carriers that delivered both overnight and ground shipments but never handled freight shipments.'},
 {'id': 444,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List customer cities that generated orders in both 2024 and 2025 but not in 2026.'},
 {'id': 445,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List product categories represented by both high-risk and low-risk suppliers but not by medium-risk '
           'suppliers.'},
 {'id': 446,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List departments that have both remote and non-remote active employees but no contractor employees.'},
 {'id': 447,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List customers who had both refunded and settled payments but no failed payments.'},
 {'id': 448,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List suppliers whose products are both low in stock and sold on delivered orders but not sold on cancelled '
           'orders.'},
 {'id': 449,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List warehouse regions that handled both Electronics and Apparel items but no Automotive items.'},
 {'id': 450,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List products that were sold in both 2024 and 2025 but have not been sold in 2026.'},
 {'id': 451,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List products priced above the overall average sale price.'},
 {'id': 452,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List employees earning more than the overall average salary.'},
 {'id': 453,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List customers whose current balance is above the average customer balance.'},
 {'id': 454,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List warehouses with utilization above the average warehouse utilization.'},
 {'id': 455,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List suppliers whose rating is above the average supplier rating.'},
 {'id': 456,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List sales orders larger than the average sales order value.'},
 {'id': 457,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List payments larger than the average payment amount.'},
 {'id': 458,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List shipments heavier than the average shipment weight.'},
 {'id': 459,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List departments with budgets above the average department budget.'},
 {'id': 460,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List inventory records with available quantity above the average available quantity.'},
 {'id': 461,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List products that have never appeared on a sales order.'},
 {'id': 462,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List customers who have never placed a sales order.'},
 {'id': 463,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List suppliers that provide no discontinued products.'},
 {'id': 464,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List employees who do not manage any other employee.'},
 {'id': 465,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List warehouses that have never originated a delivered shipment.'},
 {'id': 466,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List products priced above the average sale price for their category.'},
 {'id': 467,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List employees earning more than the average salary in their department.'},
 {'id': 468,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List customers whose total order value is above the average customer total order value.'},
 {'id': 469,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List warehouses whose total inventory value is above the average warehouse inventory value.'},
 {'id': 470,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List suppliers that have at least one product priced above the overall average product sale price.'},
 {'id': 471,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List sales orders larger than the average order placed by the same customer.'},
 {'id': 472,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List payments whose amount is greater than the average payment for the same payment method.'},
 {'id': 473,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List shipments whose shipping cost is above the average cost for the same carrier.'},
 {'id': 474,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List products whose available inventory is below their total ordered quantity.'},
 {'id': 475,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List customers whose most recent order is a delivered order.'},
 {'id': 476,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List employees who handled more orders than the average employee who handled an order.'},
 {'id': 477,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List product categories whose delivered-order revenue is above the average category revenue.'},
 {'id': 478,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List customers who have at least one order but no settled payment.'},
 {'id': 479,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List products stocked in every open warehouse.'},
 {'id': 480,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List suppliers whose every product is currently active and not discontinued.'},
 {'id': 481,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List departments where every active employee has a performance rating above 3.'},
 {'id': 482,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List orders containing at least one product priced above the average price of its category.'},
 {'id': 483,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List customers whose total refunded amount is greater than the average refunded amount among customers '
           'with refunds.'},
 {'id': 484,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List warehouses that stock at least one product from every product category.'},
 {'id': 485,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List products whose latest order date is after the average latest-order date across products.'},
 {'id': 486,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List the highest-revenue product in each product category.'},
 {'id': 487,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List the highest-paid employee in each department.'},
 {'id': 488,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List the largest sales order for each customer.'},
 {'id': 489,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List the most recent shipment for each customer.'},
 {'id': 490,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List customers whose delivered-order revenue is above the average delivered revenue for their loyalty '
           'tier.'},
 {'id': 491,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List suppliers whose product revenue is above the average supplier revenue within the same supplier type.'},
 {'id': 492,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List warehouses whose low-stock product count is above the average low-stock count for warehouses in the '
           'same region.'},
 {'id': 493,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List products whose gross margin percentage is above the average margin for their category and whose sales '
           'revenue is above the category average.'},
 {'id': 494,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': "List employees whose handled-order revenue is above their department's average employee revenue."},
 {'id': 495,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List customers who ordered every product category that appears on any delivered order.'},
 {'id': 496,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List suppliers for whom every supplied product has been ordered at least once.'},
 {'id': 497,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List warehouses that have available inventory for every product sold through the online channel.'},
 {'id': 498,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List customers whose order value increased on each of their three most recent orders.'},
 {'id': 499,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List products whose 2025 sales revenue exceeded their 2024 sales revenue and whose 2026 revenue has not '
           'yet exceeded 2025.'},
 {'id': 500,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List carriers whose on-time delivery rate is above the overall carrier average and whose average shipping '
           'cost is below the overall average shipping cost.'}]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run 500 fixed Northstar Commerce natural-language queries against SpiderSQL."
    )
    parser.add_argument(
        "--database-id",
        type=int,
        required=True,
        help="SpiderSQL database ID assigned after uploading the 12 CSV files.",
    )
    parser.add_argument(
        "--base-url",
        default="http://127.0.0.1:8000",
        help="SpiderSQL backend base URL.",
    )
    parser.add_argument(
        "--output",
        default="northstar_500_query_sql_results.txt",
        help="Single TXT output file containing each query and its generated SQL.",
    )
    parser.add_argument(
        "--timeout",
        type=int,
        default=180,
        help="Per-query HTTP timeout in seconds.",
    )
    parser.add_argument(
        "--start-index",
        type=int,
        default=1,
        help="Start at this 1-based test number. Useful after an interrupted run.",
    )
    parser.add_argument(
        "--end-index",
        type=int,
        default=len(TEST_CASES),
        help="Stop at this 1-based test number.",
    )
    parser.add_argument(
        "--trace-run",
        default="",
        help=(
            "Value sent in the X-SpiderSQL-Trace-Run header on every request. "
            "Sets the full-trace run id / output filename prefix. When empty, "
            "the header is omitted and the backend's SPIDERSQL_TRACE_RUN_ID "
            "environment variable controls the run id."
        ),
    )
    return parser.parse_args()


def post_query(
    base_url: str,
    database_id: int,
    question: str,
    timeout: int,
    test_id: int | None = None,
    category: str | None = None,
    difficulty: str | None = None,
    trace_run: str = "",
) -> tuple[int, dict[str, Any]]:
    url = f"{base_url.rstrip('/')}/database/{database_id}/execute_sql"
    request_body = json.dumps({"question": question}).encode("utf-8")

    # Benchmark instrumentation headers consumed by the backend's full_trace
    # (app.py execute_sql endpoint -> full_trace.set_request_meta). These carry
    # per-request benchmark metadata only; they never alter generation,
    # validation, scoring, or selection. Header names are case-insensitive and
    # match the server's x-spidersql-* lookups exactly.
    headers = {"Content-Type": "application/json", "Accept": "application/json"}
    if test_id is not None:
        headers["X-SpiderSQL-Test-ID"] = str(test_id)
    if category:
        headers["X-SpiderSQL-Test-Category"] = str(category)
    if difficulty:
        headers["X-SpiderSQL-Test-Difficulty"] = str(difficulty)
    if trace_run:
        headers["X-SpiderSQL-Trace-Run"] = str(trace_run)

    request = urllib.request.Request(
        url,
        data=request_body,
        headers=headers,
        method="POST",
    )

    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            status_code = response.getcode()
            raw = response.read().decode("utf-8", errors="replace")
    except urllib.error.HTTPError as exc:
        status_code = exc.code
        raw = exc.read().decode("utf-8", errors="replace")
    except Exception as exc:
        return 0, {"success": False, "_client_error": str(exc)}

    try:
        payload = json.loads(raw) if raw.strip() else {}
    except json.JSONDecodeError:
        payload = {"success": False, "_raw_response": raw}

    if not isinstance(payload, dict):
        payload = {"success": False, "_raw_response": payload}

    return status_code, payload


def extract_sql(payload: dict[str, Any]) -> str:
    generated = payload.get("generated_sql")

    if isinstance(generated, dict):
        for key in ("sql", "query", "generated_sql"):
            value = generated.get(key)
            if isinstance(value, str) and value.strip():
                return value.strip()

    if isinstance(generated, str) and generated.strip():
        return generated.strip()

    for key in ("sql", "query_sql", "final_sql"):
        value = payload.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()

    execution = payload.get("execution")
    if isinstance(execution, dict):
        for key in ("sql", "executed_sql"):
            value = execution.get(key)
            if isinstance(value, str) and value.strip():
                return value.strip()

    return ""


def execution_succeeded(http_status: int, payload: dict[str, Any]) -> bool:
    if http_status < 200 or http_status >= 300:
        return False

    top_level = payload.get("success")
    execution = payload.get("execution")

    if top_level is False:
        return False

    if isinstance(execution, dict) and execution.get("success") is False:
        return False

    if top_level is True:
        return True

    if isinstance(execution, dict) and execution.get("success") is True:
        return True

    return False


def format_record(case: dict[str, Any], status: str, sql: str) -> str:
    displayed_sql = sql if sql else "<NO SQL GENERATED>"
    separator = "=" * 100
    return (
        f"{separator}\n"
        f"TEST {case['id']:03d}\n"
        f"CATEGORY: {case['category']}\n"
        f"DIFFICULTY: {case['difficulty']}\n"
        f"STATUS: {status}\n"
        f"QUERY:\n{case['query']}\n"
        f"SQL:\n{displayed_sql}\n"
    )


def main() -> int:
    args = parse_args()

    if args.start_index < 1 or args.end_index > len(TEST_CASES) or args.start_index > args.end_index:
        print(
            f"Invalid range. Use 1 <= start-index <= end-index <= {len(TEST_CASES)}.",
            file=sys.stderr,
        )
        return 2

    selected_cases = [
        case for case in TEST_CASES
        if args.start_index <= case["id"] <= args.end_index
    ]

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # A complete run overwrites the file. A resumed partial run appends.
    file_mode = "w" if args.start_index == 1 else "a"

    pass_count = 0
    fail_count = 0
    run_started = time.time()

    with output_path.open(file_mode, encoding="utf-8") as output:
        for position, case in enumerate(selected_cases, start=1):
            http_status, payload = post_query(
                base_url=args.base_url,
                database_id=args.database_id,
                question=case["query"],
                timeout=args.timeout,
                test_id=case["id"],
                category=case["category"],
                difficulty=case["difficulty"],
                trace_run=args.trace_run,
            )

            sql = extract_sql(payload)
            passed = execution_succeeded(http_status, payload)
            status = "PASS" if passed else "FAIL"

            if passed:
                pass_count += 1
            else:
                fail_count += 1

            print(
                f"[{position:03d}/{len(selected_cases):03d}] "
                f"{status} | TEST {case['id']:03d} | "
                f"{case['category']} | {case['difficulty']}",
                flush=True,
            )

            output.write(format_record(case, status, sql))
            output.flush()

    elapsed = time.time() - run_started
    print("-" * 100)
    print(f"Completed: {len(selected_cases)}")
    print(f"PASS: {pass_count}")
    print(f"FAIL: {fail_count}")
    print(f"Elapsed seconds: {elapsed:.1f}")
    print(f"TXT output: {output_path.resolve()}")

    return 0 if fail_count == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
