"""
Player database 500-query SpiderSQL execution test.

This file contains 500 fixed, normal natural-language queries for the
twelve-table player database (database ID 57):

- leagues
- seasons
- teams
- coaches
- players
- matches
- player_match_stats
- contracts
- injuries
- training_sessions
- player_training_stats
- transfers

The queries use only the finalized relationships among those tables.

Organization:
- 10 SQL/query categories
- 50 queries per category
- 15 easy, 20 moderate, and 15 hard queries per category

The file contains no expected/reference SQL. At runtime it sends each
natural-language query to SpiderSQL, prints PASS or FAIL, and writes the
generated SQL and query details to one TXT file.

Example:
    python player_db57_500_test_run.py

Optional:
    python player_db57_500_test_run.py --database-id 57 \
        --base-url http://127.0.0.1:8000 \
        --output player_db57_500_query_sql_results.txt \
        --timeout 180
"""

from __future__ import annotations

import argparse
import json
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any


TEST_CASES = [{'id': 1, 'category': 'aggregation', 'difficulty': 'easy', 'query': 'How many leagues are currently active?'},
 {'id': 2,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the average salary cap across all leagues?'},
 {'id': 3,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the highest stadium capacity among all teams?'},
 {'id': 4, 'category': 'aggregation', 'difficulty': 'easy', 'query': 'How many teams are currently active?'},
 {'id': 5,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the average annual revenue across all teams?'},
 {'id': 6, 'category': 'aggregation', 'difficulty': 'easy', 'query': 'How many coaches are currently active?'},
 {'id': 7,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the average annual salary of all coaches?'},
 {'id': 8, 'category': 'aggregation', 'difficulty': 'easy', 'query': 'How many players are currently active?'},
 {'id': 9,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the average market value of all players?'},
 {'id': 10,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the highest career match count among players?'},
 {'id': 11, 'category': 'aggregation', 'difficulty': 'easy', 'query': 'How many matches have been completed?'},
 {'id': 12,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the average attendance across all matches?'},
 {'id': 13,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'How many contracts currently have active status?'},
 {'id': 14, 'category': 'aggregation', 'difficulty': 'easy', 'query': 'How many injury records are still active?'},
 {'id': 15,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the average coach rating across all training records?'},
 {'id': 16,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'How many professional leagues are currently active?'},
 {'id': 17,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average league salary cap for soccer leagues?'},
 {'id': 18,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the total annual revenue of active teams?'},
 {'id': 19,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average team value of teams with more than 5 championships?'},
 {'id': 20,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'How many active coaches have a Pro or Elite license?'},
 {'id': 21,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average salary of head coaches?'},
 {'id': 22,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'How many active players are currently injured?'},
 {'id': 23,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average market value of players who play as forwards?'},
 {'id': 24,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'How many completed matches went to overtime?'},
 {'id': 25,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average ticket revenue for completed matches?'},
 {'id': 26,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'How many player-match records have a rating above 8?'},
 {'id': 27,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average distance covered by players who started a match?'},
 {'id': 28,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the total guaranteed amount across active contracts?'},
 {'id': 29,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average signing bonus for standard contracts?'},
 {'id': 30, 'category': 'aggregation', 'difficulty': 'moderate', 'query': 'How many injury records required surgery?'},
 {'id': 31,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average number of games missed for severe injuries?'},
 {'id': 32, 'category': 'aggregation', 'difficulty': 'moderate', 'query': 'How many training sessions were cancelled?'},
 {'id': 33,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average actual training duration for high-intensity sessions?'},
 {'id': 34,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'How many transfer records have completed status?'},
 {'id': 35,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the total transfer fee for permanent transfers?'},
 {'id': 36,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'How many active players belong to active teams in active leagues?'},
 {'id': 37,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the average market value of active players whose teams have annual revenue above 100 million '
           'dollars?'},
 {'id': 38,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the total salary payroll of teams in professional leagues?'},
 {'id': 39,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'How many completed matches involved two active teams?'},
 {'id': 40,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the average player rating in completed matches during 2025?'},
 {'id': 41,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the total ticket revenue from completed playoff matches?'},
 {'id': 42,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'How many players with active contracts have at least one injury record?'},
 {'id': 43,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the average base salary of players who transferred permanently during 2025?'},
 {'id': 44,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'How many coaches led high-intensity training sessions for active teams?'},
 {'id': 45,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the total transfer fee for players moving between teams in the same league?'},
 {'id': 46,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the average recovery score of active players during high-intensity training sessions?'},
 {'id': 47,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'How many players recorded a match rating above 8 and a training readiness score above 80?'},
 {'id': 48,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the total base salary of players who missed more than 10 games through injury?'},
 {'id': 49,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the average number of completed matches per active season?'},
 {'id': 50,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'How many active players have both a current contract and at least one completed transfer?'},
 {'id': 51,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each league with the difference between its salary cap and minimum salary.'},
 {'id': 52,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each league with the number of teams per playoff place.'},
 {'id': 53,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each season with the number of days between its start and end dates.'},
 {'id': 54,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each season with revenue per recorded attendee.'},
 {'id': 55,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each team with annual revenue as a percentage of team value.'},
 {'id': 56,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each team with salary payroll as a percentage of annual revenue.'},
 {'id': 57,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each team with the number of inactive roster spots based on roster size minus active players.'},
 {'id': 58,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each coach with total matches coached based on wins, losses, and draws.'},
 {'id': 59,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each coach with win percentage based on wins divided by total coached matches.'},
 {'id': 60,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each player with career scores per career match.'},
 {'id': 61,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each player with annual salary as a percentage of market value.'},
 {'id': 62,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each match with total points scored by both teams.'},
 {'id': 63,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each match with home possession minus away possession.'},
 {'id': 64,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each contract with total listed compensation based on base salary and bonuses.'},
 {'id': 65,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each injury with the difference between actual and estimated days out.'},
 {'id': 66,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the percentage of active leagues for each sport.'},
 {'id': 67,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average salary cap per team for each league.'},
 {'id': 68,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate season revenue per match scheduled for each season.'},
 {'id': 69,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the percentage of active teams for each league.'},
 {'id': 70,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate average team payroll as a percentage of team revenue for each league.'},
 {'id': 71,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average coach win percentage for each coach role.'},
 {'id': 72,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the percentage of active players for each team.'},
 {'id': 73,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate average career scores per match for each player position.'},
 {'id': 74,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the percentage of completed matches for each competition stage.'},
 {'id': 75,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate average ticket revenue per attendee for each league.'},
 {'id': 76,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate average player rating per minute played for each position.'},
 {'id': 77,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the percentage of match appearances started for each player.'},
 {'id': 78,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate average guaranteed compensation as a percentage of base salary for each contract type.'},
 {'id': 79,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the percentage of active contracts for each team.'},
 {'id': 80,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average actual days out divided by estimated days out for each injury severity.'},
 {'id': 81,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the surgery rate for each injury type.'},
 {'id': 82,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average attendance rate for each training session type.'},
 {'id': 83,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate average training load per completed minute for each intensity level.'},
 {'id': 84,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average transfer fee per contract year for each transfer type.'},
 {'id': 85,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the percentage of completed transfers for each transfer window.'},
 {'id': 86,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each team, calculate total player salary as a percentage of team annual revenue.'},
 {'id': 87,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each league, calculate completed-match ticket revenue per active team.'},
 {'id': 88,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each player, calculate total match scores per thousand dollars of annual salary.'},
 {'id': 89,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each player, calculate total match minutes divided by career matches.'},
 {'id': 90,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each coach, calculate completed team matches per year of coaching experience.'},
 {'id': 91,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each team, calculate injury games missed per active player.'},
 {'id': 92,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each player, calculate total guaranteed contract amount as a percentage of market value.'},
 {'id': 93,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each season, calculate completed-match attendance as a percentage of recorded season attendance.'},
 {'id': 94,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each league, calculate average team value per championship won.'},
 {'id': 95,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each player position, calculate average match efficiency per minute played.'},
 {'id': 96,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each team, calculate average training readiness per active player.'},
 {'id': 97,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each injury type, calculate games missed per surgery-required case.'},
 {'id': 98,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each transfer type, calculate total fees as a percentage of total performance add-ons.'},
 {'id': 99,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each team, calculate completed transfer fees per roster spot.'},
 {'id': 100,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each player, calculate average training load divided by average recovery score.'},
 {'id': 101,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different sport types are represented by the leagues?'},
 {'id': 102,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many distinct league regions are represented?'},
 {'id': 103,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different competition levels appear?'},
 {'id': 104,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many distinct season statuses are recorded?'},
 {'id': 105,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different team countries are represented?'},
 {'id': 106, 'category': 'distinct_count', 'difficulty': 'easy', 'query': 'How many distinct coach roles appear?'},
 {'id': 107,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different player positions are represented?'},
 {'id': 108, 'category': 'distinct_count', 'difficulty': 'easy', 'query': 'How many distinct player statuses appear?'},
 {'id': 109,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different competition stages occur in matches?'},
 {'id': 110, 'category': 'distinct_count', 'difficulty': 'easy', 'query': 'How many distinct match statuses appear?'},
 {'id': 111,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different contract types are represented?'},
 {'id': 112, 'category': 'distinct_count', 'difficulty': 'easy', 'query': 'How many distinct injury types appear?'},
 {'id': 113,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different training session types are recorded?'},
 {'id': 114, 'category': 'distinct_count', 'difficulty': 'easy', 'query': 'How many distinct transfer types occur?'},
 {'id': 115,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different transfer windows are represented?'},
 {'id': 116,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct teams have at least one active player?'},
 {'id': 117,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct teams employ at least one active coach?'},
 {'id': 118,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct leagues have completed matches?'},
 {'id': 119,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct seasons contain completed matches?'},
 {'id': 120,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct players have appeared in a match?'},
 {'id': 121,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct players started at least one match?'},
 {'id': 122,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct teams have at least one active contract?'},
 {'id': 123,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct players have an active contract?'},
 {'id': 124,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct players have at least one injury record?'},
 {'id': 125,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct matches have an injury linked to them?'},
 {'id': 126,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct teams conducted high-intensity training sessions?'},
 {'id': 127,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct coaches led training sessions?'},
 {'id': 128,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct players have training performance records?'},
 {'id': 129,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct players completed a transfer?'},
 {'id': 130,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct teams received at least one transferred player?'},
 {'id': 131,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct teams sent at least one transferred player?'},
 {'id': 132,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct leagues contain active teams?'},
 {'id': 133,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct players recorded at least one score in a match?'},
 {'id': 134,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct teams won a completed match?'},
 {'id': 135,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct players have both a contract and a training record?'},
 {'id': 136,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct players appeared in completed matches during both 2024 and 2025?'},
 {'id': 137,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct players have both match statistics and training statistics?'},
 {'id': 138,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct teams have both completed matches and completed transfers?'},
 {'id': 139,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct players have both an active contract and an injury record?'},
 {'id': 140,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct coaches led training sessions in more than one season?'},
 {'id': 141,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct teams competed as both home and away teams in completed matches?'},
 {'id': 142,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct players recorded scores for more than one team?'},
 {'id': 143,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct seasons contain matches from more than one competition stage?'},
 {'id': 144,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct players had injuries linked to more than one match?'},
 {'id': 145,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct teams have players under more than one contract type?'},
 {'id': 146,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct players transferred between teams in the same league?'},
 {'id': 147,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct teams had both high-intensity and recovery training sessions?'},
 {'id': 148,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct players recorded both a match rating above 8 and a readiness score above 80?'},
 {'id': 149,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct leagues have teams with both active and inactive players?'},
 {'id': 150,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct players have played matches, attended training, and completed a transfer?'},
 {'id': 151, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count leagues by sport type.'},
 {'id': 152,
  'category': 'group_by',
  'difficulty': 'easy',
  'query': 'Show average league salary cap by competition level.'},
 {'id': 153, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count seasons by season status.'},
 {'id': 154, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Show total season revenue by season year.'},
 {'id': 155, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count teams by league.'},
 {'id': 156, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Show average team value by country.'},
 {'id': 157, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count coaches by coach role.'},
 {'id': 158, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Show average coach salary by license level.'},
 {'id': 159, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count players by position.'},
 {'id': 160,
  'category': 'group_by',
  'difficulty': 'easy',
  'query': 'Show average player market value by current status.'},
 {'id': 161, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count matches by match status.'},
 {'id': 162,
  'category': 'group_by',
  'difficulty': 'easy',
  'query': 'Show average match attendance by competition stage.'},
 {'id': 163, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count contracts by contract type.'},
 {'id': 164, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count injuries by severity.'},
 {'id': 165, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count transfers by transfer status.'},
 {'id': 166, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Count active teams by league.'},
 {'id': 167, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Show total team revenue by league.'},
 {'id': 168, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Count active coaches by team.'},
 {'id': 169,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show average coach performance rating by team.'},
 {'id': 170, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Count active players by team.'},
 {'id': 171, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Show average player market value by team.'},
 {'id': 172, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Count completed matches by season.'},
 {'id': 173, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Show total ticket revenue by league.'},
 {'id': 174,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show average home score by competition stage.'},
 {'id': 175, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Show average player rating by position.'},
 {'id': 176, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Show total match minutes by player.'},
 {'id': 177, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Count active contracts by team.'},
 {'id': 178, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Show total base salary by contract type.'},
 {'id': 179, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Count injury records by team and severity.'},
 {'id': 180, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Show average games missed by injury type.'},
 {'id': 181,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Count training sessions by team and session type.'},
 {'id': 182,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show average actual training duration by intensity level.'},
 {'id': 183, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Show average readiness score by team.'},
 {'id': 184, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Count completed transfers by transfer type.'},
 {'id': 185, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Show total transfer fee by destination team.'},
 {'id': 186,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show completed match count by league and season year.'},
 {'id': 187,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show total ticket revenue by league and competition stage.'},
 {'id': 188,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show player count and average market value by league and position.'},
 {'id': 189,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show coach count and average salary by league and coach role.'},
 {'id': 190,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show total player salary by team and contract type.'},
 {'id': 191,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show match scores and assists by team and season.'},
 {'id': 192,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show average player rating by team and competition stage.'},
 {'id': 193,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show injury count and games missed by team and body part.'},
 {'id': 194,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show training load and recovery score by team and intensity level.'},
 {'id': 195,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show completed transfer count and fees by league and transfer type.'},
 {'id': 196,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show active contract count and guaranteed amount by league and team.'},
 {'id': 197,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show completed match attendance by home team and season year.'},
 {'id': 198,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show average efficiency score by player position and team.'},
 {'id': 199,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show transfer count by former team and destination team.'},
 {'id': 200,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show active player count, injury count, and training attendance by team.'},
 {'id': 201,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List sport types represented by more than five leagues.'},
 {'id': 202,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List competition levels with an average salary cap above 50 million dollars.'},
 {'id': 203, 'category': 'having', 'difficulty': 'easy', 'query': 'List season years with more than five seasons.'},
 {'id': 204, 'category': 'having', 'difficulty': 'easy', 'query': 'List leagues with more than one team.'},
 {'id': 205, 'category': 'having', 'difficulty': 'easy', 'query': 'List countries with more than five teams.'},
 {'id': 206,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List coach roles represented by more than five coaches.'},
 {'id': 207,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List license levels with an average coach salary above 500000 dollars.'},
 {'id': 208,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List player positions represented by more than ten players.'},
 {'id': 209,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List player statuses represented by more than five players.'},
 {'id': 210,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List match stages with an average attendance above 20000.'},
 {'id': 211,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List contract types represented by more than five contracts.'},
 {'id': 212,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List injury severities with an average of more than 10 games missed.'},
 {'id': 213,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List training session types represented by more than five sessions.'},
 {'id': 214,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List intensity levels with an average training duration above 90 minutes.'},
 {'id': 215,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List transfer types with total fees above 10 million dollars.'},
 {'id': 216, 'category': 'having', 'difficulty': 'moderate', 'query': 'List leagues with more than two active teams.'},
 {'id': 217,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List teams with more than three active players.'},
 {'id': 218, 'category': 'having', 'difficulty': 'moderate', 'query': 'List teams with more than two active coaches.'},
 {'id': 219,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List coaches who have led more than two training sessions.'},
 {'id': 220,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List players with more than two match appearances.'},
 {'id': 221,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List players whose total match scores exceed five.'},
 {'id': 222,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List teams with more than three completed matches.'},
 {'id': 223,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List seasons with total match attendance above 100000.'},
 {'id': 224,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List players with an average match rating above 7.'},
 {'id': 225,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List teams whose total active-contract salary exceeds 5 million dollars.'},
 {'id': 226,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List players with more than one active contract record.'},
 {'id': 227, 'category': 'having', 'difficulty': 'moderate', 'query': 'List teams with more than two injury records.'},
 {'id': 228,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List injury types with an average recovery time above 30 days.'},
 {'id': 229,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List teams with more than three training sessions.'},
 {'id': 230,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List players with an average readiness score above 75.'},
 {'id': 231,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List teams with total transfer fees above 10 million dollars.'},
 {'id': 232,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List destination teams that received more than two players.'},
 {'id': 233,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List leagues whose teams have an average value above 100 million dollars.'},
 {'id': 234,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List teams whose players have an average market value above 10 million dollars.'},
 {'id': 235,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List players whose average training load exceeds 500.'},
 {'id': 236,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List leagues whose completed-match attendance is above the average league attendance.'},
 {'id': 237,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List teams whose active-player payroll exceeds their annual revenue.'},
 {'id': 238,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List players whose average match rating is above the average for their position.'},
 {'id': 239,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List coaches whose win percentage is above the average coach win percentage.'},
 {'id': 240,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List teams whose injury rate exceeds 20 percent of active players.'},
 {'id': 241,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List seasons whose completed-match revenue is above the average season revenue.'},
 {'id': 242,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List players whose total guaranteed contract amount exceeds their market value.'},
 {'id': 243,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List teams whose average training readiness is above the league average.'},
 {'id': 244,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List players who scored in matches for at least two different teams.'},
 {'id': 245,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List leagues with completed matches in at least three competition stages.'},
 {'id': 246,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List teams that completed more transfers than the average team.'},
 {'id': 247,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List injury types whose average actual days out exceed the estimated days out.'},
 {'id': 248,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List players whose match efficiency score is above the overall player average.'},
 {'id': 249,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List teams whose completed transfer fees exceed their salary payroll.'},
 {'id': 250,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List leagues where active teams average more than five active players.'},
 {'id': 251, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each season with its league name.'},
 {'id': 252, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each team with its league name.'},
 {'id': 253, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each coach with their team name.'},
 {'id': 254, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each player with their team name.'},
 {'id': 255, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each match with its season name.'},
 {'id': 256, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each match with its league name.'},
 {'id': 257, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each match with the home team name.'},
 {'id': 258, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each match with the away team name.'},
 {'id': 259,
  'category': 'join',
  'difficulty': 'easy',
  'query': 'Show each completed match with the winning team name.'},
 {'id': 260,
  'category': 'join',
  'difficulty': 'easy',
  'query': "Show each player match record with the player's name."},
 {'id': 261, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each player match record with the team name.'},
 {'id': 262, 'category': 'join', 'difficulty': 'easy', 'query': "Show each contract with the player's name."},
 {'id': 263, 'category': 'join', 'difficulty': 'easy', 'query': "Show each injury with the player's name."},
 {'id': 264, 'category': 'join', 'difficulty': 'easy', 'query': "Show each training session with the coach's name."},
 {'id': 265, 'category': 'join', 'difficulty': 'easy', 'query': "Show each transfer with the player's name."},
 {'id': 266,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List active teams with their league names and annual revenue.'},
 {'id': 267,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List active coaches with their team names and salaries.'},
 {'id': 268,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List active players with their team names and market values.'},
 {'id': 269,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List completed matches with home team, away team, and final scores.'},
 {'id': 270,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List completed matches with season names and ticket revenue.'},
 {'id': 271,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List player performances with player names and match dates.'},
 {'id': 272,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List players who scored in a match with their team names.'},
 {'id': 273,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List active contracts with player names and team names.'},
 {'id': 274,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List severe injuries with player names and team names.'},
 {'id': 275,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List injuries linked to matches with player names and match dates.'},
 {'id': 276,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List high-intensity training sessions with coach and team names.'},
 {'id': 277,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List training performances with player names and readiness scores.'},
 {'id': 278,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List completed transfers with player names and former team names.'},
 {'id': 279,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List completed transfers with player names and destination team names.'},
 {'id': 280,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List players whose current team matches the destination team of a completed transfer.'},
 {'id': 281,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List teams in professional leagues with their league salary caps.'},
 {'id': 282,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List players with active contracts and their contract end dates.'},
 {'id': 283,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List coaches who lead training sessions for their own team.'},
 {'id': 284,
  'category': 'join',
  'difficulty': 'moderate',
  'query': "List match performances where the recorded team matches the player's current team."},
 {'id': 285,
  'category': 'join',
  'difficulty': 'moderate',
  'query': "List injuries where the recorded team matches the player's current team."},
 {'id': 286,
  'category': 'join',
  'difficulty': 'hard',
  'query': "List matches where the match league differs from the season's league."},
 {'id': 287,
  'category': 'join',
  'difficulty': 'hard',
  'query': "List player match records where the recorded team differs from the player's current team."},
 {'id': 288,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List player match records where the recorded season differs from the match season.'},
 {'id': 289,
  'category': 'join',
  'difficulty': 'hard',
  'query': "List contracts where the contract team differs from the player's current team."},
 {'id': 290,
  'category': 'join',
  'difficulty': 'hard',
  'query': "List injury records where the injury team differs from the player's current team."},
 {'id': 291,
  'category': 'join',
  'difficulty': 'hard',
  'query': "List training records where the recorded team differs from the player's current team."},
 {'id': 292,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List training records where the recorded season differs from the training session season.'},
 {'id': 293,
  'category': 'join',
  'difficulty': 'hard',
  'query': "List transfers where the destination team is the player's current team."},
 {'id': 294,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List transfers where the former and destination teams belong to different leagues.'},
 {'id': 295,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List matches where the home and away teams belong to different leagues.'},
 {'id': 296,
  'category': 'join',
  'difficulty': 'hard',
  'query': "List training sessions where the coach's team differs from the session team."},
 {'id': 297,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List injuries linked to matches where the injury team was not one of the two match teams.'},
 {'id': 298,
  'category': 'join',
  'difficulty': 'hard',
  'query': "List player match records where the player's team was neither the home nor away team."},
 {'id': 299,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List completed matches where the winning team was neither the home nor away team.'},
 {'id': 300,
  'category': 'join',
  'difficulty': 'hard',
  'query': "List contracts where the contract team belongs to a different league from the player's current team."},
 {'id': 301,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each player with their team and league names.'},
 {'id': 302,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each coach with their team and league names.'},
 {'id': 303,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each match with season, league, home team, and away team.'},
 {'id': 304,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each player match record with player name, team name, and match date.'},
 {'id': 305,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each contract with player name, team name, and league name.'},
 {'id': 306,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each injury with player name, team name, and match date when available.'},
 {'id': 307,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each training session with team, coach, and season names.'},
 {'id': 308,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each training record with player, team, and session date.'},
 {'id': 309,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each transfer with player, former team, and destination team.'},
 {'id': 310,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each completed match with winning team and league name.'},
 {'id': 311,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each active player with team, league, and coach names.'},
 {'id': 312,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each match performance with player position and competition stage.'},
 {'id': 313,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each injury with player position and team league.'},
 {'id': 314,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each active contract with player position and team league.'},
 {'id': 315,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each transfer with player position and season name.'},
 {'id': 316,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List active players with team, league, and active-contract details.'},
 {'id': 317,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List completed matches with season, league, both teams, and winning team.'},
 {'id': 318,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List player performances with player, team, match, season, and league details.'},
 {'id': 319,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List severe injuries with player, team, match, and season details.'},
 {'id': 320,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List high-intensity training performances with player, coach, team, and season.'},
 {'id': 321,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List completed transfers with player, former team, destination team, and season.'},
 {'id': 322,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List players who scored in completed matches with team and league details.'},
 {'id': 323,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List active players who have both an active contract and a training record.'},
 {'id': 324,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List players with surgery-required injuries and their current contract details.'},
 {'id': 325,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List coaches who led training sessions for active teams in active leagues.'},
 {'id': 326,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List completed matches involving teams from active leagues with season revenue.'},
 {'id': 327,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List players whose match team and training team are the same.'},
 {'id': 328,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List players who transferred to their current team and later appeared in a match for that team.'},
 {'id': 329,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List teams with active players, active coaches, and completed matches.'},
 {'id': 330,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List player injuries linked to matches, including both match teams.'},
 {'id': 331,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List active contracts for players who appeared in completed matches.'},
 {'id': 332,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List training sessions attended by players who also have match appearances.'},
 {'id': 333,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List permanent transfers involving players with active contracts at the destination team.'},
 {'id': 334,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List teams with player contracts, injury records, and training sessions.'},
 {'id': 335,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List leagues with active teams, completed matches, and completed transfers.'},
 {'id': 336,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List players who scored in a completed match, attended high-intensity training, and have an active '
           'contract.'},
 {'id': 337,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List teams whose players have both severe injuries and completed transfer records.'},
 {'id': 338,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List players who transferred between teams in the same league and later played for the destination team.'},
 {'id': 339,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List coaches whose training sessions included players who appeared in completed matches for the same '
           'team.'},
 {'id': 340,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List active players whose current team differs from both their contract team and latest match team.'},
 {'id': 341,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List completed matches with player performances, injury records, and contract details for the same '
           'player.'},
 {'id': 342,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List teams that had completed matches, active contracts, injuries, and completed transfers in the same '
           'season.'},
 {'id': 343,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List players who appeared for one team, trained with another team, and transferred to a third team.'},
 {'id': 344,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List leagues whose teams had both surgery-required injuries and permanent transfers.'},
 {'id': 345,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List players whose injury match was played between their former and destination teams.'},
 {'id': 346,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List coaches who led high-intensity sessions for players with match ratings above 8.'},
 {'id': 347,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List teams whose active players have contracts, match statistics, and training statistics.'},
 {'id': 348,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List players who completed a transfer and then recorded match statistics in the same season.'},
 {'id': 349,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List seasons containing completed matches, training sessions, injuries, and transfers for the same team.'},
 {'id': 350,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List leagues where at least one player has an active contract, a completed transfer, a match appearance, '
           'and a training record.'},
 {'id': 351,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 5 leagues with the highest salary caps.'},
 {'id': 352,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 5 seasons with the largest total revenue.'},
 {'id': 353,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 teams with the highest team values.'},
 {'id': 354,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 teams with the largest annual revenue.'},
 {'id': 355,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 coaches with the highest annual salaries.'},
 {'id': 356,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 coaches with the most career wins.'},
 {'id': 357,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 players with the highest market values.'},
 {'id': 358,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 players with the highest annual salaries.'},
 {'id': 359,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 matches with the largest attendance.'},
 {'id': 360,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 matches with the highest ticket revenue.'},
 {'id': 361,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 player performances with the highest ratings.'},
 {'id': 362,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 contracts with the largest base salaries.'},
 {'id': 363,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 injuries with the most games missed.'},
 {'id': 364,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 training sessions with the longest duration.'},
 {'id': 365,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 transfers with the highest transfer fees.'},
 {'id': 366,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 leagues by number of active teams.'},
 {'id': 367,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 teams by number of active players.'},
 {'id': 368,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 teams by number of active coaches.'},
 {'id': 369,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 players by total match scores.'},
 {'id': 370,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 players by average match rating.'},
 {'id': 371,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 teams by completed match wins.'},
 {'id': 372,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 seasons by completed match attendance.'},
 {'id': 373,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 players by total base salary across contracts.'},
 {'id': 374,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 teams by active-contract payroll.'},
 {'id': 375,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 players by number of injury records.'},
 {'id': 376,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 teams by total games missed through injury.'},
 {'id': 377,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 coaches by number of training sessions led.'},
 {'id': 378,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 players by average readiness score.'},
 {'id': 379,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 teams by total training load.'},
 {'id': 380,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 players by completed transfer fees.'},
 {'id': 381,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 destination teams by incoming transfer fees.'},
 {'id': 382,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 leagues by completed match ticket revenue.'},
 {'id': 383,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 positions by average player market value.'},
 {'id': 384,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 teams by average player match rating.'},
 {'id': 385,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 players by combined match and training efficiency scores.'},
 {'id': 386,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 players by market value within each team.'},
 {'id': 387,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the highest-paid coach in each team.'},
 {'id': 388,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 teams by completed-match revenue within each league.'},
 {'id': 389,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 players by average match rating within each position.'},
 {'id': 390,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 teams by active-contract payroll within each league.'},
 {'id': 391,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 5 players by scoring rate among players with at least three match appearances.'},
 {'id': 392,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 teams by injury rate among teams with at least five active players.'},
 {'id': 393,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 players by training readiness within each team.'},
 {'id': 394,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 destination teams by transfer fees within each season.'},
 {'id': 395,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 5 players by contract value among players with at least one completed transfer.'},
 {'id': 396,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 leagues by average team value among leagues with at least two teams.'},
 {'id': 397,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 seasons by ticket revenue among seasons with at least three completed matches.'},
 {'id': 398,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 5 coaches by win percentage among coaches with at least 20 recorded matches.'},
 {'id': 399,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 teams by average player efficiency within each league.'},
 {'id': 400,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 5 players by match rating and readiness combined among players with both records.'},
 {'id': 401,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List team identifiers that appear either in player records or coach records.'},
 {'id': 402,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List player identifiers that appear either in match statistics or training statistics.'},
 {'id': 403,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List team identifiers that appear either as home teams or away teams.'},
 {'id': 404,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List season identifiers that appear either in matches or training sessions.'},
 {'id': 405,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List player identifiers that appear either in contracts or injuries.'},
 {'id': 406,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List team identifiers that appear either in contracts or transfers.'},
 {'id': 407,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List players who are either active or injured.'},
 {'id': 408,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List teams that are either active or have more than five championships.'},
 {'id': 409,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List matches that are either completed or scheduled.'},
 {'id': 410,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List contracts that are either active or pending.'},
 {'id': 411,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List injuries that are either severe or moderate.'},
 {'id': 412,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List training sessions that are either high intensity or maximum intensity.'},
 {'id': 413,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List transfers that are either permanent or loan transfers.'},
 {'id': 414,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List leagues that are either professional or semi-professional.'},
 {'id': 415,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List coaches who are either head coaches or assistant coaches.'},
 {'id': 416,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List players who have both match statistics and training statistics.'},
 {'id': 417,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List teams that have both players and coaches.'},
 {'id': 418,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List seasons that have both matches and training sessions.'},
 {'id': 419,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List players who have both contracts and injury records.'},
 {'id': 420,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List teams that have both completed matches and active contracts.'},
 {'id': 421,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List players with match appearances but no training records.'},
 {'id': 422,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List players with training records but no match appearances.'},
 {'id': 423,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List teams with active contracts but no completed transfers.'},
 {'id': 424,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List players with injury records but no active contract.'},
 {'id': 425,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List coaches who led training sessions but have no active team.'},
 {'id': 426,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List teams that appeared as home teams but never as away teams.'},
 {'id': 427,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List players who scored in matches but never recorded an assist.'},
 {'id': 428,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List teams with high-intensity training sessions but no recovery sessions.'},
 {'id': 429,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List players who completed transfers but have no current active contract.'},
 {'id': 430,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List seasons with completed matches but no completed transfers.'},
 {'id': 431,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List teams with injuries but no surgery-required injuries.'},
 {'id': 432,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List players with active contracts but no match statistics.'},
 {'id': 433,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List leagues with active teams but no completed matches.'},
 {'id': 434,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List players who trained for one team but played matches for another.'},
 {'id': 435,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List teams that received players in transfers but never sent a player.'},
 {'id': 436,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List players who have match statistics and training statistics but no injury record.'},
 {'id': 437,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List teams with both completed matches and completed transfers but no active contracts.'},
 {'id': 438,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List players with both active contracts and injuries but no completed transfer.'},
 {'id': 439,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List leagues with both completed and scheduled matches but no cancelled matches.'},
 {'id': 440,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List teams with players in both active and injured status but no suspended players.'},
 {'id': 441,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List players who appeared for both their current team and another team but never transferred.'},
 {'id': 442,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List coaches who led both high-intensity and recovery sessions but no cancelled session.'},
 {'id': 443,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List teams that were both home and away winners but never drew a match.'},
 {'id': 444,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List players with both surgery-required and non-surgery injuries but no reinjury record.'},
 {'id': 445,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List seasons with matches in both regular season and playoff stages but no final.'},
 {'id': 446,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List teams that both sent and received transferred players but had no free transfer.'},
 {'id': 447,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List players with both standard and loan contracts but no pending contract.'},
 {'id': 448,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List leagues whose teams had both high-value and low-value players but no retired players.'},
 {'id': 449,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List players with match ratings above 8 and readiness above 80 but no active injury.'},
 {'id': 450,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List teams with completed matches, training sessions, and transfers but no injury records.'},
 {'id': 451,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List leagues with salary caps above the average league salary cap.'},
 {'id': 452,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List seasons with revenue above the average season revenue.'},
 {'id': 453,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List teams valued above the average team value.'},
 {'id': 454,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List teams with annual revenue above the average team revenue.'},
 {'id': 455,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List coaches earning more than the average coach salary.'},
 {'id': 456,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List coaches with more wins than the average coach.'},
 {'id': 457,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List players valued above the average player market value.'},
 {'id': 458,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List players earning more than the average player salary.'},
 {'id': 459,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List matches with attendance above the average match attendance.'},
 {'id': 460,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List player performances with ratings above the average player rating.'},
 {'id': 461,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List contracts with base salaries above the average contract salary.'},
 {'id': 462,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List injuries causing more games missed than the average injury.'},
 {'id': 463,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List training sessions longer than the average training session.'},
 {'id': 464,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List transfers with fees above the average transfer fee.'},
 {'id': 465,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List players who have never appeared in a match.'},
 {'id': 466,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List teams valued above the average team value in their league.'},
 {'id': 467,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List coaches earning more than the average coach salary on their team.'},
 {'id': 468,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List players valued above the average player market value on their team.'},
 {'id': 469,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List players with more match appearances than the average player with an appearance.'},
 {'id': 470,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List players whose average match rating exceeds the average rating of players on their current team.'},
 {'id': 471,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List teams with more completed wins than the average team.'},
 {'id': 472,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List seasons with completed-match attendance above the average season attendance.'},
 {'id': 473,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List players whose total contract salary is above the average player contract salary.'},
 {'id': 474,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List teams whose active-contract payroll is above the average team payroll.'},
 {'id': 475,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List players with more injury records than the average injured player.'},
 {'id': 476,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List teams whose total games missed is above the average team injury total.'},
 {'id': 477,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List coaches who led more training sessions than the average coach.'},
 {'id': 478,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List players whose readiness score is above the average for their team.'},
 {'id': 479,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List teams whose total training load is above the average team load.'},
 {'id': 480,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List players whose completed transfer fees exceed the average transferred player.'},
 {'id': 481,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List destination teams whose incoming transfer fees exceed the average destination team.'},
 {'id': 482,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List matches with ticket revenue above the average for their competition stage.'},
 {'id': 483,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List contracts whose guaranteed amount is above the average for their contract type.'},
 {'id': 484,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List injuries whose recovery time is above the average for their injury type.'},
 {'id': 485,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List transfers whose fee is above the average for their transfer type.'},
 {'id': 486, 'category': 'subquery_cte', 'difficulty': 'hard', 'query': 'List the most valuable player on each team.'},
 {'id': 487, 'category': 'subquery_cte', 'difficulty': 'hard', 'query': 'List the highest-paid coach on each team.'},
 {'id': 488,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List the highest-revenue completed match in each season.'},
 {'id': 489,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List players whose average match rating is above the average for their team and position.'},
 {'id': 490,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List teams whose active-contract payroll is above the average for teams in the same league.'},
 {'id': 491,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List leagues whose completed-match ticket revenue is above the average league revenue.'},
 {'id': 492,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List players whose total contract value is above the average for players at the same position.'},
 {'id': 493,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List teams whose injury rate is above the average injury rate in their league.'},
 {'id': 494,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List players whose average readiness score is above the team average and whose match rating is above the '
           'position average.'},
 {'id': 495,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List coaches whose win percentage is above the average for coaches in the same role.'},
 {'id': 496,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List players who appeared in every completed match played by their team.'},
 {'id': 497,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List teams where every active player has at least one active contract.'},
 {'id': 498,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List seasons where every completed match has at least one player performance record.'},
 {'id': 499,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List players whose three most recent match ratings improved each time.'},
 {'id': 500,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List teams whose 2025 completed-match revenue exceeded their 2024 completed-match revenue.'}]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run 500 fixed player-database natural-language queries against SpiderSQL."
    )
    parser.add_argument(
        "--database-id",
        type=int,
        default=57,
        help="SpiderSQL database ID. Defaults to the uploaded player database ID 57.",
    )
    parser.add_argument(
        "--base-url",
        default="http://127.0.0.1:8000",
        help="SpiderSQL backend base URL.",
    )
    parser.add_argument(
        "--output",
        default="player_db57_500_query_sql_results.txt",
        help="Single TXT output file containing each query and its generated SQL.",
    )
    parser.add_argument(
        "--timeout",
        type=int,
        default=180,
        help="Per-query HTTP timeout in seconds.",
    )
    parser.add_argument(
        "--start-index",
        type=int,
        default=1,
        help="Start at this 1-based test number. Useful after an interrupted run.",
    )
    parser.add_argument(
        "--end-index",
        type=int,
        default=len(TEST_CASES),
        help="Stop at this 1-based test number.",
    )
    return parser.parse_args()


def _trace_headers(trace_meta: dict[str, str] | None) -> dict[str, str]:
    """Emit the optional X-SpiderSQL-* diagnostic headers so full-trace runs
    capture per-test metadata (test id / category / difficulty / trace run).
    No-op ({}) when trace_meta is None. Only sent when values are present."""
    if not trace_meta:
        return {}
    name = {"test_id": "X-SpiderSQL-Test-ID", "category": "X-SpiderSQL-Category",
            "difficulty": "X-SpiderSQL-Difficulty", "trace_run": "X-SpiderSQL-Trace-Run"}
    return {name[k]: str(v) for k, v in trace_meta.items() if k in name and v}


def post_query(base_url: str, database_id: int, question: str, timeout: int, trace_meta: dict[str, str] | None = None) -> tuple[int, dict[str, Any]]:
    url = f"{base_url.rstrip('/')}/database/{database_id}/execute_sql"
    request_body = json.dumps({"question": question}).encode("utf-8")
    request = urllib.request.Request(
        url,
        data=request_body,
        headers={"Content-Type": "application/json", "Accept": "application/json",
                 **_trace_headers(trace_meta)},
        method="POST",
    )

    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            status_code = response.getcode()
            raw = response.read().decode("utf-8", errors="replace")
    except urllib.error.HTTPError as exc:
        status_code = exc.code
        raw = exc.read().decode("utf-8", errors="replace")
    except Exception as exc:
        return 0, {"success": False, "_client_error": str(exc)}

    try:
        payload = json.loads(raw) if raw.strip() else {}
    except json.JSONDecodeError:
        payload = {"success": False, "_raw_response": raw}

    if not isinstance(payload, dict):
        payload = {"success": False, "_raw_response": payload}

    return status_code, payload


def extract_sql(payload: dict[str, Any]) -> str:
    generated = payload.get("generated_sql")

    if isinstance(generated, dict):
        for key in ("sql", "query", "generated_sql"):
            value = generated.get(key)
            if isinstance(value, str) and value.strip():
                return value.strip()

    if isinstance(generated, str) and generated.strip():
        return generated.strip()

    for key in ("sql", "query_sql", "final_sql"):
        value = payload.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()

    execution = payload.get("execution")
    if isinstance(execution, dict):
        for key in ("sql", "executed_sql"):
            value = execution.get(key)
            if isinstance(value, str) and value.strip():
                return value.strip()

    return ""


def execution_succeeded(http_status: int, payload: dict[str, Any]) -> bool:
    if http_status < 200 or http_status >= 300:
        return False

    top_level = payload.get("success")
    execution = payload.get("execution")

    if top_level is False:
        return False

    if isinstance(execution, dict) and execution.get("success") is False:
        return False

    if top_level is True:
        return True

    if isinstance(execution, dict) and execution.get("success") is True:
        return True

    return False


def format_record(case: dict[str, Any], status: str, sql: str) -> str:
    displayed_sql = sql if sql else "<NO SQL GENERATED>"
    separator = "=" * 100
    return (
        f"{separator}\n"
        f"TEST {case['id']:03d}\n"
        f"CATEGORY: {case['category']}\n"
        f"DIFFICULTY: {case['difficulty']}\n"
        f"STATUS: {status}\n"
        f"QUERY:\n{case['query']}\n"
        f"SQL:\n{displayed_sql}\n"
    )


def main() -> int:
    args = parse_args()

    if args.start_index < 1 or args.end_index > len(TEST_CASES) or args.start_index > args.end_index:
        print(
            f"Invalid range. Use 1 <= start-index <= end-index <= {len(TEST_CASES)}.",
            file=sys.stderr,
        )
        return 2

    selected_cases = [
        case for case in TEST_CASES
        if args.start_index <= case["id"] <= args.end_index
    ]

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    file_mode = "w" if args.start_index == 1 else "a"

    pass_count = 0
    fail_count = 0
    run_started = time.time()

    with output_path.open(file_mode, encoding="utf-8") as output:
        for position, case in enumerate(selected_cases, start=1):
            http_status, payload = post_query(
                base_url=args.base_url,
                database_id=args.database_id,
                question=case["query"],
                timeout=args.timeout,
                trace_meta={
                    "test_id": str(case.get("id", position)),
                    "category": case.get("category"),
                    "difficulty": case.get("difficulty"),
                    "trace_run": getattr(args, "trace_run", None),
                },
            )

            sql = extract_sql(payload)
            passed = execution_succeeded(http_status, payload)
            status = "PASS" if passed else "FAIL"

            if passed:
                pass_count += 1
            else:
                fail_count += 1

            print(
                f"[{position:03d}/{len(selected_cases):03d}] "
                f"{status} | TEST {case['id']:03d} | "
                f"{case['category']} | {case['difficulty']}",
                flush=True,
            )

            output.write(format_record(case, status, sql))
            output.flush()

    elapsed = time.time() - run_started
    print("-" * 100)
    print(f"Completed: {len(selected_cases)}")
    print(f"PASS: {pass_count}")
    print(f"FAIL: {fail_count}")
    print(f"Elapsed seconds: {elapsed:.1f}")
    print(f"TXT output: {output_path.resolve()}")

    return 0 if fail_count == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
