"""
Sales database 500-query SpiderSQL execution test.

This file contains 500 fixed, normal natural-language queries for the
six-table sales database (database ID 54):

- customers
- suppliers
- products
- warehouses
- sales_orders
- sales_order_items

The queries follow only these relationships:

- products.supplier_id -> suppliers.supplier_id
- sales_orders.customer_id -> customers.customer_id
- sales_orders.warehouse_id -> warehouses.warehouse_id
- sales_order_items.order_id -> sales_orders.order_id
- sales_order_items.product_id -> products.product_id
- sales_order_items.warehouse_id -> warehouses.warehouse_id

Organization:
- 10 SQL/query categories
- 50 queries per category
- 15 easy, 20 moderate, and 15 hard queries per category

The file does not contain expected/reference SQL. At runtime it sends each
fixed natural-language query to SpiderSQL, prints PASS or FAIL, and writes
the generated SQL and query details to one TXT file.

Example:
    python sales_db54_500_test_run.py

Optional:
    python sales_db54_500_test_run.py --database-id 54 \
        --base-url http://127.0.0.1:8000 \
        --output sales_db54_500_query_sql_results.txt \
        --timeout 180
"""

from __future__ import annotations

import argparse
import json
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any


TEST_CASES = [{'id': 1,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'How many customers currently have an active account?'},
 {'id': 2,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the total current balance across all customers?'},
 {'id': 3,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the average credit limit for enterprise customers?'},
 {'id': 4,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the highest risk score among active customers?'},
 {'id': 5, 'category': 'aggregation', 'difficulty': 'easy', 'query': 'How many suppliers are marked as preferred?'},
 {'id': 6,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the average rating across all suppliers?'},
 {'id': 7,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the combined annual revenue of all active suppliers?'},
 {'id': 8,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the average sale price across all products?'},
 {'id': 9,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the highest list price among Electronics products?'},
 {'id': 10,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the lowest standard cost among Apparel products?'},
 {'id': 11, 'category': 'aggregation', 'difficulty': 'easy', 'query': 'How many warehouses are currently open?'},
 {'id': 12,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the average utilization percentage of Northwest warehouses?'},
 {'id': 13,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the total capacity of all open warehouses?'},
 {'id': 14, 'category': 'aggregation', 'difficulty': 'easy', 'query': 'How many sales orders have been delivered?'},
 {'id': 15,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the total grand total of orders whose payment status is settled?'},
 {'id': 16,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What was the total revenue from delivered orders placed in 2025?'},
 {'id': 17,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average order value for online sales orders?'},
 {'id': 18,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the total discount amount given on delivered orders?'},
 {'id': 19,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the total shipping amount charged on urgent orders?'},
 {'id': 20,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the total quantity ordered for Electronics products?'},
 {'id': 21,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the total quantity shipped on fulfilled order items?'},
 {'id': 22,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the total backordered quantity for Apparel products?'},
 {'id': 23,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the total line revenue from products supplied by manufacturers?'},
 {'id': 24,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average line total for fulfilled items handled by open warehouses?'},
 {'id': 25,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the total standard cost of all ordered units for Outdoors products?'},
 {'id': 26,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the total gross profit on delivered order items, using quantity ordered times unit price minus '
           'unit cost?'},
 {'id': 27,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average order total for customers in the gold loyalty tier?'},
 {'id': 28,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'How many orders were placed by small-business customers?'},
 {'id': 29,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the total line revenue from partner-channel orders?'},
 {'id': 30,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average markup amount between standard cost and list price for products from active '
           'suppliers?'},
 {'id': 31,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'How many products are supplied by high-risk suppliers?'},
 {'id': 32,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the sum of list prices for products from preferred suppliers?'},
 {'id': 33,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average annual operating cost of temperature-controlled warehouses?'},
 {'id': 34,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the total capacity of warehouses with restricted security?'},
 {'id': 35,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average discount percentage on delivered orders, based on discount amount divided by '
           'subtotal?'},
 {'id': 36,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What was the total delivered line revenue from Electronics products bought online by platinum customers in '
           '2025?'},
 {'id': 37,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the total shipped gross profit from products supplied by low-risk suppliers, fulfilled by open '
           'warehouses, and sold on delivered orders?'},
 {'id': 38,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the average line total for products from manufacturers on high-priority orders?'},
 {'id': 39,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the total backordered quantity for products supplied by inactive suppliers?'},
 {'id': 40,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the total tax collected on fulfilled line items from store-channel orders?'},
 {'id': 41,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the total delivered order revenue from active enterprise customers whose orders used Northwest '
           'warehouses?'},
 {'id': 42,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the quantity-weighted average unit price of products on delivered orders?'},
 {'id': 43,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the total line revenue from order items fulfilled by a warehouse different from the order’s '
           'default warehouse?'},
 {'id': 44,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the combined annual revenue of suppliers whose products appeared on delivered orders?'},
 {'id': 45,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'How many distinct customers placed at least one delivered order and at least one cancelled order?'},
 {'id': 46,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the total delivered order revenue from customers whose current balance is greater than their '
           'credit limit?'},
 {'id': 47,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the average quantity shipped per order item for products with warranties of at least 24 months?'},
 {'id': 48,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the total gross profit from non-discontinued products sold through online or partner orders?'},
 {'id': 49,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the total delivered line revenue from products bought by gold or platinum customers?'},
 {'id': 50,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the average number of days between order date and required date for urgent delivered orders?'},
 {'id': 51,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each product with the difference between its list price and standard cost.'},
 {'id': 52,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each product with the discount amount from list price to sale price.'},
 {'id': 53,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each product with its markup percentage from standard cost to list price.'},
 {'id': 54,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each sales order with its discount amount as a percentage of subtotal.'},
 {'id': 55,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each sales order with its tax amount as a percentage of subtotal.'},
 {'id': 56,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each sales order with shipping amount as a percentage of subtotal.'},
 {'id': 57,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each order item with its gross profit per unit.'},
 {'id': 58,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each order item with total gross profit based on quantity ordered.'},
 {'id': 59,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each order item with the percentage of ordered units that were shipped.'},
 {'id': 60,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each order item with the percentage of ordered units that were backordered.'},
 {'id': 61,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each warehouse with its unused capacity percentage.'},
 {'id': 62,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each warehouse with its estimated used capacity units based on utilization percentage.'},
 {'id': 63,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each customer with the percentage of their credit limit currently used.'},
 {'id': 64,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each supplier with payment terms expressed in weeks.'},
 {'id': 65,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each warehouse with annual operating cost per capacity unit.'},
 {'id': 66,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average order value for each sales channel.'},
 {'id': 67,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the percentage of orders that were delivered for each priority level.'},
 {'id': 68,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average order discount percentage for each customer segment.'},
 {'id': 69,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the percentage of customers who opted into marketing for each loyalty tier.'},
 {'id': 70,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the percentage of active suppliers for each supplier type.'},
 {'id': 71,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average product markup percentage for each product category.'},
 {'id': 72,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average gross profit per unit for each product brand.'},
 {'id': 73,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate shipped quantity as a percentage of ordered quantity for each warehouse.'},
 {'id': 74,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the backorder rate for each product category.'},
 {'id': 75,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average line discount percentage for each sales channel.'},
 {'id': 76,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate each product category’s share of total delivered line revenue.'},
 {'id': 77,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average shipping amount as a percentage of subtotal for each sales channel.'},
 {'id': 78,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average customer credit-utilization percentage for each customer segment.'},
 {'id': 79,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average estimated used capacity units for each warehouse region.'},
 {'id': 80,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average annual operating cost per capacity unit for each warehouse region.'},
 {'id': 81,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'For each supplier type, divide total supplier annual revenue by the number of products those suppliers '
           'provide.'},
 {'id': 82,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average delivered line revenue per distinct order for each sales channel.'},
 {'id': 83,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average quantity ordered per distinct order for each product category.'},
 {'id': 84,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average gross profit per order item for each supplier risk level.'},
 {'id': 85,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the percentage of fully fulfilled order items for each product category.'},
 {'id': 86,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each customer, calculate lifetime delivered-order revenue divided by the number of delivered orders.'},
 {'id': 87,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each supplier, calculate total order-item revenue minus total order-item cost for its products.'},
 {'id': 88,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each warehouse, calculate total shipped units per capacity unit.'},
 {'id': 89,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each loyalty tier, calculate delivered-order revenue as a percentage of all order revenue for that '
           'tier.'},
 {'id': 90,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each product category, calculate total gross profit divided by total line revenue.'},
 {'id': 91,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each sales representative, calculate delivered-order revenue per distinct customer served.'},
 {'id': 92,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each supplier, calculate distinct customers reached per non-discontinued product supplied.'},
 {'id': 93,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each warehouse, calculate backordered units as a percentage of ordered units.'},
 {'id': 94,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each customer, calculate revenue from orders with settled payment status as a percentage of all order '
           'revenue.'},
 {'id': 95,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each warehouse region, calculate shipped units divided by total warehouse capacity.'},
 {'id': 96,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each product, calculate total quantity shipped divided by total quantity ordered.'},
 {'id': 97,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each supplier risk level, calculate the percentage of supplied products that are discontinued.'},
 {'id': 98,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each month of 2025, calculate delivered-order revenue growth compared with the previous month.'},
 {'id': 99,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each product category, calculate its share of total delivered line revenue and its share of total '
           'gross profit.'},
 {'id': 100,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each customer, calculate the average number of days from order date to shipped date for orders that '
           'were shipped or delivered.'},
 {'id': 101,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different customer segments are represented?'},
 {'id': 102,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many distinct loyalty tiers do customers have?'},
 {'id': 103,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different customer account statuses are present?'},
 {'id': 104,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many distinct preferred contact methods do customers use?'},
 {'id': 105,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different supplier types are represented?'},
 {'id': 106,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many distinct supplier countries are represented?'},
 {'id': 107,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different supplier risk levels are present?'},
 {'id': 108,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many distinct product categories are in the catalog?'},
 {'id': 109,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different product subcategories are represented?'},
 {'id': 110,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many distinct product brands are available?'},
 {'id': 111,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different product colors are available?'},
 {'id': 112,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many distinct warehouse regions are represented?'},
 {'id': 113, 'category': 'distinct_count', 'difficulty': 'easy', 'query': 'How many different order statuses occur?'},
 {'id': 114, 'category': 'distinct_count', 'difficulty': 'easy', 'query': 'How many distinct sales channels are used?'},
 {'id': 115,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different order priority levels are present?'},
 {'id': 116,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct customers placed at least one order in 2025?'},
 {'id': 117,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct products appeared on delivered orders?'},
 {'id': 118,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct suppliers provide Electronics products?'},
 {'id': 119,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct warehouses fulfilled at least one order item?'},
 {'id': 120,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct customers placed an online order that was delivered?'},
 {'id': 121,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct products had at least one backordered unit?'},
 {'id': 122,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct active suppliers provide at least one product?'},
 {'id': 123,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct brands appeared on delivered orders?'},
 {'id': 124,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct sales representatives handled urgent orders?'},
 {'id': 125,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct warehouses fulfilled Apparel products?'},
 {'id': 126,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct customers placed a gift order?'},
 {'id': 127,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct products received a line discount of at least 15 percent?'},
 {'id': 128,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct supplier countries provided products that were ordered?'},
 {'id': 129,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct warehouses fulfilled items on delivered orders?'},
 {'id': 130,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct customers placed an order whose payment status is settled?'},
 {'id': 131,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct product categories appeared on partner-channel orders?'},
 {'id': 132,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct supplier types had at least one backordered product?'},
 {'id': 133,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct cities contain an open warehouse?'},
 {'id': 134,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct supplier cities provided products on delivered orders?'},
 {'id': 135,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct customers had orders assigned to more than one default warehouse?'},
 {'id': 136,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct customers placed delivered orders in both 2024 and 2025?'},
 {'id': 137,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct products were sold through both online and store channels?'},
 {'id': 138,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct suppliers had products sold on delivered orders during 2025?'},
 {'id': 139,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct customers placed both a delivered order and a cancelled order?'},
 {'id': 140,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct warehouses fulfilled order items for gold customers during 2025?'},
 {'id': 141,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct products were ordered through at least three different sales channels?'},
 {'id': 142,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct suppliers had products fulfilled from at least three different warehouses?'},
 {'id': 143,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct customers had order items fulfilled from more than one warehouse?'},
 {'id': 144,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct product brands were bought by both enterprise and retail customers?'},
 {'id': 145,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct product categories were purchased online by platinum customers?'},
 {'id': 146,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct suppliers had products shipped from warehouses in at least three regions?'},
 {'id': 147,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct customers used more than one default warehouse across their orders?'},
 {'id': 148,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct sales representatives handled delivered orders worth more than 1,000 dollars?'},
 {'id': 149,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct products were ordered in 2025 but not in 2026?'},
 {'id': 150,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct warehouse cities generated more than 10,000 dollars in delivered line revenue?'},
 {'id': 151, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count customers by account status.'},
 {'id': 152, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count customers by loyalty tier.'},
 {'id': 153, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count customers by customer segment.'},
 {'id': 154, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count customers by gender.'},
 {'id': 155, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count customers by preferred contact method.'},
 {'id': 156, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count suppliers by supplier type.'},
 {'id': 157, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count suppliers by risk level.'},
 {'id': 158, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count suppliers by rating.'},
 {'id': 159, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count suppliers by country.'},
 {'id': 160, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count products by category.'},
 {'id': 161, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count products by brand.'},
 {'id': 162, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count products by color.'},
 {'id': 163, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count warehouses by region.'},
 {'id': 164, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count sales orders by order status.'},
 {'id': 165, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count sales orders by sales channel.'},
 {'id': 166, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Show total customer balance by loyalty tier.'},
 {'id': 167,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show average customer credit limit by customer segment.'},
 {'id': 168,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show total supplier annual revenue by supplier type.'},
 {'id': 169, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Show average supplier rating by risk level.'},
 {'id': 170,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show product count and average sale price by category.'},
 {'id': 171,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show the number of discontinued products by brand.'},
 {'id': 172, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Show total warehouse capacity by region.'},
 {'id': 173,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show average warehouse utilization by operating status.'},
 {'id': 174,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show order count and total order revenue by order status.'},
 {'id': 175, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Show average order value by sales channel.'},
 {'id': 176,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show total order discount amount by priority.'},
 {'id': 177, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Show total shipping amount by sales channel.'},
 {'id': 178,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show total quantity ordered by product category.'},
 {'id': 179, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Show total line revenue by product brand.'},
 {'id': 180,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show total backordered quantity by warehouse.'},
 {'id': 181,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show total shipped quantity by line-item fulfillment status.'},
 {'id': 182,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show customer count by account status and customer segment.'},
 {'id': 183, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Show product count by supplier type.'},
 {'id': 184, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Show order count by customer loyalty tier.'},
 {'id': 185,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show delivered line revenue by warehouse region.'},
 {'id': 186,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show delivered line revenue by customer segment and product category.'},
 {'id': 187,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show total gross profit by supplier and product category.'},
 {'id': 188,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show shipped quantity by warehouse region and sales channel.'},
 {'id': 189,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show average order value by customer loyalty tier and order year.'},
 {'id': 190,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show line revenue by supplier risk level and sales channel.'},
 {'id': 191,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show order count and average days from order date to shipped date by warehouse region.'},
 {'id': 192,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show backordered quantity by supplier risk level and warehouse region.'},
 {'id': 193,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show total quantity ordered by sales representative and product category.'},
 {'id': 194,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show average line discount percentage by customer segment and product brand.'},
 {'id': 195,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show delivered line revenue by the order’s default warehouse state and the item fulfillment warehouse '
           'state.'},
 {'id': 196,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show order count and total revenue by customer segment and payment status.'},
 {'id': 197, 'category': 'group_by', 'difficulty': 'hard', 'query': 'Show total order revenue by month for 2025.'},
 {'id': 198,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show product sales revenue by supplier rating and product category.'},
 {'id': 199,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show fulfillment percentage by warehouse and product category.'},
 {'id': 200,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show customer count, order count, and total order revenue by loyalty tier and customer segment.'},
 {'id': 201, 'category': 'having', 'difficulty': 'easy', 'query': 'List loyalty tiers with more than 15 customers.'},
 {'id': 202,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List customer segments with a total current balance above 100,000 dollars.'},
 {'id': 203,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List supplier types represented by more than 10 suppliers.'},
 {'id': 204,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List supplier ratings shared by more than 10 suppliers.'},
 {'id': 205,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List product categories containing more than 15 products.'},
 {'id': 206,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List product brands with an average sale price above 300 dollars.'},
 {'id': 207,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List warehouse regions containing more than 5 warehouses.'},
 {'id': 208, 'category': 'having', 'difficulty': 'easy', 'query': 'List order statuses with more than 15 orders.'},
 {'id': 209,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List sales channels with an average order value above 1,000 dollars.'},
 {'id': 210,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List priority levels with total shipping charges above 500 dollars.'},
 {'id': 211,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List product categories with an average markup percentage above 40 percent.'},
 {'id': 212,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List supplier risk levels with average annual supplier revenue above 5 million dollars.'},
 {'id': 213,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List warehouse security levels with total capacity above 100,000 units.'},
 {'id': 214,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List line-item fulfillment statuses with more than 20 order items.'},
 {'id': 215,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List customer account statuses with an average risk score above 50.'},
 {'id': 216,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List customers whose total order value exceeds 5,000 dollars.'},
 {'id': 217,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List products with more than 20 total units ordered.'},
 {'id': 218,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List suppliers whose products generated more than 10,000 dollars in line revenue.'},
 {'id': 219,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List warehouses whose fulfilled order items generated more than 5,000 dollars in line revenue.'},
 {'id': 220,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List sales representatives who handled more than 3 orders.'},
 {'id': 221,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List customer segments whose delivered-order revenue exceeds 20,000 dollars.'},
 {'id': 222,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List product brands with more than 20 backordered units.'},
 {'id': 223,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List supplier types whose products have an average sale price above 250 dollars.'},
 {'id': 224,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List warehouse regions that fulfilled more than 15 order items.'},
 {'id': 225,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List loyalty tiers whose settled-payment-status order revenue exceeds 20,000 dollars.'},
 {'id': 226,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List customers who placed at least 3 delivered orders.'},
 {'id': 227,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List product categories with more than 25 backordered units.'},
 {'id': 228,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List supplier risk levels with an average supplier rating above 3.'},
 {'id': 229,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List warehouse cities whose default-assigned orders generated more than 1,000 dollars in shipping '
           'charges.'},
 {'id': 230,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List sales channels whose delivered-order revenue exceeds 10,000 dollars.'},
 {'id': 231,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List product categories with an average line total above 500 dollars.'},
 {'id': 232,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List customer segments with an average order value above 1,000 dollars.'},
 {'id': 233,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List suppliers whose products were sold through more than 2 sales channels.'},
 {'id': 234,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List warehouse regions that fulfilled orders for more than 10 distinct customers.'},
 {'id': 235,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List customers whose total order discount amount exceeds 250 dollars.'},
 {'id': 236,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List suppliers whose products generated more than 10,000 dollars in delivered line revenue during 2025.'},
 {'id': 237,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List customers whose delivered-order total is greater than their credit limit.'},
 {'id': 238,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List warehouses whose delivered line revenue is above the average delivered line revenue of warehouses in '
           'the same region.'},
 {'id': 239,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List product categories whose average unit gross profit is above the overall average unit gross profit.'},
 {'id': 240,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List customer segments whose delivered-order rate is above the overall delivered-order rate.'},
 {'id': 241,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List sales representatives who handled more than 5 delivered orders and more than 10,000 dollars in '
           'delivered revenue.'},
 {'id': 242,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List supplier risk levels whose backorder rate is above 10 percent.'},
 {'id': 243,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List warehouse regions whose average utilization is above the overall warehouse average.'},
 {'id': 244,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List products whose total ordered quantity is more than twice their total shipped quantity.'},
 {'id': 245,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List suppliers whose average product sale price is above the overall average product sale price.'},
 {'id': 246,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List customers who ordered products from at least 3 different categories.'},
 {'id': 247,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List warehouses that fulfilled order items for more than 15 distinct customers.'},
 {'id': 248,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List product categories sold through all four sales channels.'},
 {'id': 249,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List loyalty tiers whose average credit-utilization percentage is above 75 percent.'},
 {'id': 250,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List supplier cities whose delivered product revenue is above the average delivered revenue across '
           'supplier cities.'},
 {'id': 251, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each product name with its supplier name.'},
 {'id': 252, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each order number with the customer name.'},
 {'id': 253,
  'category': 'join',
  'difficulty': 'easy',
  'query': 'Show each order number with its default warehouse name.'},
 {'id': 254, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each order item with its order number.'},
 {'id': 255, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each order item with the current product name.'},
 {'id': 256,
  'category': 'join',
  'difficulty': 'easy',
  'query': 'Show each order item with its fulfillment warehouse name.'},
 {'id': 257,
  'category': 'join',
  'difficulty': 'easy',
  'query': 'Show each order number with the customer loyalty tier.'},
 {'id': 258, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each product with its supplier risk level.'},
 {'id': 259,
  'category': 'join',
  'difficulty': 'easy',
  'query': 'Show each warehouse with the order numbers assigned to it.'},
 {'id': 260,
  'category': 'join',
  'difficulty': 'easy',
  'query': 'Show each order item with its order number and product name.'},
 {'id': 261,
  'category': 'join',
  'difficulty': 'easy',
  'query': 'Show each customer name with the statuses of their orders.'},
 {'id': 262, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each product name with the supplier city.'},
 {'id': 263,
  'category': 'join',
  'difficulty': 'easy',
  'query': 'Show each order item with the fulfillment warehouse region.'},
 {'id': 264, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each product name with the supplier rating.'},
 {'id': 265, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each order number with the customer segment.'},
 {'id': 266,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List delivered order numbers with customer names and grand totals.'},
 {'id': 267,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List Electronics products with supplier names and sale prices.'},
 {'id': 268,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List open warehouses with the order numbers assigned to them.'},
 {'id': 269,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List backordered order items with product names and warehouse names.'},
 {'id': 270,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List urgent orders with customer names and default warehouse names.'},
 {'id': 271,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List order items from high-risk suppliers with product names and line totals.'},
 {'id': 272,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List orders from platinum customers with order numbers and grand totals.'},
 {'id': 273,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List discontinued products with their supplier names.'},
 {'id': 274,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List partner-channel order items with order number and product name.'},
 {'id': 275,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List order items fulfilled by a warehouse different from the order’s default warehouse, showing both '
           'warehouse names.'},
 {'id': 276,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List active suppliers with the products they provide.'},
 {'id': 277,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List orders from customers whose current balance is above 75 percent of their credit limit.'},
 {'id': 278,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List orders assigned to warehouses currently under maintenance.'},
 {'id': 279,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List order items where the recorded unit price differs from the current product sale price.'},
 {'id': 280,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List suppliers and the products they provide with a standard cost above 100 dollars.'},
 {'id': 281,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List customer names with the products they ordered.'},
 {'id': 282,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List delivered order items with product names and fulfillment warehouse names.'},
 {'id': 283, 'category': 'join', 'difficulty': 'moderate', 'query': 'List gift orders with customer names.'},
 {'id': 284,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List delivered order items for products supplied by manufacturers.'},
 {'id': 285,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List temperature-controlled warehouses with the fulfilled order items they handled.'},
 {'id': 286,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List customers whose order’s default warehouse city matches the supplier city of a product on that order.'},
 {'id': 287,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List order items fulfilled by a different warehouse than the order’s default warehouse, showing customer, '
           'product, and both warehouse names.'},
 {'id': 288,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List each order item with order number, customer name, product name, supplier name, and warehouse name.'},
 {'id': 289,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List products whose supplier state matches the state of a warehouse that fulfilled the product.'},
 {'id': 290,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List delivered order items with customer segment, product category, supplier type, and warehouse region.'},
 {'id': 291,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List order items whose unit price is lower than the product’s current sale price.'},
 {'id': 292,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List customers whose current balance is greater than at least one of their order totals.'},
 {'id': 293,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List products from inactive suppliers that still appeared on delivered orders.'},
 {'id': 294,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List suppliers and warehouses connected through fulfilled sales of the supplier’s products.'},
 {'id': 295,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List order items where both the supplier and fulfillment warehouse are in the same state.'},
 {'id': 296,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List delivered orders with product category, supplier type, and warehouse security level.'},
 {'id': 297,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List urgent orders with customer, product, and supplier details.'},
 {'id': 298,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List backordered items from preferred suppliers that were assigned to open warehouses.'},
 {'id': 299,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List delivered store orders from gold customers that included products from manufacturers.'},
 {'id': 300,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List orders where at least one item was fulfilled from the order’s default warehouse and at least one '
           'other item was fulfilled elsewhere.'},
 {'id': 301,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each order number with customer name and product name.'},
 {'id': 302,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each order item with product name and supplier name.'},
 {'id': 303,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each order item with order number and warehouse name.'},
 {'id': 304,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each sales order with customer name and default warehouse name.'},
 {'id': 305,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each product with supplier name and any order item where it appeared.'},
 {'id': 306,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each delivered order with customer name and product names.'},
 {'id': 307,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each order item with product name, supplier name, and warehouse name.'},
 {'id': 308,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each order item with customer name and product name.'},
 {'id': 309,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each sales order with customer name and warehouse manager name.'},
 {'id': 310,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each product with order number and customer name for orders containing it.'},
 {'id': 311,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each line item with order number, customer name, and warehouse name.'},
 {'id': 312,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each delivered line item with product name and supplier name.'},
 {'id': 313,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each customer with order number and product category purchased.'},
 {'id': 314,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each supplier with product names and warehouses that fulfilled those products.'},
 {'id': 315,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each warehouse with order numbers and customer names for assigned orders.'},
 {'id': 316,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List delivered orders with customer name, product name, quantity ordered, and line total.'},
 {'id': 317,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List gold customers with delivered order numbers and product names.'},
 {'id': 318,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List Electronics products sold through online orders with customer names.'},
 {'id': 319,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List backordered items with order number, product name, supplier name, and warehouse name.'},
 {'id': 320,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List delivered order items fulfilled in Washington with customer name and product name.'},
 {'id': 321,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List orders with settled payment status, including customer name and product name.'},
 {'id': 322,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List urgent orders with customer name, product name, and supplier name.'},
 {'id': 323,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List products from high-risk suppliers with warehouse name and quantity shipped.'},
 {'id': 324,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List delivered order items handled by temperature-controlled warehouses.'},
 {'id': 325,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List customer names, order numbers, payment statuses, and line-item fulfillment statuses.'},
 {'id': 326,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List refunded orders with customer segment and product name.'},
 {'id': 327,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List Apparel order items with supplier name, customer name, and quantity shipped.'},
 {'id': 328,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List delivered Outdoors items with warehouse name and region.'},
 {'id': 329,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List supplier names with product names and total line revenue by warehouse.'},
 {'id': 330,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List enterprise customers with order numbers, default warehouse state, and item warehouse state.'},
 {'id': 331,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List partially fulfilled items from open warehouses with product and customer names.'},
 {'id': 332,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List discontinued products that were ordered, with supplier and fulfillment warehouse.'},
 {'id': 333,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List sales representatives with customers and products on the orders they handled.'},
 {'id': 334,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List gift orders with customer, product, and supplier names.'},
 {'id': 335,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List preferred suppliers with products sold through the partner channel.'},
 {'id': 336,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List customers who placed delivered online orders for Electronics products, with order, product, supplier, '
           'and warehouse.'},
 {'id': 337,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List high-risk suppliers whose products appeared on refunded orders, with customer and line total.'},
 {'id': 338,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List orders whose item warehouse matches the default warehouse, with customer, product, and supplier.'},
 {'id': 339,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List sales representatives who handled platinum customers’ delivered orders, with product category and '
           'line revenue.'},
 {'id': 340,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List products with more than 20 total ordered units, together with supplier and fulfillment warehouses.'},
 {'id': 341,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List orders where supplier state, item warehouse state, and default warehouse state are all different.'},
 {'id': 342,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List delivered order items handled by maintenance-status warehouses, with customer, product, and '
           'supplier.'},
 {'id': 343,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List products from rating-1 suppliers that generated delivered line revenue in 2025, summarized by '
           'warehouse.'},
 {'id': 344,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List suppliers whose products were bought by both enterprise and retail customers.'},
 {'id': 345,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List customers who ordered through more than one sales channel and bought from more than one supplier.'},
 {'id': 346,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List orders containing products from at least two suppliers, with customer and default warehouse.'},
 {'id': 347,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List discontinued products sold in 2025, with supplier and fulfillment warehouse.'},
 {'id': 348,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List customers who bought products from high-risk suppliers on orders that were later refunded.'},
 {'id': 349,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List warehouses that fulfilled online orders for gold customers, with product and supplier.'},
 {'id': 350,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List suppliers whose products were fulfilled from both open and maintenance-status warehouses.'},
 {'id': 351,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 5 customers with the highest current balance.'},
 {'id': 352,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 customers with the highest credit limits.'},
 {'id': 353,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 5 active customers with the lowest risk scores.'},
 {'id': 354,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 5 suppliers with the highest annual revenue.'},
 {'id': 355,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 5 suppliers with the longest payment terms.'},
 {'id': 356,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 most expensive products by list price.'},
 {'id': 357,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 least expensive products by sale price.'},
 {'id': 358, 'category': 'order_limit_topk', 'difficulty': 'easy', 'query': 'Show the 10 heaviest products.'},
 {'id': 359,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 5 warehouses with the largest capacity.'},
 {'id': 360,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 5 warehouses with the highest utilization percentage.'},
 {'id': 361,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 5 warehouses with the highest annual operating cost.'},
 {'id': 362,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 largest sales orders by grand total.'},
 {'id': 363,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 orders with the largest discount amounts.'},
 {'id': 364,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 orders with the largest shipping amounts.'},
 {'id': 365,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 order items with the largest line totals.'},
 {'id': 366,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 customers by total order value.'},
 {'id': 367,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 products by total quantity ordered.'},
 {'id': 368,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 5 suppliers by total line revenue from their products.'},
 {'id': 369,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 5 warehouses by total fulfilled line revenue.'},
 {'id': 370,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 sales representatives by total order revenue handled.'},
 {'id': 371,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 5 product categories by delivered line revenue.'},
 {'id': 372,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 5 product brands by total quantity shipped.'},
 {'id': 373,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the bottom 5 warehouses by total shipped quantity.'},
 {'id': 374,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 customers by total order discount amount.'},
 {'id': 375,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 products by total gross profit.'},
 {'id': 376,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show supplier types ranked by average annual supplier revenue.'},
 {'id': 377,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 warehouse cities by number of assigned orders.'},
 {'id': 378,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show loyalty tiers ranked by revenue from orders with settled payment status.'},
 {'id': 379,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 products by number of distinct warehouses that fulfilled them.'},
 {'id': 380,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 5 customer segments by average order value.'},
 {'id': 381,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the 10 orders with the highest total quantity across their line items.'},
 {'id': 382,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 5 product brands by total line revenue.'},
 {'id': 383,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 customers by number of delivered orders.'},
 {'id': 384,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 5 warehouse regions by delivered line revenue.'},
 {'id': 385,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the 10 suppliers with the highest average product sale price.'},
 {'id': 386,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 products by delivered line revenue within each product category.'},
 {'id': 387,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 5 customers by delivered-order revenue within each loyalty tier.'},
 {'id': 388,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the highest-revenue sales representative within each sales channel.'},
 {'id': 389,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 warehouses by shipped quantity within each region.'},
 {'id': 390,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 5 suppliers by gross profit from delivered orders in 2025.'},
 {'id': 391,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the 10 products with the greatest gap between ordered quantity and shipped quantity.'},
 {'id': 392,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 product brands by delivered line revenue within each category.'},
 {'id': 393,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the 5 customers with the highest delivered revenue per delivered order.'},
 {'id': 394,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 product categories by gross margin percentage.'},
 {'id': 395,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 5 suppliers by shipped quantity as a percentage of ordered quantity.'},
 {'id': 396,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 warehouses by utilization within each security level.'},
 {'id': 397,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the 10 discontinued products with the highest line revenue.'},
 {'id': 398,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 5 suppliers by number of distinct customers who bought their products.'},
 {'id': 399,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 months of 2025 by delivered-order revenue.'},
 {'id': 400,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 5 warehouse regions by gross profit per shipped unit.'},
 {'id': 401,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List customers who have either a pending order or a delivered order.'},
 {'id': 402,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List products that belong to either Electronics or Apparel.'},
 {'id': 403,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List suppliers located in either Washington or Idaho.'},
 {'id': 404,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List warehouses that are either open or under maintenance.'},
 {'id': 405,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List orders placed through either the online or store channel.'},
 {'id': 406,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List products that are either discontinued or have no warranty.'},
 {'id': 407,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List customers in either the gold or platinum loyalty tier.'},
 {'id': 408,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List suppliers that are either preferred or rated 5.'},
 {'id': 409,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List warehouses that are either temperature-controlled or hazmat-certified.'},
 {'id': 410,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List order items that are either partially fulfilled or unfulfilled.'},
 {'id': 411,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List products whose color is either black or white.'},
 {'id': 412,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List orders whose priority is either urgent or high.'},
 {'id': 413,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List suppliers that are either manufacturers or importers.'},
 {'id': 414,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List products that appeared on either delivered orders or cancelled orders.'},
 {'id': 415,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List customers whose account is either active or suspended.'},
 {'id': 416,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List customers who placed orders in both 2024 and 2025.'},
 {'id': 417,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List products sold through both online and store channels.'},
 {'id': 418,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List customers who have both a delivered order and an order with refunded payment status.'},
 {'id': 419,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List warehouses used both as an order’s default warehouse and as an item fulfillment warehouse.'},
 {'id': 420,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List products that have at least one fully fulfilled line item and at least one backordered line item.'},
 {'id': 421,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List suppliers that provide products in both Electronics and Outdoors.'},
 {'id': 422,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List cities that contain both a supplier and a warehouse.'},
 {'id': 423,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List suppliers whose products appeared on both delivered and cancelled orders.'},
 {'id': 424,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List orders that have line items but no fully fulfilled line items.'},
 {'id': 425,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List products that were ordered but never appeared on a delivered order.'},
 {'id': 426,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List customers with an order whose payment status is settled but no delivered orders.'},
 {'id': 427,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List warehouses that fulfilled order items but never fulfilled an item on a delivered order.'},
 {'id': 428,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List products sold online but never sold through the store channel.'},
 {'id': 429,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List customers who ordered Electronics but never ordered Apparel.'},
 {'id': 430,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List suppliers with non-discontinued products but no products on delivered orders.'},
 {'id': 431,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List products sold through the partner channel but never through the phone channel.'},
 {'id': 432,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List customers who placed urgent orders but never placed a cancelled order.'},
 {'id': 433,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List warehouse regions that fulfilled delivered items but never handled a backordered item.'},
 {'id': 434,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List product categories sold in 2025 but not in 2024.'},
 {'id': 435,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List customers who placed a gift order but never had an order with refunded payment status.'},
 {'id': 436,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List customers who bought both Electronics and Outdoors products but never bought Apparel.'},
 {'id': 437,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List products sold to both gold and platinum customers but not to bronze customers.'},
 {'id': 438,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List suppliers whose products were sold through both online and partner channels but never through store '
           'orders.'},
 {'id': 439,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List warehouses that fulfilled items for both gold and platinum customers but never for bronze customers.'},
 {'id': 440,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List sales representatives who handled both delivered and cancelled orders but never handled an urgent '
           'order.'},
 {'id': 441,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List customers who ordered through both online and store channels but never through the phone channel.'},
 {'id': 442,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List products fulfilled from both Northwest and Southwest warehouses but never from Northeast warehouses.'},
 {'id': 443,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List suppliers that provide both discontinued and non-discontinued products but no Electronics products.'},
 {'id': 444,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List customer segments that generated orders in both 2024 and 2025 but not in 2026.'},
 {'id': 445,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List product categories supplied by both high-risk and low-risk suppliers but not by medium-risk '
           'suppliers.'},
 {'id': 446,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List warehouse regions that handled both fulfilled and partially fulfilled items but no unfulfilled '
           'items.'},
 {'id': 447,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List customers who had orders with both settled and refunded payment statuses but no failed payment '
           'status.'},
 {'id': 448,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List suppliers whose products were both backordered and sold on delivered orders but never sold on '
           'cancelled orders.'},
 {'id': 449,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List warehouse regions that handled both Electronics and Apparel items but no Home items.'},
 {'id': 450,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List products sold in both 2024 and 2025 but not in 2026.'},
 {'id': 451,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List products priced above the overall average sale price.'},
 {'id': 452,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List suppliers whose annual revenue is above the overall supplier average.'},
 {'id': 453,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List customers whose current balance is above the average customer balance.'},
 {'id': 454,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List warehouses with utilization above the average warehouse utilization.'},
 {'id': 455,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List sales orders larger than the average sales order value.'},
 {'id': 456,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List order items with line totals above the average line total.'},
 {'id': 457,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List products that have never appeared on a sales order.'},
 {'id': 458,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List customers who have never placed a sales order.'},
 {'id': 459,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List suppliers that provide no discontinued products.'},
 {'id': 460,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List warehouses that have never fulfilled an order item.'},
 {'id': 461,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List products that have been ordered but never had any quantity shipped.'},
 {'id': 462,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List customers who have never placed a delivered order.'},
 {'id': 463,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List sales orders that contain no line items.'},
 {'id': 464,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List warehouses that have never been used as an order’s default warehouse.'},
 {'id': 465,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List suppliers whose products have never had a backordered unit.'},
 {'id': 466,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List products priced above the average sale price for their category.'},
 {'id': 467,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List suppliers whose rating is above the average rating for their supplier type.'},
 {'id': 468,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List customers whose total order value is above the average customer total order value.'},
 {'id': 469,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List warehouses whose total shipped quantity is above the average shipped quantity across warehouses.'},
 {'id': 470,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List suppliers that have at least one product priced above the overall average product sale price.'},
 {'id': 471,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List sales orders larger than the average order placed by the same customer.'},
 {'id': 472,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List order items whose unit price is above the average unit price for the same product.'},
 {'id': 473,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List warehouses whose utilization is above the average for their region.'},
 {'id': 474,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List products whose total ordered quantity is greater than their total shipped quantity.'},
 {'id': 475,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List customers whose most recent order is a delivered order.'},
 {'id': 476,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List sales representatives who handled more orders than the average representative who handled an order.'},
 {'id': 477,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List product categories whose delivered line revenue is above the average delivered revenue across '
           'categories.'},
 {'id': 478,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List customers who placed at least one order but have no order with settled payment status.'},
 {'id': 479,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List products that were fulfilled from every open warehouse.'},
 {'id': 480,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List suppliers for whom every supplied product is non-discontinued.'},
 {'id': 481,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List warehouses where every default-assigned order was either shipped or delivered.'},
 {'id': 482,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List orders containing at least one product priced above the average price of its category.'},
 {'id': 483,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List customers whose total discount amount is greater than the average customer discount total.'},
 {'id': 484,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List suppliers whose products were sold through every sales channel.'},
 {'id': 485,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List products whose latest order date is later than the average latest-order date across products.'},
 {'id': 486,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List the highest-revenue product in each product category.'},
 {'id': 487,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List the supplier with the highest annual revenue in each supplier type.'},
 {'id': 488,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List the largest sales order for each customer.'},
 {'id': 489,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List the most recent sales order for each customer.'},
 {'id': 490,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List customers whose delivered-order revenue is above the average delivered revenue for their loyalty '
           'tier.'},
 {'id': 491,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List suppliers whose product revenue is above the average supplier revenue within the same supplier type.'},
 {'id': 492,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List warehouses whose backordered-item count is above the average for warehouses in the same region.'},
 {'id': 493,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List products whose gross margin percentage is above the category average and whose line revenue is also '
           'above the category average.'},
 {'id': 494,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List sales representatives whose delivered revenue is above the average representative revenue for their '
           'sales channel.'},
 {'id': 495,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List customers who ordered every product category that appears on any delivered order.'},
 {'id': 496,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List suppliers for whom every supplied product has been ordered at least once.'},
 {'id': 497,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List warehouses that fulfilled at least one item from every product category.'},
 {'id': 498,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List customers whose order value increased across each of their three most recent orders.'},
 {'id': 499,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List products whose 2025 line revenue exceeded their 2024 line revenue and whose 2026 revenue has not '
           'exceeded 2025.'},
 {'id': 500,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List warehouses whose utilization is above the overall warehouse average and whose operating cost per '
           'capacity unit is below the overall average.'}]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run 500 fixed sales-database natural-language queries against SpiderSQL."
    )
    parser.add_argument(
        "--database-id",
        type=int,
        default=54,
        help="SpiderSQL database ID. Defaults to the uploaded sales database ID 54.",
    )
    parser.add_argument(
        "--base-url",
        default="http://127.0.0.1:8000",
        help="SpiderSQL backend base URL.",
    )
    parser.add_argument(
        "--output",
        default="sales_db54_500_query_sql_results.txt",
        help="Single TXT output file containing each query and its generated SQL.",
    )
    parser.add_argument(
        "--timeout",
        type=int,
        default=180,
        help="Per-query HTTP timeout in seconds.",
    )
    parser.add_argument(
        "--start-index",
        type=int,
        default=1,
        help="Start at this 1-based test number. Useful after an interrupted run.",
    )
    parser.add_argument(
        "--end-index",
        type=int,
        default=len(TEST_CASES),
        help="Stop at this 1-based test number.",
    )
    return parser.parse_args()


def _trace_headers(trace_meta: dict[str, str] | None) -> dict[str, str]:
    """Emit the optional X-SpiderSQL-* diagnostic headers so full-trace runs
    capture per-test metadata (test id / category / difficulty / trace run).
    No-op ({}) when trace_meta is None. Only sent when values are present."""
    if not trace_meta:
        return {}
    name = {"test_id": "X-SpiderSQL-Test-ID", "category": "X-SpiderSQL-Category",
            "difficulty": "X-SpiderSQL-Difficulty", "trace_run": "X-SpiderSQL-Trace-Run"}
    return {name[k]: str(v) for k, v in trace_meta.items() if k in name and v}


def post_query(base_url: str, database_id: int, question: str, timeout: int, trace_meta: dict[str, str] | None = None) -> tuple[int, dict[str, Any]]:
    url = f"{base_url.rstrip('/')}/database/{database_id}/execute_sql"
    request_body = json.dumps({"question": question}).encode("utf-8")
    request = urllib.request.Request(
        url,
        data=request_body,
        headers={"Content-Type": "application/json", "Accept": "application/json",
                 **_trace_headers(trace_meta)},
        method="POST",
    )

    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            status_code = response.getcode()
            raw = response.read().decode("utf-8", errors="replace")
    except urllib.error.HTTPError as exc:
        status_code = exc.code
        raw = exc.read().decode("utf-8", errors="replace")
    except Exception as exc:
        return 0, {"success": False, "_client_error": str(exc)}

    try:
        payload = json.loads(raw) if raw.strip() else {}
    except json.JSONDecodeError:
        payload = {"success": False, "_raw_response": raw}

    if not isinstance(payload, dict):
        payload = {"success": False, "_raw_response": payload}

    return status_code, payload


def extract_sql(payload: dict[str, Any]) -> str:
    generated = payload.get("generated_sql")

    if isinstance(generated, dict):
        for key in ("sql", "query", "generated_sql"):
            value = generated.get(key)
            if isinstance(value, str) and value.strip():
                return value.strip()

    if isinstance(generated, str) and generated.strip():
        return generated.strip()

    for key in ("sql", "query_sql", "final_sql"):
        value = payload.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()

    execution = payload.get("execution")
    if isinstance(execution, dict):
        for key in ("sql", "executed_sql"):
            value = execution.get(key)
            if isinstance(value, str) and value.strip():
                return value.strip()

    return ""


def execution_succeeded(http_status: int, payload: dict[str, Any]) -> bool:
    if http_status < 200 or http_status >= 300:
        return False

    top_level = payload.get("success")
    execution = payload.get("execution")

    if top_level is False:
        return False

    if isinstance(execution, dict) and execution.get("success") is False:
        return False

    if top_level is True:
        return True

    if isinstance(execution, dict) and execution.get("success") is True:
        return True

    return False


def format_record(case: dict[str, Any], status: str, sql: str) -> str:
    displayed_sql = sql if sql else "<NO SQL GENERATED>"
    separator = "=" * 100
    return (
        f"{separator}\n"
        f"TEST {case['id']:03d}\n"
        f"CATEGORY: {case['category']}\n"
        f"DIFFICULTY: {case['difficulty']}\n"
        f"STATUS: {status}\n"
        f"QUERY:\n{case['query']}\n"
        f"SQL:\n{displayed_sql}\n"
    )


def main() -> int:
    args = parse_args()

    if args.start_index < 1 or args.end_index > len(TEST_CASES) or args.start_index > args.end_index:
        print(
            f"Invalid range. Use 1 <= start-index <= end-index <= {len(TEST_CASES)}.",
            file=sys.stderr,
        )
        return 2

    selected_cases = [
        case for case in TEST_CASES
        if args.start_index <= case["id"] <= args.end_index
    ]

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    file_mode = "w" if args.start_index == 1 else "a"

    pass_count = 0
    fail_count = 0
    run_started = time.time()

    with output_path.open(file_mode, encoding="utf-8") as output:
        for position, case in enumerate(selected_cases, start=1):
            http_status, payload = post_query(
                base_url=args.base_url,
                database_id=args.database_id,
                question=case["query"],
                timeout=args.timeout,
                trace_meta={
                    "test_id": str(case.get("id", position)),
                    "category": case.get("category"),
                    "difficulty": case.get("difficulty"),
                    "trace_run": getattr(args, "trace_run", None),
                },
            )

            sql = extract_sql(payload)
            passed = execution_succeeded(http_status, payload)
            status = "PASS" if passed else "FAIL"

            if passed:
                pass_count += 1
            else:
                fail_count += 1

            print(
                f"[{position:03d}/{len(selected_cases):03d}] "
                f"{status} | TEST {case['id']:03d} | "
                f"{case['category']} | {case['difficulty']}",
                flush=True,
            )

            output.write(format_record(case, status, sql))
            output.flush()

    elapsed = time.time() - run_started
    print("-" * 100)
    print(f"Completed: {len(selected_cases)}")
    print(f"PASS: {pass_count}")
    print(f"FAIL: {fail_count}")
    print(f"Elapsed seconds: {elapsed:.1f}")
    print(f"TXT output: {output_path.resolve()}")

    return 0 if fail_count == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
