"""
Students database 500-query SpiderSQL execution test.

This file contains 500 fixed, normal natural-language queries for the
eight-table students database (database ID 55):

- departments
- programs
- instructors
- students
- courses
- academic_advising
- enrollments
- attendance_records

The queries follow only the finalized relationships:

- programs.department_id -> departments.department_id
- instructors.department_id -> departments.department_id
- students.program_id -> programs.program_id
- students.advisor_instructor_id -> instructors.instructor_id
- courses.department_id -> departments.department_id
- courses.program_id -> programs.program_id
- courses.instructor_id -> instructors.instructor_id
- courses.prerequisite_course_id -> courses.course_id
- academic_advising.student_id -> students.student_id
- academic_advising.instructor_id -> instructors.instructor_id
- academic_advising.program_id -> programs.program_id
- enrollments.student_id -> students.student_id
- enrollments.course_id -> courses.course_id
- enrollments.instructor_id -> instructors.instructor_id
- attendance_records.enrollment_id -> enrollments.enrollment_id
- attendance_records.student_id -> students.student_id
- attendance_records.course_id -> courses.course_id
- attendance_records.instructor_id -> instructors.instructor_id

Organization:
- 10 SQL/query categories
- 50 queries per category
- 15 easy, 20 moderate, and 15 hard queries per category

The file does not contain expected/reference SQL. At runtime it sends each
fixed natural-language query to SpiderSQL, prints PASS or FAIL, and writes
the generated SQL and query details to one TXT file.

Example:
    python students_db55_500_test_run.py

Optional:
    python students_db55_500_test_run.py --database-id 55 \
        --base-url http://127.0.0.1:8000 \
        --output students_db55_500_query_sql_results.txt \
        --timeout 180
"""

from __future__ import annotations

import argparse
import json
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any


TEST_CASES = [{'id': 1, 'category': 'aggregation', 'difficulty': 'easy', 'query': 'How many students currently have active status?'},
 {'id': 2,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the average cumulative GPA across all students?'},
 {'id': 3,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the highest number of credits earned by any student?'},
 {'id': 4, 'category': 'aggregation', 'difficulty': 'easy', 'query': 'How many departments are currently active?'},
 {'id': 5,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the combined annual budget of all departments?'},
 {'id': 6,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the average faculty count across departments?'},
 {'id': 7, 'category': 'aggregation', 'difficulty': 'easy', 'query': 'How many instructors are employed full time?'},
 {'id': 8, 'category': 'aggregation', 'difficulty': 'easy', 'query': 'What is the average salary of all instructors?'},
 {'id': 9,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the highest performance rating among instructors?'},
 {'id': 10, 'category': 'aggregation', 'difficulty': 'easy', 'query': 'How many programs are delivered online?'},
 {'id': 11,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the average tuition per credit across all programs?'},
 {'id': 12, 'category': 'aggregation', 'difficulty': 'easy', 'query': 'How many courses are currently active?'},
 {'id': 13,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the total enrollment count recorded across all courses?'},
 {'id': 14, 'category': 'aggregation', 'difficulty': 'easy', 'query': 'How many enrollments have completed status?'},
 {'id': 15,
  'category': 'aggregation',
  'difficulty': 'easy',
  'query': 'What is the average attendance percentage across all enrollment records?'},
 {'id': 16,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'How many active students are enrolled in bachelor programs?'},
 {'id': 17,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average GPA of international students?'},
 {'id': 18,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the total number of credits earned by students receiving financial aid?'},
 {'id': 19,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'How many students are expected to graduate in 2027?'},
 {'id': 20,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average annual budget of accredited departments?'},
 {'id': 21,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the combined student count of departments on the main campus?'},
 {'id': 22,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average salary of tenured instructors?'},
 {'id': 23,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'How many instructors hired after 2020 are still active?'},
 {'id': 24,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average performance rating of instructors researching artificial intelligence?'},
 {'id': 25,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the total current enrollment across active master programs?'},
 {'id': 26,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average application fee for hybrid programs?'},
 {'id': 27,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'How many courses offered in 2025 use online delivery?'},
 {'id': 28,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average course capacity for graduate-level courses?'},
 {'id': 29,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the total tuition amount across completed enrollments?'},
 {'id': 30,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average numeric grade for completed letter-graded enrollments?'},
 {'id': 31,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'How many advising appointments were completed?'},
 {'id': 32,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average advising satisfaction score for career appointments?'},
 {'id': 33,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'How many attendance records were marked absent?'},
 {'id': 34,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the average number of minutes late among late attendance records?'},
 {'id': 35,
  'category': 'aggregation',
  'difficulty': 'moderate',
  'query': 'What is the total participation score recorded for seminar sessions?'},
 {'id': 36,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the average GPA of active students in online bachelor programs?'},
 {'id': 37,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'How many students in accredited departments are currently on leave?'},
 {'id': 38,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the total tuition charged to students in master programs during 2025 enrollments?'},
 {'id': 39,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the average scholarship amount for international students with completed enrollments?'},
 {'id': 40,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'How many active students have an advisor whose performance rating is above 4?'},
 {'id': 41,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the average salary of instructors teaching active courses with more than 100 enrolled students?'},
 {'id': 42,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the total number of credits earned in courses offered by departments in the College of '
           'Engineering?'},
 {'id': 43,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'How many completed enrollments belong to courses taught by tenured instructors?'},
 {'id': 44,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the average numeric grade for students whose advising risk level is high?'},
 {'id': 45,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the total advising time spent with students in doctorate programs?'},
 {'id': 46,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'How many absent attendance records belong to students receiving financial aid?'},
 {'id': 47,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the average quiz score for attendance records in courses delivered online?'},
 {'id': 48,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the total tuition amount for students whose cumulative GPA is above 3.5?'},
 {'id': 49,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'How many students completed courses that required a prerequisite?'},
 {'id': 50,
  'category': 'aggregation',
  'difficulty': 'hard',
  'query': 'What is the average attendance percentage for active students in programs requiring internships?'},
 {'id': 51,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each department with the number of employees formed by adding its faculty count and staff count.'},
 {'id': 52,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each department with its annual budget per enrolled department student.'},
 {'id': 53,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each program with the number of remaining seats based on capacity minus current enrollment.'},
 {'id': 54,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each program with its estimated total tuition based on total credits times tuition per credit.'},
 {'id': 55,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each program with its average credits per year based on total credits divided by duration.'},
 {'id': 56,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each instructor with their salary per year of service since the hire date.'},
 {'id': 57,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each instructor with a salary-adjusted performance value based on salary divided by performance '
           'rating.'},
 {'id': 58,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each student with the number of credits still needed to reach 120 credits.'},
 {'id': 59,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each student with the percentage of 120 credits they have completed.'},
 {'id': 60,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each course with the number of open seats based on capacity minus enrolled count.'},
 {'id': 61,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each course with its enrollment percentage based on enrolled count divided by capacity.'},
 {'id': 62,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each enrollment with the unpaid tuition amount after subtracting scholarship amount.'},
 {'id': 63,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each enrollment with the percentage of attempted credits that were earned.'},
 {'id': 64,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each attendance record with the percentage of scheduled participation points earned out of 10.'},
 {'id': 65,
  'category': 'derived_metric',
  'difficulty': 'easy',
  'query': 'Show each advising appointment with its satisfaction score per 15 minutes of meeting time.'},
 {'id': 66,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the percentage of active students for each program.'},
 {'id': 67,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average credits earned for each student year level.'},
 {'id': 68,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the percentage of students receiving financial aid for each degree level.'},
 {'id': 69,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average GPA for each citizenship status.'},
 {'id': 70,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the percentage of active departments for each campus.'},
 {'id': 71,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average department budget per reported student for each school.'},
 {'id': 72,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average instructor salary for each academic rank.'},
 {'id': 73,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the percentage of tenured instructors for each department.'},
 {'id': 74,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average instructor performance rating for each research area.'},
 {'id': 75,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the capacity utilization percentage for each program.'},
 {'id': 76,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average estimated total tuition for each degree level.'},
 {'id': 77,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the seat utilization percentage for each course delivery mode.'},
 {'id': 78,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average earned-credit rate for each enrollment status.'},
 {'id': 79,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average scholarship as a percentage of tuition for each program.'},
 {'id': 80,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the completed-advising rate for each appointment type.'},
 {'id': 81,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the referral rate for each academic risk level.'},
 {'id': 82,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the attendance rate for each course using present, late, and excused records as attended.'},
 {'id': 83,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average lateness in minutes for each course.'},
 {'id': 84,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the average quiz score per participation point for each session type.'},
 {'id': 85,
  'category': 'derived_metric',
  'difficulty': 'moderate',
  'query': 'Calculate the percentage of enrollment records with attendance above 90 percent for each instructor.'},
 {'id': 86,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each department, calculate total instructor payroll as a percentage of the department annual budget.'},
 {'id': 87,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': "For each program, calculate total student credits earned divided by the program's current enrollment."},
 {'id': 88,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each program, calculate completed course credits as a percentage of all attempted course credits.'},
 {'id': 89,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each instructor, calculate the average numeric grade of their students divided by their performance '
           'rating.'},
 {'id': 90,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each instructor, calculate completed enrollments per active course taught.'},
 {'id': 91,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each student, calculate total scholarship received as a percentage of total tuition charged.'},
 {'id': 92,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each student, calculate completed credits per advising appointment.'},
 {'id': 93,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each student, calculate attended class sessions as a percentage of all recorded class sessions.'},
 {'id': 94,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each department, calculate active student count per active instructor.'},
 {'id': 95,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each department, calculate course seat utilization using total enrolled count divided by total '
           'capacity.'},
 {'id': 96,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each degree level, calculate completed enrollment tuition as a percentage of all enrollment tuition.'},
 {'id': 97,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each course, calculate average numeric grade per credit hour.'},
 {'id': 98,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each course, calculate average participation points as a percentage of the maximum possible points.'},
 {'id': 99,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each academic risk level, calculate completed advising appointments per referred appointment.'},
 {'id': 100,
  'category': 'derived_metric',
  'difficulty': 'hard',
  'query': 'For each program, calculate the share of all active students who belong to that program.'},
 {'id': 101,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different student status values are represented?'},
 {'id': 102,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many distinct citizenship statuses do students have?'},
 {'id': 103,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different housing statuses appear among students?'},
 {'id': 104,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many distinct schools are represented by departments?'},
 {'id': 105,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different campus codes appear in departments?'},
 {'id': 106,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many distinct research areas are represented by instructors?'},
 {'id': 107,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different academic ranks are used by instructors?'},
 {'id': 108,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many distinct degree levels are offered by programs?'},
 {'id': 109,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different program delivery modes are available?'},
 {'id': 110,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many distinct course levels appear in the course catalog?'},
 {'id': 111,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different semesters are represented by courses?'},
 {'id': 112,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many distinct enrollment statuses appear?'},
 {'id': 113,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different grading options are used?'},
 {'id': 114,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many distinct advising appointment types are recorded?'},
 {'id': 115,
  'category': 'distinct_count',
  'difficulty': 'easy',
  'query': 'How many different attendance statuses appear?'},
 {'id': 116,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct students have at least one completed enrollment?'},
 {'id': 117,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct courses have at least one completed enrollment?'},
 {'id': 118,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct instructors teach active courses?'},
 {'id': 119,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct departments offer online courses?'},
 {'id': 120,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct programs currently have active students?'},
 {'id': 121,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct students have received academic advising?'},
 {'id': 122,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct instructors have conducted advising appointments?'},
 {'id': 123,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct students have at least one absent attendance record?'},
 {'id': 124,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct courses recorded a late student?'},
 {'id': 125,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct students completed a course with a numeric grade above 90?'},
 {'id': 126,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct departments employ tenured instructors?'},
 {'id': 127,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct programs require internships?'},
 {'id': 128,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct courses have a prerequisite?'},
 {'id': 129,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct students are enrolled in courses taught by their academic advisor?'},
 {'id': 130,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct instructors taught students receiving financial aid?'},
 {'id': 131,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct departments have students with a GPA above 3.5?'},
 {'id': 132,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct programs had completed enrollments during 2025?'},
 {'id': 133,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct students attended seminar sessions?'},
 {'id': 134,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct courses have enrollment above 100 students?'},
 {'id': 135,
  'category': 'distinct_count',
  'difficulty': 'moderate',
  'query': 'How many distinct instructors have students with attendance below 60 percent?'},
 {'id': 136,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct students have completed courses in both 2024 and 2025?'},
 {'id': 137,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct students have taken both online and in-person courses?'},
 {'id': 138,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct instructors have both taught a course and conducted an advising appointment?'},
 {'id': 139,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct departments have both bachelor and master programs?'},
 {'id': 140,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct students have both a completed enrollment and a high-risk advising appointment?'},
 {'id': 141,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct courses have students from more than one degree level?'},
 {'id': 142,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct programs have students advised by instructors from the same department as the program?'},
 {'id': 143,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct students completed a course taught by their assigned advisor?'},
 {'id': 144,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct instructors taught both active and inactive courses?'},
 {'id': 145,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct departments had courses with both completed and withdrawn enrollments?'},
 {'id': 146,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct students had attendance records in at least three different courses?'},
 {'id': 147,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct courses were attended by both domestic and international students?'},
 {'id': 148,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct programs include courses taught by at least three different instructors?'},
 {'id': 149,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': "How many distinct students earned credits in courses outside their program's department?"},
 {'id': 150,
  'category': 'distinct_count',
  'difficulty': 'hard',
  'query': 'How many distinct instructors taught courses with students from both resident and nonresident groups?'},
 {'id': 151, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count students by student status.'},
 {'id': 152, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count students by current year level.'},
 {'id': 153, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Show average student GPA by citizenship status.'},
 {'id': 154, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count departments by campus code.'},
 {'id': 155, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Show total annual budget by school name.'},
 {'id': 156, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count instructors by employment type.'},
 {'id': 157, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Show average instructor salary by academic rank.'},
 {'id': 158, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count programs by degree level.'},
 {'id': 159,
  'category': 'group_by',
  'difficulty': 'easy',
  'query': 'Show average tuition per credit by delivery mode.'},
 {'id': 160, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count courses by semester.'},
 {'id': 161, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Show average course capacity by course level.'},
 {'id': 162, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count enrollments by enrollment status.'},
 {'id': 163, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Show average numeric grade by final grade.'},
 {'id': 164, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count advising appointments by appointment type.'},
 {'id': 165, 'category': 'group_by', 'difficulty': 'easy', 'query': 'Count attendance records by attendance status.'},
 {'id': 166, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Count active students by program.'},
 {'id': 167, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Show average GPA by program degree level.'},
 {'id': 168,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show total credits earned by student year level.'},
 {'id': 169,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Count instructors by department and tenure status.'},
 {'id': 170,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show average instructor salary by department.'},
 {'id': 171, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Count active programs by department.'},
 {'id': 172,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show total current enrollment by degree level.'},
 {'id': 173,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Count courses by department and delivery mode.'},
 {'id': 174,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show total enrolled course seats by academic year.'},
 {'id': 175, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Show completed enrollment count by course.'},
 {'id': 176,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show average attendance percentage by instructor.'},
 {'id': 177,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show total tuition amount by enrollment status.'},
 {'id': 178, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Show total scholarship amount by program.'},
 {'id': 179,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Count advising appointments by risk level and meeting mode.'},
 {'id': 180,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show average advising satisfaction by instructor.'},
 {'id': 181,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Count attendance records by course and session type.'},
 {'id': 182,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show average quiz score by attendance status.'},
 {'id': 183, 'category': 'group_by', 'difficulty': 'moderate', 'query': 'Show total participation points by course.'},
 {'id': 184,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Count students by program and financial-aid status.'},
 {'id': 185,
  'category': 'group_by',
  'difficulty': 'moderate',
  'query': 'Show average GPA by housing status and residency status.'},
 {'id': 186,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show completed enrollment count by department and degree level.'},
 {'id': 187,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show average numeric grade by program and course delivery mode.'},
 {'id': 188,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show total tuition and scholarship amounts by department.'},
 {'id': 189,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show active student count by department and citizenship status.'},
 {'id': 190,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show average instructor salary by school and academic rank.'},
 {'id': 191,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show course capacity and enrolled count by program and semester.'},
 {'id': 192,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show advising appointment count by program and academic risk level.'},
 {'id': 193,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show average advising satisfaction by student year level and appointment type.'},
 {'id': 194,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show attendance record count by program and attendance status.'},
 {'id': 195,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show average quiz score by department and session type.'},
 {'id': 196,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show credits earned by instructor and course level.'},
 {'id': 197,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show completed enrollment tuition by degree level and academic year.'},
 {'id': 198,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show active student count, course count, and instructor count by department.'},
 {'id': 199,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show average attendance percentage by program and course delivery mode.'},
 {'id': 200,
  'category': 'group_by',
  'difficulty': 'hard',
  'query': 'Show student count and average GPA by advisor and degree level.'},
 {'id': 201,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List student statuses represented by more than 10 students.'},
 {'id': 202, 'category': 'having', 'difficulty': 'easy', 'query': 'List year levels with an average GPA above 3.'},
 {'id': 203,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List departments with annual budgets above 2 million dollars.'},
 {'id': 204, 'category': 'having', 'difficulty': 'easy', 'query': 'List schools with more than 5 departments.'},
 {'id': 205,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List employment types with more than 10 instructors.'},
 {'id': 206,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List academic ranks with an average salary above 90000 dollars.'},
 {'id': 207,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List degree levels offered by more than 5 programs.'},
 {'id': 208,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List delivery modes with an average tuition per credit above 500 dollars.'},
 {'id': 209, 'category': 'having', 'difficulty': 'easy', 'query': 'List semesters containing more than 10 courses.'},
 {'id': 210,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List course levels with an average capacity above 70 students.'},
 {'id': 211,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List enrollment statuses represented by more than 10 records.'},
 {'id': 212,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List final grades with an average numeric grade above 80.'},
 {'id': 213,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List advising appointment types with more than 5 meetings.'},
 {'id': 214,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List attendance statuses appearing more than 10 times.'},
 {'id': 215,
  'category': 'having',
  'difficulty': 'easy',
  'query': 'List session types with an average quiz score above 70.'},
 {'id': 216,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List programs with more than 3 active students.'},
 {'id': 217,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List departments with more than 2 active instructors.'},
 {'id': 218, 'category': 'having', 'difficulty': 'moderate', 'query': 'List instructors teaching more than 2 courses.'},
 {'id': 219,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List courses with more than 2 completed enrollments.'},
 {'id': 220,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List students with more than 2 enrollment records.'},
 {'id': 221,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List students whose total earned credits from enrollments exceed 6.'},
 {'id': 222,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List programs whose total scholarship amount exceeds 5000 dollars.'},
 {'id': 223,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List departments whose total instructor payroll exceeds 200000 dollars.'},
 {'id': 224,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List courses with an average attendance percentage above 85 percent.'},
 {'id': 225,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List instructors whose students have an average numeric grade above 80.'},
 {'id': 226,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List advisors who conducted more than 2 advising appointments.'},
 {'id': 227,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List students who attended more than 3 recorded class sessions.'},
 {'id': 228,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List courses with more than 2 absent attendance records.'},
 {'id': 229,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List programs with an average student GPA above 3.2.'},
 {'id': 230,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List departments with more than 3 active courses.'},
 {'id': 231,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List degree levels whose total current enrollment exceeds 200.'},
 {'id': 232,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List research areas with an average instructor performance rating above 3.5.'},
 {'id': 233,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List housing statuses with more than 5 students receiving financial aid.'},
 {'id': 234,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List courses whose total tuition amount exceeds 10000 dollars.'},
 {'id': 235,
  'category': 'having',
  'difficulty': 'moderate',
  'query': 'List instructors with more than 3 completed student enrollments.'},
 {'id': 236,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List departments whose average student GPA is above the university-wide average GPA.'},
 {'id': 237,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List programs whose completed enrollment rate is above 60 percent.'},
 {'id': 238,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List instructors whose average student grade is above the overall instructor average grade.'},
 {'id': 239,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List courses whose average attendance percentage is above the average for their department.'},
 {'id': 240,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List students whose total scholarship amount exceeds half of their total tuition amount.'},
 {'id': 241,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List departments where active student count is greater than reported department student count divided by '
           'ten.'},
 {'id': 242,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List programs with students from at least three citizenship statuses.'},
 {'id': 243,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List courses taken by students from at least three different programs.'},
 {'id': 244,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List instructors who teach courses in more than one department.'},
 {'id': 245,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List students with completed enrollments in at least three different courses.'},
 {'id': 246,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List departments whose total course enrollment exceeds their reported student count.'},
 {'id': 247,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List programs whose average course seat utilization exceeds 75 percent.'},
 {'id': 248,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List advisors whose high-risk students have an average GPA below 2.5.'},
 {'id': 249,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List courses where more than 20 percent of attendance records are absent.'},
 {'id': 250,
  'category': 'having',
  'difficulty': 'hard',
  'query': 'List degree levels whose average completed-course grade exceeds the overall completed-course average.'},
 {'id': 251, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each program with its department name.'},
 {'id': 252, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each instructor with their department name.'},
 {'id': 253, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each student with their program name.'},
 {'id': 254, 'category': 'join', 'difficulty': 'easy', 'query': "Show each student with their advisor's name."},
 {'id': 255, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each course with its department name.'},
 {'id': 256, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each course with its program name.'},
 {'id': 257, 'category': 'join', 'difficulty': 'easy', 'query': "Show each course with its instructor's name."},
 {'id': 258,
  'category': 'join',
  'difficulty': 'easy',
  'query': 'Show each course with the title of its prerequisite course.'},
 {'id': 259,
  'category': 'join',
  'difficulty': 'easy',
  'query': "Show each advising appointment with the student's name."},
 {'id': 260,
  'category': 'join',
  'difficulty': 'easy',
  'query': "Show each advising appointment with the advisor's name."},
 {'id': 261, 'category': 'join', 'difficulty': 'easy', 'query': "Show each enrollment with the student's name."},
 {'id': 262, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each enrollment with the course title.'},
 {'id': 263, 'category': 'join', 'difficulty': 'easy', 'query': "Show each enrollment with the instructor's name."},
 {'id': 264, 'category': 'join', 'difficulty': 'easy', 'query': "Show each attendance record with the student's name."},
 {'id': 265, 'category': 'join', 'difficulty': 'easy', 'query': 'Show each attendance record with the course title.'},
 {'id': 266,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List active students with their program names and degree levels.'},
 {'id': 267,
  'category': 'join',
  'difficulty': 'moderate',
  'query': "List international students with their advisors' names."},
 {'id': 268,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List active instructors with their department names and salaries.'},
 {'id': 269,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List online programs with their department names and tuition per credit.'},
 {'id': 270,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List active courses with their instructor names and enrolled counts.'},
 {'id': 271,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List courses that have prerequisites with both course titles.'},
 {'id': 272,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List completed enrollments with student names and final grades.'},
 {'id': 273,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List withdrawn enrollments with student names and withdrawal dates.'},
 {'id': 274,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List advising appointments for high-risk students with student names.'},
 {'id': 275,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List career advising appointments with advisor names and satisfaction scores.'},
 {'id': 276,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List absent attendance records with student names and class dates.'},
 {'id': 277,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List late attendance records with course titles and minutes late.'},
 {'id': 278,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List students receiving financial aid with their program names.'},
 {'id': 279,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List instructors researching databases with their department names.'},
 {'id': 280,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List graduate-level courses with program names and instructor names.'},
 {'id': 281,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List enrollments with tuition amounts and program names.'},
 {'id': 282,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List students whose advisor is tenured with both names.'},
 {'id': 283, 'category': 'join', 'difficulty': 'moderate', 'query': 'List courses offered by accredited departments.'},
 {'id': 284,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List attendance records for exam sessions with the responsible instructor.'},
 {'id': 285,
  'category': 'join',
  'difficulty': 'moderate',
  'query': 'List students on leave with their program directors.'},
 {'id': 286,
  'category': 'join',
  'difficulty': 'hard',
  'query': "List students whose assigned advisor belongs to a different department than the student's program."},
 {'id': 287,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List courses whose instructor belongs to a different department than the course.'},
 {'id': 288,
  'category': 'join',
  'difficulty': 'hard',
  'query': "List enrollments where the recorded instructor differs from the course's assigned instructor."},
 {'id': 289,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List attendance records where the recorded instructor differs from the enrollment instructor.'},
 {'id': 290,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List students enrolled in a course taught by their assigned advisor.'},
 {'id': 291,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List courses whose prerequisite belongs to a different department.'},
 {'id': 292,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List active students in programs whose departments are inactive.'},
 {'id': 293,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List instructors teaching courses outside their own department.'},
 {'id': 294,
  'category': 'join',
  'difficulty': 'hard',
  'query': "List advising appointments where the advisor is not the student's assigned advisor."},
 {'id': 295,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List students whose enrollment course belongs to a different program than their own.'},
 {'id': 296,
  'category': 'join',
  'difficulty': 'hard',
  'query': "List attendance records where the student does not match the enrollment's student."},
 {'id': 297,
  'category': 'join',
  'difficulty': 'hard',
  'query': "List attendance records where the course does not match the enrollment's course."},
 {'id': 298, 'category': 'join', 'difficulty': 'hard', 'query': 'List completed enrollments for inactive courses.'},
 {'id': 299,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List students whose program director is also their course instructor.'},
 {'id': 300,
  'category': 'join',
  'difficulty': 'hard',
  'query': 'List courses where enrolled count exceeds capacity with department and program names.'},
 {'id': 301,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each student with their program and department names.'},
 {'id': 302,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each student with their advisor and advisor department.'},
 {'id': 303,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each course with its program and department names.'},
 {'id': 304,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each enrollment with student name, course title, and instructor name.'},
 {'id': 305,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each advising appointment with student name, advisor name, and program name.'},
 {'id': 306,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each attendance record with student name, course title, and instructor name.'},
 {'id': 307,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each completed enrollment with student name, program name, and final grade.'},
 {'id': 308,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each course with instructor name and instructor department.'},
 {'id': 309,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each student with program name and program director.'},
 {'id': 310,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each course with prerequisite title and department name.'},
 {'id': 311,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each enrollment with student year level and course level.'},
 {'id': 312,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each advising appointment with student GPA and advisor performance rating.'},
 {'id': 313,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each attendance record with enrollment status and student name.'},
 {'id': 314,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each program with department name and number of active students.'},
 {'id': 315,
  'category': 'multi_table_join',
  'difficulty': 'easy',
  'query': 'Show each instructor with department name and number of courses taught.'},
 {'id': 316,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List active students with program, department, and advisor names.'},
 {'id': 317,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List completed enrollments with student name, program, course, and instructor.'},
 {'id': 318,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List international students enrolled in online courses with instructor names.'},
 {'id': 319,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List students receiving financial aid with tuition, scholarship, and program details.'},
 {'id': 320,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List high-risk advising appointments with student, program, and advisor details.'},
 {'id': 321,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List absent attendance records with student program and course instructor.'},
 {'id': 322,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List courses with prerequisites, showing both course titles and the program name.'},
 {'id': 323,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List tenured instructors teaching active courses with department and program names.'},
 {'id': 324,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List students who completed courses with grades above 90, including program and department.'},
 {'id': 325,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List career advising appointments for graduate students with advisor department.'},
 {'id': 326,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List online courses with enrolled students and their citizenship statuses.'},
 {'id': 327,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List active bachelor-program students with their advisor and department chair.'},
 {'id': 328,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List late attendance records for completed enrollments with student and course details.'},
 {'id': 329,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List students enrolled in courses outside their program, with both program names.'},
 {'id': 330,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List instructors who both teach courses and advise students, with department names.'},
 {'id': 331,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List departments with their active programs, active courses, and instructors.'},
 {'id': 332,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List completed enrollments in courses requiring prerequisites, with both course titles.'},
 {'id': 333,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List students with advising appointments and attendance records on the same course date year.'},
 {'id': 334,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List course enrollments with student housing status and instructor tenure status.'},
 {'id': 335,
  'category': 'multi_table_join',
  'difficulty': 'moderate',
  'query': 'List attendance records for financially aided students with course and program details.'},
 {'id': 336,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List students who completed an online course taught by their assigned advisor, with program and '
           'department.'},
 {'id': 337,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List students with high-risk advising who also have a failed enrollment, with advisor and course.'},
 {'id': 338,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List instructors who teach students from a program in a different department than their own.'},
 {'id': 339,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List courses whose students come from at least two degree levels, with instructor and department.'},
 {'id': 340,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List students who attended courses in both their own department and another department.'},
 {'id': 341,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List departments whose instructors advise students from programs in other departments.'},
 {'id': 342,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List students with completed enrollments and absent attendance records for the same course.'},
 {'id': 343,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List courses where the course instructor, enrollment instructor, and attendance instructor do not all '
           'match.'},
 {'id': 344,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List students who received scholarships for courses taught by tenured instructors outside their program.'},
 {'id': 345,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': "List advisors whose assigned students completed courses taught by another instructor in the advisor's "
           'department.'},
 {'id': 346,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': "List programs whose students enrolled in every delivery mode offered by that program's department."},
 {'id': 347,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List students who completed a prerequisite course before enrolling in a course that requires it.'},
 {'id': 348,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List instructors teaching active courses whose enrolled students have high-risk advising records.'},
 {'id': 349,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List departments with active students, completed enrollments, and absent attendance records.'},
 {'id': 350,
  'category': 'multi_table_join',
  'difficulty': 'hard',
  'query': 'List students whose advisor, course instructor, and advising instructor are three different people.'},
 {'id': 351,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 students with the highest cumulative GPA.'},
 {'id': 352,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 students with the most credits earned.'},
 {'id': 353,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 5 departments with the largest annual budgets.'},
 {'id': 354,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 5 departments with the highest reported student counts.'},
 {'id': 355,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 instructors with the highest salaries.'},
 {'id': 356,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 instructors with the highest performance ratings.'},
 {'id': 357,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 5 programs with the highest tuition per credit.'},
 {'id': 358,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 5 programs with the most current enrollment.'},
 {'id': 359,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 courses with the largest capacity.'},
 {'id': 360,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 courses with the highest enrolled count.'},
 {'id': 361,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 enrollments with the highest numeric grades.'},
 {'id': 362,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 enrollments with the largest scholarship amounts.'},
 {'id': 363,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 advising appointments with the highest satisfaction scores.'},
 {'id': 364,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 attendance records with the highest quiz scores.'},
 {'id': 365,
  'category': 'order_limit_topk',
  'difficulty': 'easy',
  'query': 'Show the 10 attendance records with the most minutes late.'},
 {'id': 366,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 programs by number of active students.'},
 {'id': 367,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 5 departments by number of active instructors.'},
 {'id': 368,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 instructors by number of courses taught.'},
 {'id': 369,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 courses by number of completed enrollments.'},
 {'id': 370,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 students by total tuition charged.'},
 {'id': 371,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 students by total scholarship received.'},
 {'id': 372,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 5 programs by total scholarship amount.'},
 {'id': 373,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 5 departments by total instructor payroll.'},
 {'id': 374,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 courses by average numeric grade.'},
 {'id': 375,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 instructors by average student grade.'},
 {'id': 376,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 students by number of advising appointments.'},
 {'id': 377,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 advisors by number of completed appointments.'},
 {'id': 378,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 courses by number of absent attendance records.'},
 {'id': 379,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 5 programs by average student GPA.'},
 {'id': 380,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 courses by average attendance percentage.'},
 {'id': 381,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 5 degree levels by total current enrollment.'},
 {'id': 382,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 research areas by average instructor performance rating.'},
 {'id': 383,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 students by number of completed enrollments.'},
 {'id': 384,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 courses by total tuition amount.'},
 {'id': 385,
  'category': 'order_limit_topk',
  'difficulty': 'moderate',
  'query': 'Show the top 10 instructors by number of student attendance records.'},
 {'id': 386,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 students by GPA within each program.'},
 {'id': 387,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the highest-paid instructor in each department.'},
 {'id': 388,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 courses by enrolled count within each department.'},
 {'id': 389,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 programs by active student count within each degree level.'},
 {'id': 390,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 5 advisors by average GPA of their assigned students.'},
 {'id': 391,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 instructors by average completed-course grade within each department.'},
 {'id': 392,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 courses by attendance rate within each program.'},
 {'id': 393,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 5 students by scholarship percentage among students charged at least 5000 dollars in '
           'tuition.'},
 {'id': 394,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 departments by course seat utilization.'},
 {'id': 395,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 5 programs by completed enrollment rate.'},
 {'id': 396,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 courses with the most distinct student programs represented.'},
 {'id': 397,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 5 instructors by completed enrollments per course taught.'},
 {'id': 398,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 departments by average active-student GPA.'},
 {'id': 399,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 5 students by attended class sessions within each current year level.'},
 {'id': 400,
  'category': 'order_limit_topk',
  'difficulty': 'hard',
  'query': 'Show the top 3 programs by average advising satisfaction among programs with at least three appointments.'},
 {'id': 401,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List people who appear either as students or instructors.'},
 {'id': 402,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List department identifiers that appear either in programs or courses.'},
 {'id': 403,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List instructor identifiers that appear either as student advisors or course instructors.'},
 {'id': 404,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List student identifiers that appear either in enrollments or advising appointments.'},
 {'id': 405,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List course identifiers that appear either in enrollments or attendance records.'},
 {'id': 406,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List instructor identifiers that appear either in enrollments or attendance records.'},
 {'id': 407,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List program identifiers that appear either in student records or course records.'},
 {'id': 408,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List students who are either active or on leave.'},
 {'id': 409,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List instructors who are either full time or part time.'},
 {'id': 410,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List programs that use either online or hybrid delivery.'},
 {'id': 411,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List courses offered either in fall or spring.'},
 {'id': 412,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List enrollments that are either completed or failed.'},
 {'id': 413,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List advising appointments that are either career or graduation related.'},
 {'id': 414,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List attendance records marked either absent or late.'},
 {'id': 415,
  'category': 'set_operations',
  'difficulty': 'easy',
  'query': 'List departments located either on the main campus or north campus.'},
 {'id': 416,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List students who have both an enrollment and an advising appointment.'},
 {'id': 417,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List instructors who both teach a course and advise at least one student.'},
 {'id': 418,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List courses that have both enrollment records and attendance records.'},
 {'id': 419,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List departments that have both programs and instructors.'},
 {'id': 420,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List programs that have both students and courses.'},
 {'id': 421,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List students who have a completed enrollment but no failed enrollment.'},
 {'id': 422,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List courses that have completed enrollments but no withdrawn enrollments.'},
 {'id': 423,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List instructors who teach active courses but have no advising appointments.'},
 {'id': 424,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List students who received advising but have no enrollment records.'},
 {'id': 425,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List programs with active students but no active courses.'},
 {'id': 426,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List departments with active instructors but no active programs.'},
 {'id': 427,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List students who attended an online course but never attended an in-person course.'},
 {'id': 428,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List courses attended by international students but not domestic students.'},
 {'id': 429,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List instructors who taught completed enrollments but no failed enrollments.'},
 {'id': 430,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List students with present attendance records but no absent attendance records.'},
 {'id': 431,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List programs represented in both completed and withdrawn enrollments.'},
 {'id': 432,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List departments represented by both bachelor and master programs.'},
 {'id': 433,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List students who have both high-risk advising and completed advising appointments.'},
 {'id': 434,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List courses taught by tenured instructors but not by non-tenured instructors.'},
 {'id': 435,
  'category': 'set_operations',
  'difficulty': 'moderate',
  'query': 'List instructors whose students include both residents and nonresidents.'},
 {'id': 436,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List students who completed both online and in-person courses but never completed a hybrid course.'},
 {'id': 437,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List instructors who both teach courses and conduct advising but are not assigned as student advisors.'},
 {'id': 438,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List programs with students in both domestic and international groups but no permanent-resident students.'},
 {'id': 439,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List departments that offer both bachelor and master programs but no doctorate program.'},
 {'id': 440,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List students who have both completed and withdrawn enrollments but no failed enrollment.'},
 {'id': 441,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List courses with both present and late attendance records but no absent records.'},
 {'id': 442,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List instructors who taught both active and inactive courses but never taught an online course.'},
 {'id': 443,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List students who received both academic-plan and career advising but no probation advising.'},
 {'id': 444,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List departments with both tenured and tenure-track instructors but no lecturer.'},
 {'id': 445,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List programs whose students attended both lecture and lab sessions but no exam session.'},
 {'id': 446,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List courses taken by both financially aided and non-aided students but no international students.'},
 {'id': 447,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List students with enrollments in both their own program and another program but no failed enrollment.'},
 {'id': 448,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List instructors who taught both undergraduate and graduate course levels but no 600-level course.'},
 {'id': 449,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List departments with both completed and failed enrollments but no withdrawn enrollments.'},
 {'id': 450,
  'category': 'set_operations',
  'difficulty': 'hard',
  'query': 'List programs with both active and graduated students but no withdrawn students.'},
 {'id': 451,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List students whose GPA is above the overall student average.'},
 {'id': 452,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List students with more credits earned than the overall student average.'},
 {'id': 453,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List departments with budgets above the average department budget.'},
 {'id': 454,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List instructors earning more than the average instructor salary.'},
 {'id': 455,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List instructors with performance ratings above the instructor average.'},
 {'id': 456,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List programs with tuition per credit above the program average.'},
 {'id': 457,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List programs with current enrollment above the average program enrollment.'},
 {'id': 458,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List courses with capacity above the average course capacity.'},
 {'id': 459,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List courses with enrolled count above the average course enrollment.'},
 {'id': 460,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List enrollments with numeric grades above the completed-enrollment average.'},
 {'id': 461,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List enrollments with scholarship amounts above the average scholarship.'},
 {'id': 462,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List advising appointments longer than the average advising appointment.'},
 {'id': 463,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List attendance records with quiz scores above the average quiz score.'},
 {'id': 464,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List students who have never received an advising appointment.'},
 {'id': 465,
  'category': 'subquery_cte',
  'difficulty': 'easy',
  'query': 'List courses that have never had an enrollment record.'},
 {'id': 466,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List students whose GPA is above the average GPA for their program.'},
 {'id': 467,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List instructors earning more than the average salary in their department.'},
 {'id': 468,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List programs with current enrollment above the average for their degree level.'},
 {'id': 469,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List courses with enrolled count above the average for their department.'},
 {'id': 470,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List enrollments with numeric grades above the average for the same course.'},
 {'id': 471,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List students whose total tuition is above the average student total tuition.'},
 {'id': 472,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List students whose total scholarship is above the average among scholarship recipients.'},
 {'id': 473,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List instructors who teach more courses than the average instructor who teaches a course.'},
 {'id': 474,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List courses with more completed enrollments than the average course.'},
 {'id': 475,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List advisors who conducted more appointments than the average advisor.'},
 {'id': 476,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List students with more attendance records than the average student with attendance.'},
 {'id': 477,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List courses whose average quiz score is above the average course quiz score.'},
 {'id': 478,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List departments whose active student count is above the average department active student count.'},
 {'id': 479,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List programs whose average student GPA is above the average program GPA.'},
 {'id': 480,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List instructors whose students have an average grade above the overall completed-enrollment average.'},
 {'id': 481,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List students whose most recent enrollment is completed.'},
 {'id': 482,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List courses whose latest attendance record was marked absent.'},
 {'id': 483,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List programs where every active student has a GPA above 2.5.'},
 {'id': 484,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List instructors for whom every active course has at least one enrollment.'},
 {'id': 485,
  'category': 'subquery_cte',
  'difficulty': 'moderate',
  'query': 'List departments where every active program has current enrollment above zero.'},
 {'id': 486,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List the student with the highest GPA in each program.'},
 {'id': 487,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List the highest-paid instructor in each department.'},
 {'id': 488,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List the course with the highest enrolled count in each program.'},
 {'id': 489,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List students whose GPA is above the average for their degree level and whose credits exceed their program '
           'average.'},
 {'id': 490,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List instructors whose average student grade is above the average instructor grade within their '
           'department.'},
 {'id': 491,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List programs whose completed-enrollment rate is above the average rate for their degree level.'},
 {'id': 492,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List courses whose attendance rate is above the average attendance rate in their department.'},
 {'id': 493,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List departments whose instructor payroll is above the average payroll for departments in the same '
           'school.'},
 {'id': 494,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List students who completed every course in which they have an enrollment record.'},
 {'id': 495,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List instructors for whom every recorded enrollment is completed.'},
 {'id': 496,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List programs whose students have taken every delivery mode used by courses in that program.'},
 {'id': 497,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List departments where every active instructor teaches at least one active course.'},
 {'id': 498,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List students whose three most recent completed grades improved each time.'},
 {'id': 499,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List courses whose 2025 completed enrollment count exceeded their 2024 count.'},
 {'id': 500,
  'category': 'subquery_cte',
  'difficulty': 'hard',
  'query': 'List instructors whose advising satisfaction is above the overall advisor average and whose student grades '
           'are above the overall instructor average.'}]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run 500 fixed students-database natural-language queries against SpiderSQL."
    )
    parser.add_argument(
        "--database-id",
        type=int,
        default=55,
        help="SpiderSQL database ID. Defaults to the uploaded students database ID 55.",
    )
    parser.add_argument(
        "--base-url",
        default="http://127.0.0.1:8000",
        help="SpiderSQL backend base URL.",
    )
    parser.add_argument(
        "--output",
        default="students_db55_500_query_sql_results.txt",
        help="Single TXT output file containing each query and its generated SQL.",
    )
    parser.add_argument(
        "--timeout",
        type=int,
        default=180,
        help="Per-query HTTP timeout in seconds.",
    )
    parser.add_argument(
        "--start-index",
        type=int,
        default=1,
        help="Start at this 1-based test number. Useful after an interrupted run.",
    )
    parser.add_argument(
        "--end-index",
        type=int,
        default=len(TEST_CASES),
        help="Stop at this 1-based test number.",
    )
    return parser.parse_args()


def _trace_headers(trace_meta: dict[str, str] | None) -> dict[str, str]:
    """Emit the optional X-SpiderSQL-* diagnostic headers so full-trace runs
    capture per-test metadata (test id / category / difficulty / trace run).
    No-op ({}) when trace_meta is None. Only sent when values are present."""
    if not trace_meta:
        return {}
    name = {"test_id": "X-SpiderSQL-Test-ID", "category": "X-SpiderSQL-Category",
            "difficulty": "X-SpiderSQL-Difficulty", "trace_run": "X-SpiderSQL-Trace-Run"}
    return {name[k]: str(v) for k, v in trace_meta.items() if k in name and v}


def post_query(base_url: str, database_id: int, question: str, timeout: int, trace_meta: dict[str, str] | None = None) -> tuple[int, dict[str, Any]]:
    url = f"{base_url.rstrip('/')}/database/{database_id}/execute_sql"
    request_body = json.dumps({"question": question}).encode("utf-8")
    request = urllib.request.Request(
        url,
        data=request_body,
        headers={"Content-Type": "application/json", "Accept": "application/json",
                 **_trace_headers(trace_meta)},
        method="POST",
    )

    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            status_code = response.getcode()
            raw = response.read().decode("utf-8", errors="replace")
    except urllib.error.HTTPError as exc:
        status_code = exc.code
        raw = exc.read().decode("utf-8", errors="replace")
    except Exception as exc:
        return 0, {"success": False, "_client_error": str(exc)}

    try:
        payload = json.loads(raw) if raw.strip() else {}
    except json.JSONDecodeError:
        payload = {"success": False, "_raw_response": raw}

    if not isinstance(payload, dict):
        payload = {"success": False, "_raw_response": payload}

    return status_code, payload


def extract_sql(payload: dict[str, Any]) -> str:
    generated = payload.get("generated_sql")

    if isinstance(generated, dict):
        for key in ("sql", "query", "generated_sql"):
            value = generated.get(key)
            if isinstance(value, str) and value.strip():
                return value.strip()

    if isinstance(generated, str) and generated.strip():
        return generated.strip()

    for key in ("sql", "query_sql", "final_sql"):
        value = payload.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()

    execution = payload.get("execution")
    if isinstance(execution, dict):
        for key in ("sql", "executed_sql"):
            value = execution.get(key)
            if isinstance(value, str) and value.strip():
                return value.strip()

    return ""


def execution_succeeded(http_status: int, payload: dict[str, Any]) -> bool:
    if http_status < 200 or http_status >= 300:
        return False

    top_level = payload.get("success")
    execution = payload.get("execution")

    if top_level is False:
        return False

    if isinstance(execution, dict) and execution.get("success") is False:
        return False

    if top_level is True:
        return True

    if isinstance(execution, dict) and execution.get("success") is True:
        return True

    return False


def format_record(case: dict[str, Any], status: str, sql: str) -> str:
    displayed_sql = sql if sql else "<NO SQL GENERATED>"
    separator = "=" * 100
    return (
        f"{separator}\n"
        f"TEST {case['id']:03d}\n"
        f"CATEGORY: {case['category']}\n"
        f"DIFFICULTY: {case['difficulty']}\n"
        f"STATUS: {status}\n"
        f"QUERY:\n{case['query']}\n"
        f"SQL:\n{displayed_sql}\n"
    )


def main() -> int:
    args = parse_args()

    if args.start_index < 1 or args.end_index > len(TEST_CASES) or args.start_index > args.end_index:
        print(
            f"Invalid range. Use 1 <= start-index <= end-index <= {len(TEST_CASES)}.",
            file=sys.stderr,
        )
        return 2

    selected_cases = [
        case for case in TEST_CASES
        if args.start_index <= case["id"] <= args.end_index
    ]

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # A complete run overwrites the file. A resumed partial run appends.
    file_mode = "w" if args.start_index == 1 else "a"

    pass_count = 0
    fail_count = 0
    run_started = time.time()

    with output_path.open(file_mode, encoding="utf-8") as output:
        for position, case in enumerate(selected_cases, start=1):
            http_status, payload = post_query(
                base_url=args.base_url,
                database_id=args.database_id,
                question=case["query"],
                timeout=args.timeout,
                trace_meta={
                    "test_id": str(case.get("id", position)),
                    "category": case.get("category"),
                    "difficulty": case.get("difficulty"),
                    "trace_run": getattr(args, "trace_run", None),
                },
            )

            sql = extract_sql(payload)
            passed = execution_succeeded(http_status, payload)
            status = "PASS" if passed else "FAIL"

            if passed:
                pass_count += 1
            else:
                fail_count += 1

            print(
                f"[{position:03d}/{len(selected_cases):03d}] "
                f"{status} | TEST {case['id']:03d} | "
                f"{case['category']} | {case['difficulty']}",
                flush=True,
            )

            output.write(format_record(case, status, sql))
            output.flush()

    elapsed = time.time() - run_started
    print("-" * 100)
    print(f"Completed: {len(selected_cases)}")
    print(f"PASS: {pass_count}")
    print(f"FAIL: {fail_count}")
    print(f"Elapsed seconds: {elapsed:.1f}")
    print(f"TXT output: {output_path.resolve()}")

    return 0 if fail_count == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
